Repository Opentrons/opentrons, pull requests merged in 2022-11, with the labels that each got.

#11625 refactor(api): engine based temperature module core
  api/src/opentrons/protocol_api/core/engine/module_core.py
  api/src/opentrons/protocol_engine/clients/sync_client.py
  api/src/opentrons/protocol_engine/commands/temperature_module/deactivate.py
  api/src/opentrons/protocol_engine/commands/temperature_module/set_target_temperature.py
  api/src/opentrons/protocol_engine/commands/temperature_module/wait_for_temperature.py
  api/tests/opentrons/protocol_api/core/engine/test_temperature_module_core.py
  api/tests/opentrons/protocol_engine/clients/test_sync_client.py
Labels: robot-svcs

#11629 refactor(api): engine based magnetic module core
  api/src/opentrons/protocol_api/core/engine/exceptions.py
  api/src/opentrons/protocol_api/core/engine/module_core.py
  api/src/opentrons/protocol_api_experimental/module_contexts/magnetic_module_context.py
  api/src/opentrons/protocol_engine/clients/sync_client.py
  api/src/opentrons/protocol_engine/errors/exceptions.py
  api/src/opentrons/protocol_engine/state/labware.py
  api/tests/opentrons/protocol_api/core/engine/test_magnetic_module_core.py
  api/tests/opentrons/protocol_api_experimental/module_contexts/test_magnetic_module_context.py
  api/tests/opentrons/protocol_engine/clients/test_sync_client.py
  api/tests/opentrons/protocol_engine/conftest.py
  api/tests/opentrons/protocol_engine/state/test_labware_view.py
Labels: robot-svcs

#11661 fix(api): ensure passed in pipette and labware names are lowercased
  api/src/opentrons/protocol_api/protocol_context.py
  api/src/opentrons/protocol_api/validation.py
  api/tests/opentrons/protocol_api/test_protocol_context.py
  api/tests/opentrons/protocol_api/test_validation.py
Labels: papi-v2, robot-svcs

#11692 fix(robot-server): Do not raise exception when unpickling unknown types
  robot-server/robot_server/persistence/legacy_pickle.py
Labels: robot server

#11694 fix(api): ensure Thermocycler status APIs return vanilla strings
  api/src/opentrons/protocol_api/module_contexts.py
  api/tests/opentrons/protocol_api/test_thermocycler_context.py
  api/tests/opentrons/protocol_api_old/test_module_context.py
Labels: api, fix, papi-v2

#11700 refactor(api): Add pause and delay handling to ProtocolEngine PAPI core
  api/src/opentrons/protocol_api/core/engine/protocol.py
  api/src/opentrons/protocol_engine/clients/sync_client.py
  api/tests/opentrons/protocol_api/core/engine/test_protocol_core.py
  api/tests/opentrons/protocol_engine/clients/test_sync_client.py
Labels: api, papi-v2, robot-svcs, protocol-engine

#11703 refactor(api): Support protocol.comment() backed by ProtocolEngine core
  api/src/opentrons/protocol_api/core/engine/protocol.py
  api/src/opentrons/protocol_engine/clients/sync_client.py
  api/src/opentrons/protocol_engine/commands/__init__.py
  api/src/opentrons/protocol_engine/commands/command_unions.py
  api/src/opentrons/protocol_engine/commands/custom.py
  api/tests/opentrons/protocol_api/core/engine/test_protocol_core.py
  api/tests/opentrons/protocol_engine/clients/test_sync_client.py
Labels: api, papi-v2, robot-svcs, protocol-engine

#11689 refactor(api): add dispense to PAPI engine core
  api/src/opentrons/commands/commands.py
  api/src/opentrons/protocol_api/core/engine/instrument.py
  api/src/opentrons/protocol_api/core/engine/labware.py
  api/src/opentrons/protocol_api/core/instrument.py
  api/src/opentrons/protocol_api/core/labware.py
  api/src/opentrons/protocol_api/core/protocol_api/instrument_context.py
  api/src/opentrons/protocol_api/core/protocol_api/labware.py
  api/src/opentrons/protocol_api/core/simulator/instrument_context.py
  api/src/opentrons/protocol_api/instrument_context.py
  api/src/opentrons/protocol_api_experimental/pipette_context.py
  api/src/opentrons/protocol_engine/clients/sync_client.py
  api/src/opentrons/protocol_engine/state/labware.py
  api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
  api/tests/opentrons/protocol_api/test_instrument_context.py
  api/tests/opentrons/protocol_api_experimental/test_pipette_context.py
  api/tests/opentrons/protocol_api_old/core/simulator/test_instrument_context.py
  api/tests/opentrons/protocol_engine/clients/test_sync_client.py
Labels: robot-svcs

#11715 fix(app): include enabling log aggregation as toggle in robot settings
  app/src/App/types.ts
  app/src/assets/localization/en/device_settings.json
  app/src/organisms/Devices/RobotSettings/RobotSettingsPrivacy.tsx
  app/src/organisms/Devices/RobotSettings/SettingToggle.tsx
  app/src/pages/Devices/RobotSettings/__tests__/RobotSettings.test.tsx
  app/src/pages/Devices/RobotSettings/index.tsx
Labels: fix

#11725 fix(app): remove cruft from robot card banner and prevent crash on load labware fail
  app/src/organisms/Devices/RobotStatusHeader.tsx
  app/src/organisms/Devices/__tests__/RobotStatusHeader.test.tsx
  shared-data/js/helpers/getLoadedLabwareDefinitionsByUri.ts
Labels: fix

#11726 fix(app): temporarily remove setup info commands until commands include resolved entities
  app/src/organisms/Devices/ProtocolRun/RunLogProtocolSetupInfo.tsx
  app/src/organisms/Devices/ProtocolRun/__tests__/RunLogProtocolSetupInfo.test.tsx
Labels: fix

#11724 fix(app): include offsets generated in current run when finding historic offset candidates
  app/src/organisms/ApplyHistoricOffsets/hooks/useHistoricRunDetails.ts
Labels: fix

#11741 fix(api): allow loadLiquid command to no-op when liquid FF is off
  api/src/opentrons/protocol_engine/commands/load_liquid.py
  api/src/opentrons/protocol_runner/protocol_runner.py
  api/tests/opentrons/cli/test_cli.py
  api/tests/opentrons/protocol_engine/commands/test_load_liquid.py
  api/tests/opentrons/protocol_runner/test_protocol_runner.py
  robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
Labels: robot-svcs

#11755 chore(build): Add workflow to start ot-3 builds
  .github/workflows/start-ot3-build.yaml
Labels: ot3-build

#11779 chore(app-shell): update electron minor update
  .nvmrc
  app-shell/electron-builder.config.js
  app-shell/package.json
  yarn.lock
Labels: ot3-build
