Repository Opentrons/opentrons, pull requests merged in 2024-09, with the labels that each got.

#16163 feat(protocol-designer): assign liquids modal
  components/src/atoms/buttons/LargeButton.tsx
  components/src/molecules/DropdownMenu/index.tsx
  components/src/organisms/Toolbox/index.tsx
  protocol-designer/src/NavigationBar.tsx
  protocol-designer/src/assets/localization/en/liquids.json
  protocol-designer/src/components/SelectionRect.tsx
  protocol-designer/src/organisms/AssignLiquidsModal/LiquidToolbox.tsx
  protocol-designer/src/organisms/AssignLiquidsModal/index.tsx
  protocol-designer/src/organisms/ProtocolMetadataNav/index.tsx
  protocol-designer/src/organisms/index.ts
  protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SlotOverflowMenu.test.tsx
  protocol-designer/src/pages/Designer/LiquidsOverflowMenu.tsx
  protocol-designer/src/pages/Designer/__tests__/LiquidsOverflowMenu.test.tsx
  protocol-designer/src/pages/Designer/index.tsx
  protocol-designer/src/pages/Liquids/__tests__/Liquids.test.tsx
  protocol-designer/src/pages/Liquids/index.tsx
Labels: authorship

#16188 feat(components, protocol-designer): create search bar for labware tools
  components/src/atoms/InputField/index.tsx
  components/src/atoms/ListButton/ListButtonChildren/ListButtonAccordionContainer.tsx
  components/src/atoms/ListButton/ListButtonChildren/ListButtonRadioButton.tsx
  components/src/organisms/Toolbox/__tests__/Toolbox.test.tsx
  components/src/organisms/Toolbox/index.tsx
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/organisms/AssignLiquidsModal/LiquidToolbox.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupTools.test.tsx
Labels: feature

#16186 feat(protocol-designer): edit protocol metadata modal
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/organisms/EditProtocolMetadataModal/__tests__/EditProtocolMetadataModal.test.tsx
  protocol-designer/src/organisms/EditProtocolMetadataModal/index.tsx
  protocol-designer/src/organisms/index.ts
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolOverview.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#16193 feat(components, protocol-designer): add a new type to buttonType for PD
  components/src/atoms/buttons/LargeButton.stories.tsx
  components/src/atoms/buttons/LargeButton.tsx
  components/src/atoms/buttons/__tests__/LargeButton.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#16180 feat(protocol-designer): deckThumbnail in Protocol overview
  protocol-designer/src/pages/ProtocolOverview/DeckThumbnail.tsx
  protocol-designer/src/pages/ProtocolOverview/DeckThumbnailDetails.tsx
  protocol-designer/src/pages/ProtocolOverview/SlotHover.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/DeckThumbnail.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
  protocol-designer/src/step-forms/utils/index.ts
Labels: authorship

#16176 feat(protocol-designer): zoomed in deck and off-deck setup
  components/src/atoms/ListButton/ListButtonChildren/ListButtonRadioButton.tsx
  components/src/atoms/buttons/RadioButton.tsx
  components/src/index.ts
  components/src/molecules/index.ts
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/labware-ingred/actions/actions.ts
  protocol-designer/src/labware-ingred/actions/thunks.ts
  protocol-designer/src/labware-ingred/reducers/index.ts
  protocol-designer/src/labware-ingred/selectors.ts
  protocol-designer/src/labware-ingred/types.ts
  protocol-designer/src/organisms/SlotDetailsContainer/index.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckItemHover.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/FixtureRender.tsx
  protocol-designer/src/pages/Designer/DeckSetup/HoveredItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedHoveredItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupContainer.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupTools.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/HoveredItems.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/LabwareTools.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedHoveredItems.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SlotOverflowMenu.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/pages/Designer/Offdeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/Offdeck/Offdeck.tsx
  protocol-designer/src/pages/Designer/Offdeck/__tests__/OffDeckDetails.test.tsx
  protocol-designer/src/pages/Designer/Offdeck/__tests__/Offdeck.test.tsx
  protocol-designer/src/pages/Designer/__tests__/Designer.test.tsx
  protocol-designer/src/pages/Designer/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/index.tsx
  protocol-designer/src/pages/Designer/utils.ts
  protocol-designer/src/step-forms/utils/index.ts
Labels: authorship

#16173 feat(protocol-designer, components) add materials list modal
  app/src/assets/localization/en/protocol_details.json
  app/src/organisms/Devices/HistoricalProtocolRunDrawer.tsx
  app/src/organisms/Devices/ProtocolRun/ProtocolRunModuleControls.tsx
  app/src/organisms/Devices/ProtocolRun/ProtocolRunRunTimeParameters.tsx
  app/src/organisms/ProtocolDetails/ProtocolLabwareDetails.tsx
  app/src/organisms/ProtocolDetails/ProtocolParameters/__tests__/ProtocolParameters.test.tsx
  app/src/organisms/ProtocolDetails/ProtocolParameters/index.tsx
  app/src/organisms/ProtocolDetails/__tests__/ProtocolLabwareDetails.test.tsx
  app/src/organisms/ProtocolSetupOffsets/index.tsx
  app/src/organisms/RunPreview/index.tsx
  components/src/molecules/InfoScreen/InfoScreen.stories.tsx
  components/src/molecules/InfoScreen/__tests__/InfoScreen.test.tsx
  components/src/molecules/InfoScreen/index.tsx
  components/src/molecules/ParametersTable/InfoScreen.tsx
  components/src/molecules/ParametersTable/__tests__/InfoScreen.test.tsx
  components/src/molecules/index.ts
  protocol-designer/src/assets/localization/en/protocol_overview.json
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/organisms/MaterialsListModal/MaterialsListModal.stories.tsx
  protocol-designer/src/organisms/MaterialsListModal/__tests__/MaterialsListModal.test.tsx
  protocol-designer/src/organisms/MaterialsListModal/index.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolOverview.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#16194 fix(protocol-designer): fix key prop issue
  protocol-designer/src/organisms/AssignLiquidsModal/LiquidToolbox.tsx
  protocol-designer/src/organisms/EditProtocolMetadataModal/index.tsx
Labels: authorship

#16190 feat(protocol-designer): edit instruments modal
  protocol-designer/src/assets/localization/en/protocol_overview.json
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/organisms/EditInstrumentsModal/editPipettes.ts
  protocol-designer/src/organisms/EditInstrumentsModal/index.tsx
  protocol-designer/src/organisms/EditInstrumentsModal/utils.ts
  protocol-designer/src/organisms/MaterialsListModal/index.tsx
  protocol-designer/src/organisms/PipetteInfoItem/__tests__/PipetteInfoItem.test.tsx
  protocol-designer/src/organisms/PipetteInfoItem/index.tsx
  protocol-designer/src/organisms/index.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolOverview.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#16196 feat(protocol-designer): wire up Liquid and Protocol step view
  components/src/atoms/ListItem/ListItemChildren/ListItemDescriptor.tsx
  protocol-designer/src/assets/localization/en/protocol_overview.json
  protocol-designer/src/organisms/EditInstrumentsModal/index.tsx
  protocol-designer/src/organisms/MaterialsListModal/__tests__/MaterialsListModal.test.tsx
  protocol-designer/src/organisms/MaterialsListModal/index.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolOverview.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#16213 feat(protocol-designer): off-deck labware thumbnail
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/organisms/SlotDetailsContainer/index.tsx
  protocol-designer/src/organisms/SlotInformation/__tests__/SlotInformation.test.tsx
  protocol-designer/src/organisms/SlotInformation/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SlotOverflowMenu.test.tsx
  protocol-designer/src/pages/Designer/Offdeck/OffDeckDetails.tsx
  protocol-designer/src/pages/ProtocolOverview/OffdeckThumbnail.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/OffdeckThumbnail.test.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolOverview.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#16211 feat(protocol-designer): add module and labware deck labels
  components/src/molecules/DeckLabel/__tests__/DeckLabel.test.tsx
  components/src/molecules/DeckLabel/index.tsx
  components/src/organisms/DeckLabelSet/DeckLabelSet.stories.tsx
  components/src/organisms/DeckLabelSet/__tests__/DeckLabelSet.test.tsx
  components/src/organisms/DeckLabelSet/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/HoveredItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/ModuleLabel.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedHoveredItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/HoveredItems.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedHoveredItems.test.tsx
  protocol-designer/src/pages/Designer/LabwareLabel.tsx
  protocol-designer/src/pages/Designer/Offdeck/Offdeck.tsx
Labels: authorship

#16229 fix(protocol-designer): material list deck location fix
  protocol-designer/src/organisms/MaterialsListModal/__tests__/MaterialsListModal.test.tsx
  protocol-designer/src/organisms/MaterialsListModal/index.tsx
Labels: authorship

#16226 refactor(protocol-designer): hardware toast only renders on first time
  protocol-designer/src/labware-ingred/actions/actions.ts
  protocol-designer/src/labware-ingred/reducers/index.ts
  protocol-designer/src/labware-ingred/selectors.ts
  protocol-designer/src/labware-ingred/types.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
  protocol-designer/src/pages/Designer/__tests__/Designer.test.tsx
  protocol-designer/src/pages/Designer/index.tsx
Labels: authorship

#16225 feat(protocol-designer): announcement modal for redesign
  protocol-designer/src/ProtocolEditor.tsx
  protocol-designer/src/ProtocolRoutes.tsx
  protocol-designer/src/assets/localization/en/modal.json
  protocol-designer/src/organisms/AnnouncementModal/AnnouncementModal.module.css
  protocol-designer/src/organisms/AnnouncementModal/__tests__/AnnouncementModal.test.tsx
  protocol-designer/src/organisms/AnnouncementModal/announcements.tsx
  protocol-designer/src/organisms/AnnouncementModal/index.tsx
  protocol-designer/src/organisms/index.ts
Labels: authorship

#16234 refactor(protocol-designer): change trash bin snackbar required rendering
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
  protocol-designer/src/pages/Designer/__tests__/Designer.test.tsx
  protocol-designer/src/pages/Designer/index.tsx
Labels: authorship

#16218 feat(components, protocol-designer): labware render for assigning liquids in pd
  components/src/hardware-sim/Labware/LabwareRender.tsx
  components/src/hardware-sim/Labware/labwareInternals/FilledWells.tsx
  components/src/hardware-sim/Labware/labwareInternals/StaticLabware.tsx
  components/src/hardware-sim/Labware/labwareInternals/StyledWells.tsx
  protocol-designer/src/assets/localization/en/liquids.json
  protocol-designer/src/assets/localization/en/well_selection.json
  protocol-designer/src/components/LiquidPlacementModal.tsx
  protocol-designer/src/components/StepEditForm/fields/WellSelectionField/WellSelectionModal.tsx
  protocol-designer/src/components/WellSelectionInstructions.tsx
  protocol-designer/src/components/labware/SelectableLabware.tsx
  protocol-designer/src/organisms/AssignLiquidsModal/index.tsx
Labels: authorship

#16237 refactor(protocol-designer): nav routing and hover touchups
  components/src/atoms/ListItem/ListItemChildren/ListItemCustomize.tsx
  protocol-designer/src/NavigationBar.tsx
  protocol-designer/src/__tests__/NavigationBar.test.tsx
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/atoms/constants.ts
  protocol-designer/src/atoms/index.ts
  protocol-designer/src/organisms/PipetteInfoItem/index.tsx
  protocol-designer/src/organisms/SlotInformation/index.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/WizardBody.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/CreateNewProtocol.test.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
  protocol-designer/src/pages/Landing/__tests__/Landing.test.tsx
  protocol-designer/src/pages/Landing/index.tsx
  protocol-designer/src/pages/ProtocolOverview/DeckThumbnail.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#16238 refactor(components): make LiquidIcon an optional btn
  components/src/molecules/LiquidIcon/LiquidIcon.stories.tsx
  components/src/molecules/LiquidIcon/index.tsx
  protocol-designer/src/organisms/DefineLiquidsModal/index.tsx
Labels: authorship

#16291 fix(protocol-designer): update Add/Edit liquids button
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SlotOverflowMenu.test.tsx
Labels: authorship

#16301 docs(api): remaining updates to Versioning page for 2.20
  api/docs/v2/versioning.rst
Labels: docs, papi-v2

#16290 docs(api): partial pickup static workaround
  api/docs/v2/pipettes/partial_tip_pickup.rst
  api/release-notes.md
Labels: docs, papi-v2

#16308 fix(protocol-designer): remove margins from protocol overview
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#16303 fix(protocol-designer): remove margins from onboarding screens
  protocol-designer/src/assets/localization/en/create_new_protocol.json
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/pages/CreateNewProtocolWizard/AddMetadata.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectFixtures.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectGripper.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectRobot.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/WizardBody.tsx
  protocol-designer/src/pages/Landing/__tests__/Landing.test.tsx
  protocol-designer/src/pages/Landing/index.tsx
Labels: authorship

#16323 fix(protocol-designer): fix the slot information cutoff issue
  protocol-designer/src/organisms/SlotInformation/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
Labels: authorship

#16331 fix(components): add AltPrimaryButton for PD
  components/src/atoms/buttons/AltPrimaryButton.tsx
  components/src/atoms/buttons/__tests__/AltPrimaryButton.test.tsx
  components/src/atoms/buttons/buttons.stories.tsx
Labels: authorship

#16328 feat(protocol-designer, components): wire up pause form in PD redesign
  components/src/atoms/MenuList/MenuItem.tsx
  components/src/atoms/buttons/RadioButton.tsx
  components/src/molecules/DropdownMenu/index.tsx
  protocol-designer/src/assets/localization/en/application.json
  protocol-designer/src/form-types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/PauseTools/index.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/fieldLevel/errors.ts
  protocol-designer/src/steplist/fieldLevel/index.ts
  protocol-designer/src/steplist/fieldLevel/processing.ts
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdatePause.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/pauseFormToArgs.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/test/pauseFormToArgs.test.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/steplist/utils/getTimeFromPauseForm.ts
Labels: authorship

#16342 feat(protocol-designer): heater-shaker step form tools
  components/src/atoms/Checkbox/index.tsx
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/atoms/Toggle/index.tsx
  protocol-designer/src/atoms/index.ts
  protocol-designer/src/molecules/CheckboxExpandStepFormField/index.tsx
  protocol-designer/src/molecules/InputStepFormField/index.tsx
  protocol-designer/src/molecules/ToggleExpandStepFormField/index.tsx
  protocol-designer/src/molecules/ToggleStepFormField/index.tsx
  protocol-designer/src/molecules/index.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/HeaterShakerTools/index.tsx
  protocol-designer/src/ui/modules/utils.ts
Labels: authorship

#16340 feat(protocol-designer): temperature step form tools
  components/src/atoms/buttons/RadioButton.tsx
  protocol-designer/src/assets/localization/en/tooltip.json
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/TemperatureTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/__tests__/TemperatureTools.test.tsx
Labels: authorship

#16335 feat(protocol-designer): update icons for steps
  components/src/icons/icon-data.ts
  protocol-designer/src/form-types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/TerminalItemStep.tsx
Labels: authorship

#16344 feat(protocol-designer): add the release notes button to settings
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/organisms/AnnouncementModal/index.tsx
  protocol-designer/src/pages/Settings/__tests__/Settings.test.tsx
  protocol-designer/src/pages/Settings/index.tsx
Labels: authorship

#16304 docs(api): hide API reference entries for post-2.20 features
  api/src/opentrons/protocol_api/labware.py
  api/src/opentrons/protocol_api/protocol_context.py
Labels: docs, papi-v2

#16361 fix(protocol-designer): fix text display condition in select modules and select fixtures
  protocol-designer/src/assets/localization/en/create_new_protocol.json
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectFixtures.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
Labels: authorship

#16363 fix(protocol-designer): fix pipette selection issue
  protocol-designer/src/assets/localization/en/create_new_protocol.json
  protocol-designer/src/organisms/EditInstrumentsModal/index.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
Labels: authorship

#16374 fix(components): align EmptySelectorButton with the latest design
  components/src/atoms/buttons/EmptySelectorButton.stories.tsx
  components/src/atoms/buttons/EmptySelectorButton.tsx
  components/src/atoms/buttons/__tests__/EmptySelectorButton.test.tsx
  protocol-designer/src/organisms/EditInstrumentsModal/index.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectFixtures.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
  protocol-designer/src/pages/Designer/Offdeck/OffDeckDetails.tsx
Labels: authorship

#16372 fix(protocol-ddesigner): fix select modules unexpected behavior
  protocol-designer/src/assets/localization/en/create_new_protocol.json
  protocol-designer/src/organisms/EditInstrumentsModal/index.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/WizardBody.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
  protocol-designer/src/pages/Landing/index.tsx
Labels: authorship
