Repository Opentrons/opentrons, pull requests merged in 2024-05, with the labels that each got.

#15017 fix(app): fix restore default values button behavior
  app/src/organisms/ChildNavigation/index.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/ProtocolSetupParameters.test.tsx
  app/src/organisms/ProtocolSetupParameters/index.tsx
Labels: authorship

#15036 fix(app): fix remove Parameters header if a protocl is non-RTP
  app/src/atoms/MenuList/DropdownMenu.tsx
  app/src/organisms/Devices/ProtocolRun/ProtocolRunRunTimeParameters.tsx
  app/src/organisms/Devices/ProtocolRun/__tests__/ProtocolRunRuntimeParameters.test.tsx
  app/src/organisms/ProtocolDetails/ProtocolLiquidsDetails.tsx
Labels: authorship

#15037 fix(app): fix RoundTabs grid-gap in protocl details
  app/src/organisms/ProtocolDetails/index.tsx
Labels: authorship

#15039 fix(app): remove unnecessary padding-top
  app/src/pages/ProtocolDashboard/index.tsx
Labels: authorship

#15057 feat(protocol-designer): custom blowout flowRates
  protocol-designer/cypress/integration/migrations.spec.js
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/mix_8_0_0.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/components/StepEditForm/fields/FlowRateField/FlowRateInput.tsx
  protocol-designer/src/components/StepEditForm/fields/FlowRateField/__tests__/FlowRateField.test.tsx
  protocol-designer/src/components/StepEditForm/fields/FlowRateField/index.tsx
  protocol-designer/src/components/StepEditForm/forms/MixForm.tsx
  protocol-designer/src/components/StepEditForm/forms/MoveLiquidForm/SourceDestFields.tsx
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_1_0.ts
  protocol-designer/src/load-file/migration/__tests__/__snapshots__/3_0_0.test.ts.snap
  protocol-designer/src/load-file/migration/utils/getDefaultBlowoutFlowRate.ts
  protocol-designer/src/localization/en/tooltip.json
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/steplist/test/__snapshots__/mergeSubstepsFns.test.ts.snap
  protocol-designer/src/ui/steps/test/selectors.test.ts
  step-generation/src/commandCreators/compound/mix.ts
Labels: authorship

#15061 feat(protocol-designer): remove MoaM feature flag
  protocol-designer/src/components/EditModules.tsx
  protocol-designer/src/components/__tests__/EditModules.test.tsx
  protocol-designer/src/components/modals/CreateFileWizard/ModulesAndOtherTile.tsx
  protocol-designer/src/components/modals/CreateFileWizard/__tests__/ModulesAndOtherTile.test.tsx
  protocol-designer/src/feature-flags/reducers.ts
  protocol-designer/src/feature-flags/selectors.ts
  protocol-designer/src/feature-flags/types.ts
  protocol-designer/src/localization/en/feature_flags.json
Labels: authorship

#15060 feat(protocol-designer): default dispense height is 1mm from the bottom
  protocol-designer/cypress/integration/migrations.spec.js
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/mix_8_0_0.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/components/modals/FileUploadMessageModal/modalContents.tsx
  protocol-designer/src/constants.ts
  protocol-designer/src/localization/en/modal.json
Labels: authorship

#15042 fix(app): fix the arrow icon size in dropdown menu
  app/src/atoms/MenuList/DropdownMenu.tsx
  components/src/icons/icon-data.ts
Labels: authorship

#15064 fix(protocol-designer): color picker chooses new color for defaults
  protocol-designer/src/components/ColorPicker/index.tsx
  protocol-designer/src/components/LiquidsPage/LiquidEditForm.tsx
  protocol-designer/src/components/LiquidsPage/index.tsx
Labels: authorship

#15070 fix(protocol-designer): clean up trash modal and new labware dropdown logic
  protocol-designer/src/components/LabwareSelectionModal/LabwareSelectionModal.tsx
  protocol-designer/src/components/LabwareSelectionModal/__tests__/LabwareSelectionModal.test.tsx
  protocol-designer/src/components/StepEditForm/fields/LabwareLocationField/index.tsx
  protocol-designer/src/components/modals/FilePipettesModal/index.tsx
  protocol-designer/src/components/modules/TrashModal.tsx
  protocol-designer/src/localization/en/modules.json
Labels: authorship

#15067 fix(app): remove unnecessary padding
  app/src/pages/ProtocolDetails/Parameters.tsx
  app/src/pages/ProtocolDetails/index.tsx
Labels: authorship

#15040 fix(app): remove input field box-shadow on ODD
  app/src/atoms/InputField/index.tsx
Labels: authorship

#15087 fix(step-generation): account for adapter in 4th column slot timeline error
  protocol-designer/src/load-file/migration/8_1_0.ts
  protocol-designer/src/load-file/migration/utils/getDefaultBlowoutFlowRate.ts
  protocol-designer/src/step-forms/reducers/index.ts
  step-generation/src/commandCreators/atomic/aspirate.ts
  step-generation/src/commandCreators/atomic/blowout.ts
  step-generation/src/commandCreators/atomic/dispense.ts
  step-generation/src/commandCreators/atomic/moveToWell.ts
  step-generation/src/commandCreators/atomic/replaceTip.ts
  step-generation/src/robotStateSelectors.ts
Labels: authorship

#15029 feat(opentrons-ai-client): add jotai and custom hook for call api
  opentrons-ai-client/Makefile
  opentrons-ai-client/index.html
  opentrons-ai-client/package.json
  opentrons-ai-client/src/assets/images/favicon/android-chrome-192x192.png
  opentrons-ai-client/src/assets/images/favicon/android-chrome-512x512.png
  opentrons-ai-client/src/assets/images/favicon/apple-touch-icon.png
  opentrons-ai-client/src/assets/images/favicon/favicon-16x16.png
  opentrons-ai-client/src/assets/images/favicon/favicon-32x32.png
  opentrons-ai-client/src/assets/images/favicon/favicon.ico
  opentrons-ai-client/src/assets/images/favicon/site.webmanifest
  opentrons-ai-client/src/atoms/SendButton/__tests__/SendButton.test.tsx
  opentrons-ai-client/src/atoms/SendButton/index.tsx
  opentrons-ai-client/src/main.tsx
  opentrons-ai-client/src/molecules/ChatDisplay/ChatDisplay.stories.tsx
  opentrons-ai-client/src/molecules/ChatDisplay/__tests__/ChatDisplay.test.tsx
  opentrons-ai-client/src/molecules/ChatDisplay/index.tsx
  opentrons-ai-client/src/molecules/InputPrompt/index.tsx
  opentrons-ai-client/src/organisms/ChatContainer/index.tsx
  opentrons-ai-client/src/organisms/PromptButton/PromptProvider.tsx
  opentrons-ai-client/src/organisms/PromptButton/__tests__/PromptButton.test.tsx
  opentrons-ai-client/src/organisms/PromptButton/__tests__/PromptProvider.test.tsx
  opentrons-ai-client/src/organisms/PromptButton/index.tsx
  opentrons-ai-client/src/resources/atoms.ts
  opentrons-ai-client/src/resources/types.ts
  package.json
  yarn.lock
Labels: authorship

#15085 fix(app): modify the space between icon and banner outline
  app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx
  app/src/organisms/Devices/ReachableBanner.tsx
  app/src/organisms/UpdateRobotBanner/index.tsx
Labels: authorship

#15054 fix(app): disable module calibration if heating or cooling
  app/src/assets/localization/en/module_wizard_flows.json
  app/src/organisms/ModuleCard/ModuleOverflowMenu.tsx
  app/src/organisms/ModuleCard/__tests__/ModuleOverflowMenu.test.tsx
Labels: authorship

#15035 fix(app): fix input field behavior on blur
  app/src/atoms/InputField/index.tsx
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ChooseRobotSlideout/index.tsx
Labels: authorship

#15071 fix(app): fix tooltip behavior for disabled Restore default value on RTP slideout
  app/src/organisms/ChooseProtocolSlideout/__tests__/ChooseProtocolSlideout.test.tsx
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ChooseRobotSlideout/__tests__/ChooseRobotSlideout.test.tsx
  app/src/organisms/ChooseRobotSlideout/index.tsx
Labels: authorship

#15088 fix(app): fix list button styling
  app/src/organisms/ProtocolSetupParameters/index.tsx
  app/src/pages/ProtocolSetup/index.tsx
Labels: authorship

#15079 fix(app): update specific analysis keys passed through CommandText with terminal run record
  app/src/organisms/RunPreview/index.tsx
Labels: authorship

#15078 docs(api): describe new `drop_tip()` behavior introduced in PAPI 2.18
  api/src/opentrons/protocol_api/instrument_context.py
Labels: docs, papi-v2

#15095 fix(app): fix space in mini card
  app/src/organisms/ChooseProtocolSlideout/index.tsx
Labels: authorship

#15098 fix(opentrons-ai-client): fix components build issue
  opentrons-ai-client/src/organisms/PromptButton/PromptButton.stories.tsx
Labels: authorship

#15096 refactor(protocol-designer, step-generation): multi tiprack uses defURI instead of id
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/mix_8_0_0.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/components/StepEditForm/fields/TiprackField.tsx
  protocol-designer/src/components/StepEditForm/fields/__tests__/TiprackField.test.tsx
  protocol-designer/src/load-file/migration/8_1_0.ts
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/step-forms/utils/createPresavedStepForm.ts
  protocol-designer/src/steplist/test/generateSubsteps.test.ts
  protocol-designer/src/timelineMiddleware/__tests__/generateRobotStateTimeline.test.ts
  protocol-designer/src/ui/labware/selectors.ts
  step-generation/src/__tests__/consolidate.test.ts
  step-generation/src/__tests__/distribute.test.ts
  step-generation/src/__tests__/getIsSafePipetteMovement.test.ts
  step-generation/src/__tests__/mix.test.ts
  step-generation/src/__tests__/replaceTip.test.ts
  step-generation/src/__tests__/robotStateSelectors.test.ts
  step-generation/src/__tests__/transfer.test.ts
  step-generation/src/robotStateSelectors.ts
  step-generation/src/utils/safePipetteMovements.ts
Labels: authorship

#15100 fix(protocol-designer): default tiprack selection refreshing
  protocol-designer/src/components/modals/CreateFileWizard/PipetteTipsTile.tsx
  protocol-designer/src/components/modals/CreateFileWizard/__tests__/CreateFileWizard.test.tsx
  protocol-designer/src/components/modals/CreateFileWizard/__tests__/PipetteTipsTile.test.tsx
  protocol-designer/src/components/modals/CreateFileWizard/index.tsx
Labels: authorship

#15101 fix(app, react-api-client): handle failed analysis for RTP protocol on ODD
  app/src/organisms/ProtocolSetupParameters/AnalysisFailedModal.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/AnalysisFailedModal.test.tsx
  app/src/organisms/ProtocolSetupParameters/index.tsx
  app/src/pages/ProtocolDashboard/ProtocolCard.tsx
  app/src/pages/ProtocolDashboard/__tests__/ProtocolCard.test.tsx
  app/src/pages/ProtocolSetup/__tests__/ProtocolSetup.test.tsx
  app/src/pages/ProtocolSetup/index.tsx
  react-api-client/src/protocols/index.ts
  react-api-client/src/protocols/useMostRecentSuccessfulAnalysisAsDocumentQuery.ts
Labels: authorship

#15099 fix(app): fix choose number input field behavior
  app/src/organisms/ProtocolSetupParameters/ChooseNumber.tsx
Labels: authorship

#15107 feat(opentrons-ai-client): add primary floating button
  opentrons-ai-client/src/molecules/PrimaryFloatingButton/PrimaryFloatingButton.stories.tsx
  opentrons-ai-client/src/molecules/PrimaryFloatingButton/__tests__/PrimaryFloatingButton.test.tsx
  opentrons-ai-client/src/molecules/PrimaryFloatingButton/index.tsx
Labels: authorship

#15116 fix(protocol-designer): misc bugs with copy, ui, and liquid color error
  protocol-designer/src/components/LiquidsPage/LiquidEditForm.tsx
  protocol-designer/src/components/modals/AnnouncementModal/announcements.tsx
  protocol-designer/src/components/modals/CreateFileWizard/EquipmentOption.tsx
  protocol-designer/src/components/modals/CreateFileWizard/PipetteTipsTile.tsx
  protocol-designer/src/components/modals/CreateFileWizard/__tests__/EquipmentOption.test.tsx
  protocol-designer/src/components/modules/ModuleDiagram.tsx
  protocol-designer/src/images/modules/thermocycler.jpg
  protocol-designer/src/images/modules/thermocycler.png
  protocol-designer/src/localization/en/tooltip.json
  protocol-designer/src/steplist/formLevel/warnings.tsx
Labels: authorship

#15120 fix(app): ensure terminal run preview shows detail for load liquid commands
  api-client/src/runs/types.ts
  app/src/organisms/InterventionModal/__fixtures__/index.ts
  app/src/organisms/RunPreview/index.tsx
  app/src/organisms/RunTimeControl/__fixtures__/index.ts
  react-api-client/src/runs/__fixtures__/runs.ts
Labels: authorship

#15086 RDEVOPS-84 Opetrons AI Server foundation
  .eslintignore
  .github/workflows/ai-server-lint-test.yaml
  opentrons-ai-server/.gitignore
  opentrons-ai-server/Makefile
  opentrons-ai-server/Pipfile
  opentrons-ai-server/Pipfile.lock
  opentrons-ai-server/README.md
  opentrons-ai-server/api/__init__.py
  opentrons-ai-server/api/domain/__init__.py
  opentrons-ai-server/api/domain/todo.py
  opentrons-ai-server/api/handler/__init__.py
  opentrons-ai-server/api/handler/function.py
  opentrons-ai-server/api/integration/__init__.py
  opentrons-ai-server/api/integration/jsonplaceholder.py
  opentrons-ai-server/api/models/internal_server_error.py
  opentrons-ai-server/api/models/todo.py
  opentrons-ai-server/api/settings.py
  opentrons-ai-server/aws_actions.py
  opentrons-ai-server/mypy.ini
  opentrons-ai-server/pyproject.toml
  opentrons-ai-server/pytest.ini
  opentrons-ai-server/test_events/health.json
  opentrons-ai-server/tests/__init__.py
  opentrons-ai-server/tests/test_todos.py
Labels: authorship

#15128 refactor(protocol-designer): new module images and optimize all modul…
  protocol-designer/src/images/modules/heater_shaker_module_transparent.png
  protocol-designer/src/images/modules/heatershaker.png
  protocol-designer/src/images/modules/mag_block.png
  protocol-designer/src/images/modules/magdeck_gen1.png
  protocol-designer/src/images/modules/magdeck_gen2.png
  protocol-designer/src/images/modules/magdeck_tempdeck_combined.png
  protocol-designer/src/images/modules/module_pipette_collision_warning.png
  protocol-designer/src/images/modules/temp_deck_gen_2_transparent.png
  protocol-designer/src/images/modules/tempdeck_gen1.png
  protocol-designer/src/images/modules/tempdeck_gen2.png
  protocol-designer/src/images/modules/thermocycler.png
  protocol-designer/src/images/modules/thermocycler_gen2.png
Labels: authorship

#15129 fix(protocol-designer): fix dropdown icon to match legacy icon
  components/src/forms/DropdownField.tsx
  components/src/icons/icon-data.ts
Labels: authorship

#15125 refactor(app, api-client, react-api-client): unify analysis and run record for CommandText use
  api-client/src/runs/types.ts
  app/src/organisms/CommandText/LoadCommandText.tsx
  app/src/organisms/CommandText/MoveLabwareCommandText.tsx
  app/src/organisms/CommandText/PipettingCommandText.tsx
  app/src/organisms/CommandText/__fixtures__/index.ts
  app/src/organisms/CommandText/__tests__/CommandText.test.tsx
  app/src/organisms/CommandText/index.tsx
  app/src/organisms/CommandText/types.ts
  app/src/organisms/CommandText/utils/accessors.ts
  app/src/organisms/CommandText/utils/getAddressableAreaDisplayName.ts
  app/src/organisms/CommandText/utils/getCommandTextData.ts
  app/src/organisms/CommandText/utils/getLabwareDisplayLocation.ts
  app/src/organisms/CommandText/utils/getLabwareName.ts
  app/src/organisms/CommandText/utils/getLiquidDisplayName.ts
  app/src/organisms/CommandText/utils/getModuleDisplayLocation.ts
  app/src/organisms/CommandText/utils/getModuleModel.ts
  app/src/organisms/CommandText/utils/getPipetteNameOnMount.ts
  app/src/organisms/InterventionModal/__fixtures__/index.ts
  app/src/organisms/OnDeviceDisplay/RunningProtocol/CurrentRunningProtocolCommand.tsx
  app/src/organisms/OnDeviceDisplay/RunningProtocol/RunningProtocolCommandList.tsx
  app/src/organisms/RunPreview/index.tsx
  app/src/organisms/RunProgressMeter/index.tsx
  app/src/organisms/RunTimeControl/__fixtures__/index.ts
  react-api-client/src/runs/__fixtures__/runs.ts
Labels: authorship

#15131 fix(step-generation): timeline error if multiple entities in same slotName
  protocol-designer/src/localization/en/alert.json
  step-generation/src/__tests__/moveLabware.test.ts
  step-generation/src/commandCreators/atomic/moveLabware.ts
  step-generation/src/errorCreators.ts
  step-generation/src/types.ts
Labels: authorship

#15133 feat(protocol-designer): add flowRate and zHeight fields to multiDispense
  protocol-designer/src/components/StepEditForm/fields/DisposalVolumeField.tsx
  protocol-designer/src/localization/en/application.json
Labels: authorship

#15091 fix(app): Fix dropdown menu open direction issue
  app/src/atoms/MenuList/DropdownMenu.tsx
Labels: authorship

#15144 fix(step-generation): h-S collision warning for Flex protocols
  shared-data/js/helpers/__tests__/getAreFlexSlotsAdjacent.test.ts
  shared-data/js/helpers/getAreFlexSlotsAdjacent.ts
  shared-data/js/helpers/getFlexSurroundingSlots.ts
  shared-data/js/helpers/index.ts
  step-generation/src/__tests__/aspirate.test.ts
  step-generation/src/__tests__/dispense.test.ts
  step-generation/src/__tests__/moveToWell.test.ts
  step-generation/src/__tests__/utils.test.ts
  step-generation/src/commandCreators/atomic/aspirate.ts
  step-generation/src/commandCreators/atomic/dispense.ts
  step-generation/src/commandCreators/atomic/moveToWell.ts
  step-generation/src/commandCreators/atomic/replaceTip.ts
  step-generation/src/utils/heaterShakerCollision.ts
Labels: authorship

#15141 refactor(protocol-designer): tiprack option redesign to not have scroll
  components/src/forms/Select.tsx
  protocol-designer/src/components/modals/FilePipettesModal/TiprackOption.tsx
  protocol-designer/src/components/modals/FilePipettesModal/TiprackSelect.tsx
  protocol-designer/src/components/modals/FilePipettesModal/__tests__/TiprackOptions.test.tsx
Labels: authorship

#15114 fix(app): update InputField styling
  app/src/atoms/InputField/index.tsx
Labels: authorship

#15151 fix(app): fix font size in lpc table
  app/src/organisms/LabwarePositionCheck/ResultsSummary.tsx
Labels: authorship

#15145 fix(app): fix password button rendering issue and update input field component
  app/src/atoms/InputField/__tests__/InputField.test.tsx
  app/src/atoms/InputField/index.tsx
  app/src/organisms/NetworkSettings/SetWifiCred.tsx
  app/src/organisms/NetworkSettings/__tests__/SetWifiCred.test.tsx
Labels: authorship

#15126 feat(opentrons-ai-client): add code copy button
  opentrons-ai-client/src/assets/localization/en/protocol_generator.json
  opentrons-ai-client/src/molecules/ChatDisplay/index.tsx
  opentrons-ai-client/src/molecules/PrimaryFloatingButton/index.tsx
  opentrons-ai-client/src/organisms/ChatContainer/index.tsx
  package.json
Labels: authorship

#15156 docs(api): add missing equals sign in tutorial code snippets
  api/docs/v2/tutorial.rst
Labels: docs, papi-v2

#15155 fix(protocol-designer, step-generation): labware only removed if prev…
  protocol-designer/src/components/StepEditForm/fields/LabwareLocationField/index.tsx
  protocol-designer/src/localization/en/alert.json
  protocol-designer/src/ui/labware/selectors.ts
  step-generation/src/__tests__/moveLabware.test.ts
  step-generation/src/commandCreators/atomic/moveLabware.ts
  step-generation/src/errorCreators.ts
  step-generation/src/types.ts
Labels: authorship

#15159 refactor(protocol-designer): logic for when slots are occupied for staging areas
  protocol-designer/src/components/modals/CreateFileWizard/StagingAreaTile.tsx
  protocol-designer/src/components/modals/CreateFileWizard/__tests__/utils.test.tsx
  protocol-designer/src/components/modals/CreateFileWizard/utils.ts
Labels: authorship

#15169 OpenAI API available in the opentrons-ai-server
  opentrons-ai-server/.gitignore
  opentrons-ai-server/Makefile
  opentrons-ai-server/Pipfile
  opentrons-ai-server/Pipfile.lock
  opentrons-ai-server/README.md
  opentrons-ai-server/api/domain/openai_predict.py
  opentrons-ai-server/api/domain/prompts.py
  opentrons-ai-server/api/domain/todo.py
  opentrons-ai-server/api/handler/function.py
  opentrons-ai-server/api/integration/aws_secrets_manager.py
  opentrons-ai-server/api/integration/jsonplaceholder.py
  opentrons-ai-server/api/models/__init__.py
  opentrons-ai-server/api/models/chat_request.py
  opentrons-ai-server/api/models/chat_response.py
  opentrons-ai-server/api/models/empty_request_error.py
  opentrons-ai-server/api/models/internal_server_error.py
  opentrons-ai-server/api/models/todo.py
  opentrons-ai-server/api/settings.py
  opentrons-ai-server/deploy.py
  opentrons-ai-server/pytest.ini
  opentrons-ai-server/test_events/health.json
  opentrons-ai-server/tests/conftest.py
  opentrons-ai-server/tests/helpers/__init__.py
  opentrons-ai-server/tests/helpers/client.py
  opentrons-ai-server/tests/helpers/settings.py
  opentrons-ai-server/tests/helpers/token.py
  opentrons-ai-server/tests/helpers/token_verifier.py
  opentrons-ai-server/tests/test_chat_models.py
  opentrons-ai-server/tests/test_live.py
  opentrons-ai-server/tests/test_todos.py
Labels: authorship

#14677 docs(api): runtime parameters in Python API 2.18
  api/docs/v2/conf.py
  api/docs/v2/index.rst
  api/docs/v2/new_labware.rst
  api/docs/v2/new_protocol_api.rst
  api/docs/v2/parameters/choosing.rst
  api/docs/v2/parameters/defining.rst
  api/docs/v2/parameters/style.rst
  api/docs/v2/parameters/use_case_dry_run.rst
  api/docs/v2/parameters/use_case_sample_count.rst
  api/docs/v2/parameters/using_values.rst
  api/docs/v2/runtime_parameters.rst
  api/src/opentrons/protocol_api/protocol_context.py
Labels: docs, papi-v2

#15173 fix(opentrons-ai-client): fix the vertical position of caret
  opentrons-ai-client/README.md
  opentrons-ai-client/src/main.tsx
  opentrons-ai-client/src/molecules/InputPrompt/index.tsx
Labels: authorship

#15172 fix(app): adjust applied labware offset data table
  app/src/organisms/Devices/HistoricalProtocolRunOffsetDrawer.tsx
Labels: authorship

#15185 chore: add known issue for Windows USB labware offset data
  app-shell/build/release-notes.md
Labels: chore, docs

#15183 docs(api): Versioning page updates for Python API 2.18
  api/docs/v2/versioning.rst
Labels: docs, papi-v2

#15182 fix(opentrons-ai-client): fix ChatContainer layout issue
  opentrons-ai-client/README.md
  opentrons-ai-client/src/organisms/ChatContainer/index.tsx
Labels: authorship

#15148 feat(opentrons-ai-client): add auth0 package
  opentrons-ai-client/package.json
  opentrons-ai-client/src/App.test.tsx
  opentrons-ai-client/src/App.tsx
  opentrons-ai-client/src/assets/localization/en/protocol_generator.json
  opentrons-ai-client/src/main.tsx
  opentrons-ai-client/src/molecules/ChatDisplay/__tests__/ChatDisplay.test.tsx
  opentrons-ai-client/src/molecules/ChatDisplay/index.tsx
  opentrons-ai-client/src/molecules/InputPrompt/index.tsx
  opentrons-ai-client/src/molecules/Loading/index.tsx
  opentrons-ai-client/src/resources/types.ts
  package.json
  yarn.lock
Labels: authorship

#15184 feat(ai-server): switch to custom runtime
  opentrons-ai-server/Dockerfile
  opentrons-ai-server/Makefile
  opentrons-ai-server/Pipfile
  opentrons-ai-server/Pipfile.lock
  opentrons-ai-server/README.md
  opentrons-ai-server/api/handler/function.py
  opentrons-ai-server/deploy.py
  opentrons-ai-server/tests/conftest.py
  opentrons-ai-server/tests/helpers/client.py
  opentrons-ai-server/tests/helpers/settings.py
  opentrons-ai-server/tests/test_live.py
Labels: authorship

#15199 fix(opentrons-ai-client): fix copy code button visibility
  opentrons-ai-client/src/molecules/ChatDisplay/index.tsx
Labels: authorship

#15221 fix(protocol-designer): disabled color logic and pause step item ui
  protocol-designer/src/components/LiquidsPage/LiquidEditForm.tsx
  protocol-designer/src/components/steplist/PauseStepItems.tsx
Labels: authorship

#15219 fix(protocol-designer): enable arrow when reaching max slots
  protocol-designer/src/components/modals/CreateFileWizard/EquipmentOption.tsx
  protocol-designer/src/components/modals/CreateFileWizard/ModulesAndOtherTile.tsx
Labels: authorship

#15214 fix(opentrons-ai-client): fix layout issues
  opentrons-ai-client/src/App.tsx
  opentrons-ai-client/src/molecules/ChatDisplay/index.tsx
  opentrons-ai-client/src/molecules/ChatFooter/__tests__/ChatFooter.test.tsx
  opentrons-ai-client/src/molecules/ChatFooter/index.tsx
  opentrons-ai-client/src/molecules/SidePanel/index.tsx
  opentrons-ai-client/src/organisms/ChatContainer/__tests__/ChatContainer.test.tsx
  opentrons-ai-client/src/organisms/ChatContainer/index.tsx
Labels: authorship

#15224 fix(protocol-designer): default to correct tiprack uri
  protocol-designer/src/components/StepEditForm/fields/TiprackField.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/step-forms/utils/createPresavedStepForm.ts
Labels: authorship

#15220 fix(opentrons-ai-client): update prompt guide and examples
  opentrons-ai-client/src/assets/localization/en/protocol_generator.json
  opentrons-ai-client/src/assets/prompts/prompt-data.ts
  opentrons-ai-client/src/molecules/PromptGuide/__tests__/PromptGuide.test.tsx
  opentrons-ai-client/src/molecules/PromptGuide/index.tsx
Labels: authorship

#15218 fix(protocol-designer): do not duplicate into adjacent h-s slot for o…
  protocol-designer/src/components/modals/CreateFileWizard/index.tsx
  protocol-designer/src/labware-ingred/actions/thunks.ts
  protocol-designer/src/labware-ingred/utils.ts
Labels: authorship

#15225 feat(protocol-designer): y position tooltip and migration copy
  protocol-designer/cypress/e2e/migrations.cy.js
  protocol-designer/src/components/StepEditForm/fields/TipPositionField/TipPositionModal.tsx
  protocol-designer/src/components/StepEditForm/forms/MoveLiquidForm/SourceDestFields.tsx
  protocol-designer/src/localization/en/modal.json
  protocol-designer/src/localization/en/tooltip.json
Labels: authorship

#15230 fix(protocol-designer): submit and don't show again fixes
  protocol-designer/src/components/FilePage.tsx
  protocol-designer/src/components/Hints/index.tsx
Labels: authorship

#15244 refactor(protocol-designer): dismissed warning now dismisses for duration of protocol
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/mix_8_0_0.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/components/alerts/Alerts.tsx
  protocol-designer/src/dismiss/__tests__/reducers.test.ts
  protocol-designer/src/dismiss/actions.ts
  protocol-designer/src/dismiss/reducers.ts
  protocol-designer/src/dismiss/selectors.ts
  protocol-designer/src/file-data/__fixtures__/createFile/commonFields.ts
  protocol-designer/src/load-file/migration/8_1_0.ts
  protocol-designer/src/load-file/migration/utils/getLoadLiquidCommands.ts
  protocol-designer/src/top-selectors/timelineWarnings/index.ts
Labels: authorship

#15248 fix(protocol-designer): missing labware modal logic
  protocol-designer/src/ui/modules/selectors.ts
  protocol-designer/src/ui/steps/actions/__tests__/addAndSelectStepWithHints.test.ts
  protocol-designer/src/ui/steps/actions/thunks/index.ts
Labels: authorship

#15258 fix(protocol-designer): candidate-C bug addressing and don't unnecess…
  protocol-designer/src/components/FilePage.tsx
  protocol-designer/src/components/FileSidebar/utils/getUnusedTrash.ts
  protocol-designer/src/components/modals/CreateFileWizard/index.tsx
  protocol-designer/src/load-file/migration/index.ts
  protocol-designer/src/step-forms/reducers/index.ts
Labels: authorship

#15260 fix(protocol-designer): well order input field cta logic refinement
  protocol-designer/src/components/StepEditForm/fields/WellOrderField/WellOrderModal.tsx
Labels: authorship

#15271 test(robot-server): Fix datetime regexes
  robot-server/tests/integration/http_api/protocols/test_deck_coordinate_load.tavern.yaml
  robot-server/tests/integration/http_api/protocols/test_key.tavern.yaml
  robot-server/tests/integration/http_api/protocols/test_upload.tavern.yaml
  robot-server/tests/integration/http_api/protocols/test_upload_flex_protocol.yaml
  robot-server/tests/integration/http_api/protocols/test_v6_json_upload.tavern.yaml
  robot-server/tests/integration/http_api/protocols/test_v8_json_upload_flex.tavern.yaml
  robot-server/tests/integration/http_api/protocols/test_v8_json_upload_ot2.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_json_v6_protocol_run.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_json_v6_run_failure.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_json_v7_protocol_run.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_papi_v2_run_failure.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_play_stop_papi.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_play_stop_v6.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_protocol_run.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_run_queued_protocol_commands.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_run_with_run_time_parameters.tavern.yaml
  robot-server/tests/integration/http_api/runs/test_runs_pagination.tavern.yaml
  robot-server/tests/integration/http_api/test_command_key_hash_matching.tavern.yaml
  robot-server/tests/integration/http_api/test_deck_configuration.tavern.yaml
  robot-server/tests/integration/sessions/test_calibration_check.tavern.yaml
  robot-server/tests/integration/sessions/test_deck_calibration.tavern.yaml
  robot-server/tests/integration/sessions/test_session.tavern.yaml
  robot-server/tests/integration/sessions/test_tip_length_calibration.tavern.yaml
  robot-server/tests/integration/system/test_system_time.tavern.yaml
Labels: robot server

#15286 fix(protocol-designer): set numMultiples to numItems instead of 0
  protocol-designer/src/components/modals/CreateFileWizard/EquipmentOption.tsx
Labels: authorship

#15273 fix(opentrons-ai-client): fix textboxarea position issue
  opentrons-ai-client/src/molecules/ChatFooter/index.tsx
  opentrons-ai-client/src/organisms/ChatContainer/index.tsx
Labels: authorship

#15193 refactor(opentrons-ai-client): refactoring api call and inputprompt component
  opentrons-ai-client/Makefile
  opentrons-ai-client/package.json
  opentrons-ai-client/src/App.tsx
  opentrons-ai-client/src/main.tsx
  opentrons-ai-client/src/molecules/ChatDisplay/index.tsx
  opentrons-ai-client/src/molecules/ChatFooter/index.tsx
  opentrons-ai-client/src/molecules/InputPrompt/index.tsx
  opentrons-ai-client/src/organisms/ChatContainer/index.tsx
  opentrons-ai-client/src/resources/constants.ts
  opentrons-ai-client/src/resources/hooks/__tests__/useApiCall.test.ts
  opentrons-ai-client/src/resources/hooks/__tests__/useGetAccessToken.test.ts
  opentrons-ai-client/src/resources/hooks/index.ts
  opentrons-ai-client/src/resources/hooks/useApiCall.ts
  opentrons-ai-client/src/resources/hooks/useGetAccessToken.ts
  opentrons-ai-client/src/resources/utils/__tests__/utils.test.ts
  opentrons-ai-client/src/resources/utils/utils.ts
  yarn.lock
Labels: authorship

#15288 feat(opentrons-ai-client): update payload type
  opentrons-ai-client/Makefile
  opentrons-ai-client/src/App.tsx
  opentrons-ai-client/src/assets/localization/en/protocol_generator.json
  opentrons-ai-client/src/molecules/InputPrompt/index.tsx
  opentrons-ai-client/src/resources/atoms.ts
  opentrons-ai-client/src/resources/types.ts
Labels: authorship

#15307 fix(opentrons-ai-client) fix textarea overlapping issue
  opentrons-ai-client/src/App.test.tsx
  opentrons-ai-client/src/App.tsx
  opentrons-ai-client/src/atoms/GlobalStyle/index.ts
  opentrons-ai-client/src/molecules/ChatFooter/index.tsx
  opentrons-ai-client/src/organisms/MainContentContainer/MainContainer.stories.tsx
  opentrons-ai-client/src/organisms/MainContentContainer/__tests__/MainContentContainer.test.tsx
  opentrons-ai-client/src/organisms/MainContentContainer/index.tsx
Labels: authorship
