Repository Opentrons/opentrons, pull requests merged in 2024-08, with the labels that each got.

#15874 refactor(protocol_designer): move Slideout from atoms to components
  protocol-designer/src/atoms/index.ts
  protocol-designer/src/components/OffDeckLabwareSlideout.tsx
  protocol-designer/src/components/Slideout/index.tsx
  protocol-designer/src/molecules/index.ts
  protocol-designer/src/organisms/index.ts
Labels: DO NOT MERGE, authorship

#15873 refactor(app): display file name from robot-server data
  app/src/organisms/ChooseRobotSlideout/FileCard.tsx
  app/src/organisms/ChooseRobotSlideout/__tests__/FileCard.test.tsx
  app/src/organisms/Devices/ProtocolRun/ProtocolRunRunTimeParameters.tsx
  app/src/organisms/Devices/ProtocolRun/__tests__/ProtocolRunRuntimeParameters.test.tsx
  shared-data/js/helpers/__tests__/formatRunTimeParameterValue.test.ts
  shared-data/js/helpers/formatRunTimeParameterValue.ts
  shared-data/js/types.ts
Labels: authorship

#15863 chore(app): remove enableCsvFile feature flag
  app/src/assets/localization/en/app_settings.json
  app/src/organisms/ChooseProtocolSlideout/__tests__/ChooseProtocolSlideout.test.tsx
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ChooseRobotSlideout/index.tsx
  app/src/organisms/ChooseRobotToRunProtocolSlideout/__tests__/ChooseRobotToRunProtocolSlideout.test.tsx
  app/src/organisms/ChooseRobotToRunProtocolSlideout/index.tsx
  app/src/organisms/Devices/HistoricalProtocolRun.tsx
  app/src/organisms/Devices/HistoricalProtocolRunDrawer.tsx
  app/src/organisms/Devices/ProtocolRun/__tests__/ProtocolRunRuntimeParameters.test.tsx
  app/src/organisms/Devices/RecentProtocolRuns.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/ProtocolSetupParameters.test.tsx
  app/src/organisms/ProtocolSetupParameters/index.tsx
  app/src/pages/ProtocolDashboard/PinnedProtocol.tsx
  app/src/pages/ProtocolDashboard/ProtocolCard.tsx
  app/src/pages/ProtocolDetails/__tests__/ProtocolDetails.test.tsx
  app/src/pages/ProtocolDetails/index.tsx
  app/src/redux/config/constants.ts
  app/src/redux/config/schema-types.ts
Labels: authorship

#15921 refactor(components, app): move RadioButton and add styling for helix
  app/src/atoms/buttons/index.ts
  app/src/molecules/InterventionModal/ModalContentOneColSimpleButtons.tsx
  app/src/molecules/InterventionModal/__tests__/ModalContentOneColSimpleButtons.test.tsx
  app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/IgnoreErrorSkipStep.tsx
  app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/SelectRecoveryOption.tsx
  app/src/organisms/NetworkSettings/SelectAuthenticationType.tsx
  app/src/organisms/ProtocolSetupParameters/ChooseCsvFile.tsx
  app/src/organisms/ProtocolSetupParameters/ChooseEnum.tsx
  app/src/organisms/QuickTransferFlow/SelectDestLabware.tsx
  app/src/organisms/QuickTransferFlow/SelectPipette.tsx
  app/src/organisms/QuickTransferFlow/SelectSourceLabware.tsx
  app/src/organisms/QuickTransferFlow/SelectTipRack.tsx
  app/src/organisms/QuickTransferFlow/TipManagement/ChangeTip.tsx
  app/src/organisms/QuickTransferFlow/TipManagement/TipDropLocation.tsx
  app/src/organisms/RobotSettingsDashboard/TouchScreenSleep.tsx
  app/src/organisms/WellSelection/Selection384Wells.tsx
  components/src/atoms/buttons/RadioButton.stories.tsx
  components/src/atoms/buttons/RadioButton.tsx
  components/src/atoms/buttons/__tests__/RadioButton.test.tsx
  components/src/atoms/buttons/index.ts
Labels: authorship

#15932 feat(protocol-designer): add public sans to protocol-designer
  protocol-designer/package.json
  protocol-designer/src/atoms/GlobalStyle/index.ts
  protocol-designer/src/index.tsx
Labels: authorship

#15929 refactor(components, app): move LargeButton to components and add helix styling
  app/src/atoms/buttons/index.ts
  app/src/organisms/ErrorRecoveryFlows/RunPausedSplash.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/AirGap.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/BlowOut.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Mix.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/PipettePath.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TouchTip.tsx
  app/src/pages/RunSummary/index.tsx
  components/src/atoms/buttons/LargeButton.stories.tsx
  components/src/atoms/buttons/LargeButton.tsx
  components/src/atoms/buttons/__tests__/LargeButton.test.tsx
  components/src/atoms/buttons/index.ts
Labels: authorship

#15912 feat(protocol-designer): add landing page
  components/src/atoms/buttons/LargeButton.tsx
  components/src/helix-design-system/product/typography.ts
  protocol-designer/src/images/welcome_page.png
  protocol-designer/src/localization/en/shared.json
  protocol-designer/src/pages/Landing/__tests__/Landing.test.tsx
  protocol-designer/src/pages/Landing/index.tsx
Labels: authorship

#15899 feat(protocol-designer): deck setup skeleton for redesign
  protocol-designer/src/components/DeckSetup/index.tsx
  protocol-designer/src/components/DeckSetupManager.tsx
  protocol-designer/src/localization/en/protocol_overview.json
  protocol-designer/src/pages/ProtocolOverview/DeckSetup/ControlSelect.tsx
  protocol-designer/src/pages/ProtocolOverview/DeckSetup/DeckSetup.module.css
  protocol-designer/src/pages/ProtocolOverview/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/ProtocolOverview/DeckSetup/SlotDetailsContainer.tsx
  protocol-designer/src/pages/ProtocolOverview/DeckSetup/index.tsx
  protocol-designer/src/pages/ProtocolOverview/DeckSetup/utils.ts
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolOverview.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#15902 feat(components, app): move ListItem and create a ListItem child
  app/src/organisms/EmergencyStop/EstopPressedModal.tsx
  app/src/organisms/IncompatibleModule/IncompatibleModuleODDModalBody.tsx
  app/src/organisms/QuickTransferFlow/Overview.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/BaseSettings.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
  app/src/organisms/QuickTransferFlow/TipManagement/index.tsx
  components/src/atoms/ListItem/ListItem.stories.tsx
  components/src/atoms/ListItem/ListItemChildren/ListItemDescriptor.tsx
  components/src/atoms/ListItem/__tests__/ListItem.test.tsx
  components/src/atoms/ListItem/index.tsx
  components/src/atoms/index.ts
Labels: authorship

#15958 feat(components): emptySelectorButton creation
  components/src/atoms/buttons/EmptySelectorButton.stories.tsx
  components/src/atoms/buttons/EmptySelectorButton.tsx
  components/src/atoms/buttons/__tests__/EmptySelectorButton.test.tsx
  components/src/atoms/buttons/index.ts
Labels: authorship

#15964 refactor(components, app): rename input field in components
  app/src/organisms/Devices/RobotSettings/ConnectNetwork/ConnectModal/TextField.tsx
  components/src/forms/InputField.stories.tsx
  components/src/forms/LegacyInputField.tsx
  components/src/forms/index.ts
  labware-library/src/labware-creator/components/TextField.tsx
  protocol-designer/src/components/EditableTextField.tsx
  protocol-designer/src/components/FilePage.tsx
  protocol-designer/src/components/LiquidPlacementForm/LiquidPlacementForm.tsx
  protocol-designer/src/components/LiquidsPage/LiquidEditForm.tsx
  protocol-designer/src/components/StepEditForm/fields/FlowRateField/FlowRateInput.tsx
  protocol-designer/src/components/StepEditForm/fields/ProfileItemRows.tsx
  protocol-designer/src/components/StepEditForm/fields/TextField.tsx
  protocol-designer/src/components/StepEditForm/fields/TipPositionField/TipPositionModal.tsx
  protocol-designer/src/components/StepEditForm/fields/TipPositionField/ZTipPositionModal.tsx
  protocol-designer/src/components/StepEditForm/fields/TipPositionField/index.tsx
  protocol-designer/src/components/StepEditForm/fields/TipWellSelectionField/index.tsx
  protocol-designer/src/components/StepEditForm/fields/WellSelectionField/WellSelectionField.tsx
  protocol-designer/src/components/modals/MoreOptionsModal.tsx
Labels: authorship

#15963 refactor(components, app): move MenuList folder to components directory
  app/src/atoms/MenuList/DropdownMenu.tsx
  app/src/molecules/InstrumentCard/MenuOverlay.tsx
  app/src/molecules/InstrumentCard/index.tsx
  app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx
  app/src/organisms/Devices/PipetteCard/PipetteOverflowMenu.tsx
  app/src/organisms/Devices/PipetteCard/index.tsx
  app/src/organisms/Devices/RobotOverflowMenu.tsx
  app/src/organisms/Devices/RobotOverviewOverflowMenu.tsx
  app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx
  app/src/organisms/ModuleCard/ModuleOverflowMenu.tsx
  app/src/organisms/ModuleCard/hooks.tsx
  app/src/organisms/ModuleCard/index.tsx
  app/src/organisms/Navigation/NavigationMenu.tsx
  app/src/organisms/ProtocolDetails/ProtocolLabwareDetails.tsx
  app/src/organisms/ProtocolsLanding/ProtocolList.tsx
  app/src/organisms/ProtocolsLanding/ProtocolOverflowMenu.tsx
  app/src/organisms/RobotSettingsCalibration/CalibrationDetails/ModuleCalibrationOverflowMenu.tsx
  app/src/organisms/RobotSettingsCalibration/CalibrationDetails/OverflowMenu.tsx
  app/src/organisms/RobotSettingsCalibration/RobotSettingsGripperCalibration.tsx
  app/src/pages/InstrumentDetail/InstrumentDetailOverflowMenu.tsx
  app/src/pages/Labware/index.tsx
  app/src/pages/ProtocolDashboard/LongPressModal.tsx
  app/src/pages/QuickTransferDashboard/LongPressModal.tsx
  app/tsconfig.json
  components/src/atoms/MenuList/MenuItem.stories.tsx
  components/src/atoms/MenuList/MenuItem.tsx
  components/src/atoms/MenuList/MenuList.stories.tsx
  components/src/atoms/MenuList/OverflowBtn.stories.tsx
  components/src/atoms/MenuList/OverflowBtn.tsx
  components/src/atoms/MenuList/__tests__/MenuItem.test.tsx
  components/src/atoms/MenuList/__tests__/MenuList.test.tsx
  components/src/atoms/MenuList/__tests__/OverflowBtn.test.tsx
  components/src/atoms/MenuList/index.tsx
  components/src/atoms/index.ts
  components/src/hooks/index.ts
  components/src/hooks/useMenuHandleClickOutside.tsx
Labels: authorship

#15972 refactor(protocol-designer): add some styling to navigation bar
  protocol-designer/src/Navbar.tsx
  protocol-designer/src/NavigationBar.tsx
  protocol-designer/src/ProtocolRoutes.tsx
  protocol-designer/src/localization/en/shared.json
Labels: authorship

#15979 refactor(components, app): move InputField component from app to components
  app/src/atoms/SoftwareKeyboard/AlphanumericKeyboard/AlphanumericKeyboard.stories.tsx
  app/src/atoms/SoftwareKeyboard/FullKeyboard/FullKeyboard.stories.tsx
  app/src/atoms/SoftwareKeyboard/IndividualKey/IndividualKey.stories.tsx
  app/src/atoms/SoftwareKeyboard/NumericalKeyboard/NumericalKeyboard.stories.tsx
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ChooseRobotSlideout/index.tsx
  app/src/organisms/ConfigurePipette/ConfigFormGroup.tsx
  app/src/organisms/Devices/RobotSettings/AdvancedTab/AdvancedTabSlideouts/FactoryModeSlideout.tsx
  app/src/organisms/Devices/RobotSettings/AdvancedTab/AdvancedTabSlideouts/RenameRobotSlideout.tsx
  app/src/organisms/ModuleCard/HeaterShakerSlideout.tsx
  app/src/organisms/ModuleCard/MagneticModuleSlideout.tsx
  app/src/organisms/ModuleCard/TemperatureModuleSlideout.tsx
  app/src/organisms/ModuleCard/TestShakeSlideout.tsx
  app/src/organisms/ModuleCard/ThermocyclerModuleSlideout.tsx
  app/src/organisms/NetworkSettings/SetWifiCred.tsx
  app/src/organisms/NetworkSettings/SetWifiSsid.tsx
  app/src/organisms/ProtocolSetupParameters/ChooseNumber.tsx
  app/src/organisms/QuickTransferFlow/NameQuickTransfer.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/AirGap.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/FlowRate.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/Mix.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/PipettePath.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TipPosition.tsx
  app/src/organisms/QuickTransferFlow/QuickTransferAdvancedSettings/TouchTip.tsx
  app/src/organisms/QuickTransferFlow/VolumeEntry.tsx
  app/src/organisms/QuickTransferFlow/__tests__/NameQuickTransfer.test.tsx
  app/src/organisms/QuickTransferFlow/__tests__/VolumeEntry.test.tsx
  app/src/pages/NameRobot/index.tsx
  components/src/atoms/InputField/InputField.stories.tsx
  components/src/atoms/InputField/__tests__/InputField.test.tsx
  components/src/atoms/InputField/index.tsx
  components/src/atoms/index.ts
Labels: authorship

#15985 refactor(robot-server): Single-source filenames
  robot-server/robot_server/data_files/dependencies.py
  robot-server/robot_server/deck_configuration/fastapi_dependencies.py
  robot-server/robot_server/persistence/__init__.py
  robot-server/robot_server/persistence/_files_and_directories.py
  robot-server/robot_server/persistence/_migrations/up_to_3.py
  robot-server/robot_server/persistence/_migrations/v3_to_v4.py
  robot-server/robot_server/persistence/_migrations/v4_to_v5.py
  robot-server/robot_server/persistence/_migrations/v5_to_v6.py
  robot-server/robot_server/persistence/fastapi_dependencies.py
  robot-server/robot_server/persistence/file_and_directory_names.py
  robot-server/robot_server/persistence/persistence_directory.py
  robot-server/robot_server/protocols/dependencies.py
  robot-server/tests/integration/http_api/protocols/test_persistence.py
Labels: robot-svcs, robot server

#15967 feat(components): listButton and accordion children creation
  components/src/atoms/ListButton/ListButton.stories.tsx
  components/src/atoms/ListButton/ListButtonChildren/ListButtonAccordion.tsx
  components/src/atoms/ListButton/ListButtonChildren/ListButtonAccordionContainer.tsx
  components/src/atoms/ListButton/ListButtonChildren/ListButtonRadioButton.tsx
  components/src/atoms/ListButton/ListButtonChildren/index.ts
  components/src/atoms/ListButton/__tests__/ListButton.test.tsx
  components/src/atoms/ListButton/__tests__/ListButtonAccordion.test.tsx
  components/src/atoms/ListButton/__tests__/ListButtonRadioButton.test.tsx
  components/src/atoms/ListButton/index.tsx
Labels: authorship

#15999 refactor(protocol-designer): move deck setup folder to correct pg
  protocol-designer/src/localization/en/protocol_overview.json
  protocol-designer/src/localization/en/starting_deck_state.json
  protocol-designer/src/pages/ProtocolOverview/DeckSetup/index.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolOverview.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
  protocol-designer/src/pages/StartingDeckState/ControlSelect.tsx
  protocol-designer/src/pages/StartingDeckState/DeckSetup.module.css
  protocol-designer/src/pages/StartingDeckState/DeckSetupDetails.tsx
  protocol-designer/src/pages/StartingDeckState/SlotDetailsContainer.tsx
  protocol-designer/src/pages/StartingDeckState/index.tsx
  protocol-designer/src/pages/StartingDeckState/utils.ts
Labels: authorship

#15990 feat(compnents): add DeckLabel and DeckLabelSet
  components/src/molecules/DeckLabel/DeckLabel.stories.tsx
  components/src/molecules/DeckLabel/__tests__/DeckLabel.test.tsx
  components/src/molecules/DeckLabel/index.tsx
  components/src/organisms/DeckLabelSet/DeckLabelSet.stories.tsx
  components/src/organisms/DeckLabelSet/__tests__/DeckLabelSet.test.tsx
  components/src/organisms/DeckLabelSet/index.tsx
  components/src/organisms/index.ts
Labels: authorship

#16008 refactor(components): toggleGroup creation from useToggleGroup
  app/src/molecules/ToggleGroup/useToggleGroup.tsx
  components/src/atoms/ToggleGroup/ToggleGroup.stories.tsx
  components/src/atoms/ToggleGroup/__tests__/ToggleGroup.test.tsx
  components/src/atoms/ToggleGroup/index.tsx
  components/src/atoms/index.ts
Labels: authorship

#15778 docs(api): additional partial tip pickup layouts in 2.20
  api/docs/v2/conf.py
  api/docs/v2/new_pipette.rst
  api/docs/v2/pipettes/characteristics.rst
  api/docs/v2/pipettes/partial_tip_pickup.rst
  api/docs/v2/versioning.rst
  api/src/opentrons/protocol_api/instrument_context.py
Labels: docs, papi-v2

#16012 feat(components): toolbox creation
  components/src/organisms/Toolbox/Toolbox.stories.tsx
  components/src/organisms/Toolbox/__tests__/Toolbox.test.tsx
  components/src/organisms/Toolbox/index.tsx
Labels: authorship

#15695 docs(api): liquid presence verification
  api/docs/v2/basic_commands/liquids.rst
  api/docs/v2/pipettes/loading.rst
  api/src/opentrons/protocol_api/instrument_context.py
  api/src/opentrons/protocol_api/protocol_context.py
Labels: docs, papi-v2

#16032 fix(app): remove unnecessary text
  app/src/assets/localization/en/protocol_details.json
  app/src/organisms/ChooseRobotSlideout/index.tsx
Labels: authorship

#16043 feat(protocol-designer, components): add SlotInformation component
  .storybook/main.js
  .storybook/preview.jsx
  components/src/atoms/ListItem/ListItemChildren/ListItemDescriptor.tsx
  components/src/atoms/index.ts
  protocol-designer/src/localization/en/shared.json
  protocol-designer/src/organisms/SlotInformation/SlotInformation.stories.tsx
  protocol-designer/src/organisms/SlotInformation/__tests__/SlotInformation.test.tsx
  protocol-designer/src/organisms/SlotInformation/index.tsx
  protocol-designer/src/organisms/index.ts
Labels: authorship

#16053 feat(protocol-designer): protocol overview foundation
  components/src/atoms/ListItem/ListItemChildren/ListItemDescriptor.tsx
  protocol-designer/src/localization/en/protocol_overview.json
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolOverview.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
Labels: authorship

#16040 fix(app): fix confirm values button issue
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ChooseRobotToRunProtocolSlideout/index.tsx
Labels: authorship

#16039 fix(app): fix long file name issue
  app/src/organisms/ProtocolSetupParameters/ViewOnlyParameters.tsx
Labels: authorship

#16041 fix(app): fix navigate condition issue
  app/src/pages/Devices/ProtocolRunDetails/__tests__/ProtocolRunDetails.test.tsx
  app/src/pages/Devices/ProtocolRunDetails/index.tsx
Labels: authorship

#16054 fix(app): dismiss run on `AnalysisFailedModal` CTA
  app/src/organisms/ProtocolSetupParameters/AnalysisFailedModal.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/AnalysisFailedModal.test.tsx
  app/src/pages/ProtocolSetup/index.tsx
Labels: authorship

#16059 feat(protocol-designer): default robot type to Flex on protocol onboarding
  protocol-designer/src/load-file/types.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectRobot.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
Labels: authorship

#16036 feat(protocol-designer): deck setup tools
  components/src/atoms/ListButton/ListButtonChildren/ListButtonAccordion.tsx
  components/src/atoms/index.ts
  components/src/index.ts
  components/src/organisms/Toolbox/Toolbox.stories.tsx
  components/src/organisms/Toolbox/__tests__/Toolbox.test.tsx
  components/src/organisms/Toolbox/index.tsx
  components/src/organisms/index.ts
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/pages/StartingDeckState/DeckSetupTools.tsx
  protocol-designer/src/pages/StartingDeckState/LabwareTools.tsx
  protocol-designer/src/pages/StartingDeckState/__tests__/DeckSetupTools.test.tsx
  protocol-designer/src/pages/StartingDeckState/__tests__/LabwareTools.test.tsx
  protocol-designer/src/pages/StartingDeckState/__tests__/utils.test.ts
  protocol-designer/src/pages/StartingDeckState/constants.ts
  protocol-designer/src/pages/StartingDeckState/index.tsx
  protocol-designer/src/pages/StartingDeckState/utils.ts
  protocol-designer/src/step-forms/actions/additionalItems.ts
  protocol-designer/src/step-forms/actions/thunks.ts
  shared-data/labware/fixtures/2/fixture_corning_96_wellplate_360_flat.json
  shared-data/labware/fixtures/2/fixture_universal_flat_bottom_adapter.json
  shared-data/labware/fixtures/2/index.ts
Labels: authorship

#15994 feat(components, protocol-designer): wire up create file pages and make ListItemCustomize
  components/src/atoms/Checkbox/index.tsx
  components/src/atoms/ListItem/ListItem.stories.tsx
  components/src/atoms/ListItem/ListItemChildren/ListItemCustomize.tsx
  components/src/atoms/ListItem/ListItemChildren/index.ts
  components/src/atoms/ListItem/index.tsx
  components/src/atoms/Tag/index.tsx
  protocol-designer/src/assets/localization/en/create_new_protocol.json
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/components/modals/utils.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/AddMetadata.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/PipetteInfoItem.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectFixtures.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectGripper.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectRobot.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/WizardBody.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/SelectGripper.test.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/SelectRobot.test.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/constants.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/types.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/utils.tsx
Labels: authorship

#15910 docs(api): CSV runtime parameters
  api/docs/v2/new_protocol_api.rst
  api/docs/v2/parameters/defining.rst
  api/docs/v2/parameters/use_case_cherrypicking.rst
  api/docs/v2/parameters/using_values.rst
  api/docs/v2/runtime_parameters.rst
  api/src/opentrons/protocols/parameters/csv_parameter_interface.py
Labels: docs, papi-v2

#16042 fix(components) fix Chip height issue and Parameters table display issue
  app/src/organisms/Devices/ProtocolRun/ProtocolRunRunTimeParameters.tsx
  components/src/atoms/Chip/index.tsx
Labels: authorship

#16081 feat(protocol-designer): incompatible tips modal in wizard flow
  protocol-designer/src/assets/localization/en/create_new_protocol.json
  protocol-designer/src/components/modals/utils.ts
  protocol-designer/src/organisms/IncompatibleTipsModal/__tests__/IncompatibleTipsModal.test.tsx
  protocol-designer/src/organisms/IncompatibleTipsModal/index.tsx
  protocol-designer/src/organisms/index.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/PipetteInfoItem.test.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/SelectPipettes.test.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/utils.tsx
Labels: authorship

#16073 feat(protocol-designer): import modals and landing pg touch up
  protocol-designer/src/NavigationBar.tsx
  protocol-designer/src/ProtocolRoutes.tsx
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/components/modals/FileUploadMessageModal/FileUploadMessageModal.tsx
  protocol-designer/src/organisms/FileUploadMessagesModal/__tests__/FileUploadMessagesModal.test.tsx
  protocol-designer/src/organisms/FileUploadMessagesModal/__tests__/utils.test.ts
  protocol-designer/src/organisms/FileUploadMessagesModal/index.tsx
  protocol-designer/src/organisms/FileUploadMessagesModal/utils.tsx
  protocol-designer/src/organisms/index.ts
  protocol-designer/src/pages/Landing/__tests__/Landing.test.tsx
  protocol-designer/src/pages/Landing/index.tsx
Labels: authorship

#16061 fix(app): fix add missing banner for runtime parameters
  app/src/assets/localization/en/protocol_setup.json
  app/src/organisms/Devices/ProtocolRun/ProtocolRunRunTimeParameters.tsx
  app/src/organisms/Devices/ProtocolRun/__tests__/ProtocolRunRuntimeParameters.test.tsx
Labels: authorship

#16077 feat(protocol-designer): labware upload modal
  protocol-designer/src/ProtocolRoutes.tsx
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/organisms/LabwareUploadModal/LabwareUploadModalBody.tsx
  protocol-designer/src/organisms/LabwareUploadModal/_tests__/LabwareUploadModal.test.tsx
  protocol-designer/src/organisms/LabwareUploadModal/index.tsx
  protocol-designer/src/organisms/index.ts
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupTools.test.tsx
Labels: authorship

#16107 feat(protocol-designer): display toast for auto-loaded hardware
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/pages/Designer/index.tsx
Labels: authorship

#16115 refactor(protocol-designer): designer nav bar
  protocol-designer/src/NavigationBar.tsx
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/__tests__/Designer.test.tsx
  protocol-designer/src/pages/Designer/index.tsx
Labels: authorship

#16114 feat(protocol-designer): module restrictions and snackbar rendering
  components/src/atoms/buttons/RadioButton.tsx
  components/src/atoms/buttons/__tests__/RadioButton.test.tsx
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupTools.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
Labels: authorship

#16121 feat(protocol-designer): make dev ffs accessible in the redesign
  protocol-designer/src/Bouncing.tsx
  protocol-designer/src/ProtocolEditor.tsx
  protocol-designer/src/organisms/FeatureFlagsModal/index.tsx
  protocol-designer/src/organisms/index.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/WizardBody.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
  protocol-designer/src/pages/Landing/index.tsx
Labels: authorship

#16089 feat(protocol-designer): onboarding flow module and fixture slot logic
  components/src/atoms/buttons/EmptySelectorButton.tsx
  components/src/atoms/buttons/LargeButton.tsx
  protocol-designer/src/assets/localization/en/create_new_protocol.json
  protocol-designer/src/pages/CreateNewProtocolWizard/AddMetadata.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/HandleEnter.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectFixtures.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectGripper.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectRobot.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/WizardBody.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/SelectFixtures.test.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/SelectModules.test.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/utils.test.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/constants.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/types.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/utils.tsx
Labels: authorship

#16140 feat(protocol-designer): off-deck labware view
  protocol-designer/src/Bouncing.tsx
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/organisms/SlotDetailsContainer/index.tsx
  protocol-designer/src/organisms/SlotInformation/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckItemHover.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SlotOverflowMenu.test.tsx
  protocol-designer/src/pages/Designer/Offdeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/Offdeck/Offdeck.tsx
  protocol-designer/src/pages/Designer/Offdeck/__tests__/OffDeckDetails.test.tsx
  protocol-designer/src/pages/Designer/Offdeck/__tests__/Offdeck.test.tsx
  protocol-designer/src/pages/Designer/Offdeck/index.ts
  protocol-designer/src/pages/Designer/index.tsx
Labels: authorship

#16153 feat(protocol-designer): wire up defining liquids
  protocol-designer/src/assets/localization/en/liquids.json
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/organisms/DefineLiquidsModal/index.tsx
  protocol-designer/src/organisms/DefineLiquidsModal/utils.ts
  protocol-designer/src/organisms/index.ts
  protocol-designer/src/pages/Designer/LiquidsOverflowMenu.tsx
  protocol-designer/src/pages/Designer/__tests__/Designer.test.tsx
  protocol-designer/src/pages/Designer/__tests__/LiquidsOverflowMenu.test.tsx
  protocol-designer/src/pages/Designer/index.tsx
Labels: authorship
