Repository Opentrons/opentrons, pull requests merged in 2024-07, with the labels that each got.

#15550 feat(app): clone run with CSV file IDs
  .github/workflows/app-test-build-deploy.yaml
  api-client/src/runs/types.ts
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ChooseRobotToRunProtocolSlideout/index.tsx
  app/src/organisms/Devices/utils.ts
  app/src/organisms/ProtocolUpload/hooks/__tests__/useCloneRun.test.tsx
Labels: authorship

#15563 refactor(app, components): fix styling of ProtocolDetails
  app/src/assets/localization/en/protocol_details.json
  app/src/organisms/Devices/ProtocolRun/SetupLiquids/SetupLiquidsList.tsx
  app/src/organisms/ProtocolDetails/ProtocolLabwareDetails.tsx
  app/src/organisms/ProtocolDetails/ProtocolParameters/index.tsx
  app/src/organisms/ProtocolDetails/RobotConfigurationDetails.tsx
  app/src/organisms/ProtocolDetails/__tests__/RobotConfigurationDetails.test.tsx
  app/src/organisms/ProtocolDetails/index.tsx
  components/src/molecules/ParametersTable/index.tsx
Labels: authorship

#15437 feat(components): added a component called Tabs
  app/src/atoms/buttons/TabbedButton.stories.tsx
  app/src/atoms/buttons/TabbedButton.tsx
  app/src/atoms/buttons/__tests__/TabbedButton.test.tsx
  app/src/atoms/buttons/index.ts
  app/src/organisms/LabwareOffsetTabs/index.tsx
  app/src/organisms/ProtocolDetails/index.tsx
  app/src/organisms/QuickTransferFlow/SelectDestLabware.tsx
  app/src/organisms/QuickTransferFlow/SelectSourceLabware.tsx
  app/src/organisms/QuickTransferFlow/SummaryAndSettings.tsx
  app/src/pages/ProtocolDetails/index.tsx
  components/src/molecules/RoundTab.stories.tsx
  components/src/molecules/RoundTab.tsx
  components/src/molecules/Tabs/Tabs.stories.tsx
  components/src/molecules/Tabs/__tests__/Tabs.test.tsx
  components/src/molecules/Tabs/index.tsx
  components/src/molecules/index.ts
Labels: authorship

#15572 feat(app): add uis for csv file
  app/src/assets/localization/en/protocol_info.json
  app/src/assets/localization/en/protocol_setup.json
  app/src/organisms/ProtocolSetupParameters/__tests__/ProtocolSetupParameters.test.tsx
  app/src/pages/ProtocolDashboard/PinnedProtocol.tsx
  app/src/pages/ProtocolDashboard/PinnedProtocolCarousel.tsx
  app/src/pages/ProtocolDashboard/ProtocolCard.tsx
  app/src/pages/ProtocolDashboard/__tests__/PinnedProtocol.test.tsx
  app/src/pages/ProtocolDashboard/__tests__/ProtocolCard.test.tsx
  app/src/pages/ProtocolDashboard/index.tsx
  app/src/pages/ProtocolDetails/fixtures.ts
Labels: authorship

#15575 feat(labware-library): add stacking offset image
  labware-library/src/images/stacking_offsets.svg
  labware-library/src/labware-creator/__tests__/StackingOffsets.test.tsx
  labware-library/src/labware-creator/components/sections/StackingOffsets.tsx
Labels: authorship

#15561 fix(ai-server): dependency upgrades for python 3.12.4
  opentrons-ai-server/Dockerfile
  opentrons-ai-server/Makefile
  opentrons-ai-server/Pipfile
  opentrons-ai-server/Pipfile.lock
  opentrons-ai-server/api/handler/fast.py
Labels: authorship

#15551 feat(app, app-shell-odd): add function to read csv file from usb
  api-client/src/dataFiles/types.ts
  app-shell-odd/src/actions.ts
  app-shell-odd/src/constants.ts
  app-shell-odd/src/main.ts
  app-shell-odd/src/types.ts
  app-shell-odd/src/usb.ts
  app/src/assets/localization/en/protocol_setup.json
  app/src/organisms/ChooseRobotToRunProtocolSlideout/index.tsx
  app/src/organisms/Devices/ProtocolRun/__tests__/ProtocolRunRuntimeParameters.test.tsx
  app/src/organisms/ProtocolSetupParameters/ChooseCsvFile.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/ChooseCsvFile.test.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/ProtocolSetupParameters.test.tsx
  app/src/organisms/ProtocolSetupParameters/index.tsx
  app/src/pages/ProtocolDashboard/PinnedProtocol.tsx
  app/src/redux/shell/actions.ts
  app/src/redux/shell/reducer.ts
  app/src/redux/shell/types.ts
  app/src/redux/shell/update.ts
  react-api-client/src/protocols/useProtocolAnalysesQuery.ts
Labels: authorship

#15582 refactor(components): remove global style from stories
  components/src/molecules/LocationIcon/LocationIcon.stories.tsx
Labels: authorship

#15577 feat(protocol-designer, step-generation): add comment to step form
  protocol-designer/src/components/StepCreationButton.tsx
  protocol-designer/src/components/StepEditForm/StepEditFormComponent.tsx
  protocol-designer/src/components/StepEditForm/forms/CommentForm/index.tsx
  protocol-designer/src/components/StepEditForm/forms/index.ts
  protocol-designer/src/components/steplist/CommentStepItems.tsx
  protocol-designer/src/components/steplist/StepItem.tsx
  protocol-designer/src/file-data/helpers/index.ts
  protocol-designer/src/form-types.ts
  protocol-designer/src/localization/en/application.json
  protocol-designer/src/localization/en/form.json
  protocol-designer/src/steplist/fieldLevel/index.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/getDisabledFields/index.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/commentFormToArgs.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/index.ts
  protocol-designer/src/steplist/generateSubstepItem.ts
  protocol-designer/src/steplist/types.ts
  protocol-designer/src/ui/steps/selectors.ts
  step-generation/src/commandCreators/index.ts
  step-generation/src/index.ts
  step-generation/src/types.ts
Labels: authorship

#15595 fix(protocol-designer): getPipetteCapacity correctly updates tip capa…
  protocol-designer/src/components/StepEditForm/fields/DisposalVolumeField.tsx
  protocol-designer/src/components/StepEditForm/fields/PathField/PathField.tsx
  protocol-designer/src/components/StepEditForm/fields/PathField/getDisabledPathMap.ts
  protocol-designer/src/pipettes/pipetteData.ts
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/test/utils.test.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/utils.ts
Labels: authorship

#15634 feat(app): Implement two cols RadioButton controller
  app/src/assets/localization/en/protocol_setup.json
  app/src/organisms/ProtocolSetupParameters/ChooseCsvFile.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/ChooseCsvFile.test.tsx
  app/src/organisms/ProtocolSetupParameters/index.tsx
  shared-data/js/types.ts
Labels: authorship

#15625 feat(app, shared-data): implement CSV runtime parameter functionality on ODD
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ChooseRobotSlideout/index.tsx
  app/src/organisms/Devices/utils.ts
  app/src/organisms/ProtocolSetupParameters/ChooseCsvFile.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/ProtocolSetupParameters.test.tsx
  app/src/organisms/ProtocolSetupParameters/index.tsx
  app/src/pages/ProtocolSetup/index.tsx
  shared-data/js/types.ts
Labels: authorship

#15657 feat(protocol-designer): create redesign ff and scaffolding for new nav
  protocol-designer/package.json
  protocol-designer/src/App.tsx
  protocol-designer/src/Navbar.tsx
  protocol-designer/src/ProtocolEditor.tsx
  protocol-designer/src/ProtocolRoutes.tsx
  protocol-designer/src/components/ProtocolEditor.tsx
  protocol-designer/src/feature-flags/reducers.ts
  protocol-designer/src/feature-flags/selectors.ts
  protocol-designer/src/feature-flags/types.ts
  protocol-designer/src/index.tsx
  protocol-designer/src/localization/en/feature_flags.json
  protocol-designer/src/localization/en/index.ts
  protocol-designer/src/localization/en/liquids.json
  protocol-designer/src/localization/en/protocol_overview.json
  protocol-designer/src/localization/en/protocol_steps.json
  protocol-designer/src/localization/en/shared.json
  protocol-designer/src/localization/en/starting_deck_state.json
  protocol-designer/src/localization/index.ts
  protocol-designer/src/pages/CreateNewProtocol/__tests__/CreateNewProtocol.test.tsx
  protocol-designer/src/pages/CreateNewProtocol/index.tsx
  protocol-designer/src/pages/Landing/__tests__/Landing.test.tsx
  protocol-designer/src/pages/Landing/index.tsx
  protocol-designer/src/pages/Liquids/__tests__/Liquids.test.tsx
  protocol-designer/src/pages/Liquids/index.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolOverview.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
  protocol-designer/src/pages/ProtocolSteps/__tests__/ProtocolSteps.test.tsx
  protocol-designer/src/pages/ProtocolSteps/index.tsx
  protocol-designer/src/pages/StartingDeckState/__tests__/StartingDeckState.test.tsx
  protocol-designer/src/pages/StartingDeckState/index.tsx
  protocol-designer/src/step-forms/selectors/index.ts
  protocol-designer/src/types.ts
  yarn.lock
Labels: authorship

#15693 fix(api-client): fix upload csv function issue
  api-client/src/dataFiles/uploadCsvFile.ts
Labels: authorship

#15684 feat(app): add a function to check unplug
  api-client/src/protocols/getCsvFiles.ts
  app/src/organisms/ProtocolSetupParameters/ChooseCsvFile.tsx
Labels: authorship

#15682 feat(app, api-client, react-api-client): update POST interface for file parameters
  api-client/src/protocols/createProtocol.ts
  api-client/src/protocols/createProtocolAnalysis.ts
  api-client/src/runs/createRun.ts
  api-client/src/runs/types.ts
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ChooseRobotToRunProtocolSlideout/index.tsx
  app/src/organisms/Devices/ProtocolRun/ProtocolRunRunTimeParameters.tsx
  app/src/organisms/Devices/utils.ts
  app/src/organisms/ProtocolSetupParameters/index.tsx
  app/src/organisms/ProtocolUpload/hooks/__tests__/useCloneRun.test.tsx
  app/src/organisms/ProtocolUpload/hooks/useCloneRun.ts
  react-api-client/src/protocols/useCreateProtocolAnalysisMutation.ts
  react-api-client/src/protocols/useCreateProtocolMutation.ts
Labels: authorship

#15700 fix(app) modify the conditions for confirm values button's aria-disabled
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ProtocolSetupParameters/ChooseCsvFile.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/ProtocolSetupParameters.test.tsx
  app/src/organisms/ProtocolSetupParameters/index.tsx
Labels: authorship

#15705 feat(protocol-designer): multiple h-s and mag block behind ff
  protocol-designer/src/components/EditModules.tsx
  protocol-designer/src/components/__tests__/EditModules.test.tsx
  protocol-designer/src/components/modals/CreateFileWizard/ModulesAndOtherTile.tsx
  protocol-designer/src/components/modals/CreateFileWizard/__tests__/ModulesAndOtherTile.test.tsx
  protocol-designer/src/feature-flags/reducers.ts
  protocol-designer/src/feature-flags/selectors.ts
  protocol-designer/src/feature-flags/types.ts
  protocol-designer/src/localization/en/feature_flags.json
Labels: authorship

#15714 feat(protocol-designer): put comment step behind ff
  protocol-designer/src/components/StepCreationButton.tsx
  protocol-designer/src/components/__tests__/StepCreationButton.test.tsx
  protocol-designer/src/feature-flags/reducers.ts
  protocol-designer/src/feature-flags/selectors.ts
  protocol-designer/src/feature-flags/types.ts
  protocol-designer/src/localization/en/feature_flags.json
  protocol-designer/src/localization/en/tooltip.json
Labels: authorship

#15709 fix(api-client): fix payload type for csv file from USB
  api-client/src/dataFiles/uploadCsvFile.ts
Labels: authorship

#15728 refactor(app): replace Flex+icon+text with Chip
  app/src/pages/ProtocolDashboard/ProtocolCard.tsx
  app/src/pages/ProtocolDashboard/__tests__/ProtocolCard.test.tsx
  app/src/pages/ProtocolDashboard/index.tsx
Labels: authorship

#15641 docs(api): fix typo calling `pick_up_tip` instead of `drop_tip`
  api/docs/v2/basic_commands/pipette_tips.rst
Labels: docs, papi-v2

#15794 refactor(labware-library): aluminum flat bottom plate compatible for …
  labware-library/src/labware-creator/components/sections/StackingOffsets.tsx
Labels: authorship

#15799 fix(app): add null and length check for array
  app/src/organisms/Devices/HistoricalProtocolRun.tsx
Labels: authorship

#15792 feat(ci): analyses snapshot skip pr on fail label
  .github/workflows/analyses-snapshot-test.yaml
Labels: no-analyses-snapshot-pr

#15807 fix(analyses-snapshot-testing): trigger test run on test library change
  .github/workflows/analyses-snapshot-test.yaml
  analyses-snapshot-testing/automation/data/protocols.py
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[057de2035d][OT2_S_v2_19_P300M_P20S_HS_TC_TM_SmokeTestV3].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[dabb7872d8][Flex_S_v2_19_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
Labels: gen-analyses-snapshot-pr

#15749 feat(app): add sorting function for csv files
  app/src/organisms/ProtocolSetupParameters/ChooseCsvFile.tsx
Labels: authorship

#15824 fix(app-shell-odd): fix csv files filtering
  app-shell-odd/src/usb.ts
Labels: authorship

#15731 refactor(api-client, app): activate getCsvFiles function
  api-client/src/protocols/getCsvFiles.ts
  app/src/organisms/ChooseProtocolSlideout/index.tsx
  app/src/organisms/ChooseRobotToRunProtocolSlideout/useCreateRunFromProtocol.ts
  app/src/organisms/ProtocolSetupParameters/ChooseCsvFile.tsx
  app/src/organisms/ProtocolSetupParameters/__tests__/ChooseCsvFile.test.tsx
Labels: authorship

#15840 refactor(protocol-designer): clean up form-types file and organize fields
  protocol-designer/src/form-types.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
Labels: authorship
