Repository Opentrons/opentrons, pull requests merged in 2025-03, with the labels that each got.

#17602 feat(protocol-designer,shared-data): add description to liquid classes
  api/tests/opentrons/conftest.py
  api/tests/opentrons/protocol_api_integration/test_liquid_classes.py
  protocol-designer/src/assets/localization/en/liquids.json
  protocol-designer/src/organisms/DefineLiquidsModal/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/PipetteField.tsx
  shared-data/js/liquidClasses.ts
  shared-data/js/types.ts
  shared-data/liquid-class/definitions/1/ethanol_80.json
  shared-data/liquid-class/definitions/1/glycerol_50.json
  shared-data/liquid-class/definitions/1/water.json
  shared-data/liquid-class/fixtures/1/fixture_glycerol50.json
  shared-data/liquid-class/schemas/1.json
  shared-data/python/opentrons_shared_data/liquid_classes/liquid_class_definition.py
Labels: authorship

#17611 fix(ab): verify protocol test intention matches analysis output
  .eslintignore
  .github/workflows/analyses-snapshot-test.yaml
  analyses-snapshot-testing/Makefile
  analyses-snapshot-testing/automation/analysis_matrix.py
  analyses-snapshot-testing/automation/data/protocols.py
  analyses-snapshot-testing/citools/generate_analyses.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_15_NO_PIPETTES_TC_verifyThermocyclerLoadedSlots.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_16_NO_PIPETTES_TC_verifyThermocyclerLoadedSlots.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_16_P1000_96_TC_PartialTipPickupSingle.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_17_NO_PIPETTES_TC_verifyThermocyclerLoadedSlots.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_18_Illumina_Stranded_total_RNA_Ribo_Zero.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_18_NO_PIPETTES_DescriptionTooLongRTP.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_19_Illumina_Stranded_total_RNA_Ribo_Zero.py
  analyses-snapshot-testing/files/protocols/OT2_X_v2_17_P300M_P20S_HS_TC_TM_dispense_changes.py
  analyses-snapshot-testing/files/protocols/OT2_X_v2_18_P300M_P20S_HS_TC_TM_SmokeTestV3.py
  analyses-snapshot-testing/files/protocols/OT2_X_v2_19_P300M_P20S_HS_TC_TM_SmokeTestV3.py
  analyses-snapshot-testing/files/protocols/OT2_X_v6_P20S_P300M_HS_HSCollision.json
  analyses-snapshot-testing/files/protocols/pl_Illumina_Stranded_total_RNA_Ribo_Zero_protocol.py
  analyses-snapshot-testing/files/protocols/pl_normalization_with_csv.py
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[06989450c4][OT2_X_v2_19_P300M_P20S_HS_TC_TM_SmokeTestV3].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[1baf3666f4][Flex_X_v2_18_Illumina_Stranded_total_RNA_Ribo_Zero].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[24462ac210][OT2_X_v2_18_P300M_P20S_HS_TC_TM_SmokeTestV3].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[29795b699e][Flex_X_v2_16_NO_PIPETTES_TC_verifyThermocyclerLoadedSlots].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[33db294a9b][Flex_X_v2_18_NO_PIPETTES_DescriptionTooLongRTP].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[87c1ba0c84][Flex_X_v2_16_P1000_96_TC_PartialTipPickupSingle].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[88de2fb78f][OT2_X_v6_P20S_P300M_HS_HSCollision].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[94cd467de4][Flex_X_v2_19_Illumina_Stranded_total_RNA_Ribo_Zero].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[9bcb0a3f13][pl_normalization_with_csv].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[a61a631b38][Flex_X_v2_15_NO_PIPETTES_TC_verifyThermocyclerLoadedSlots].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[b4f07bfb7c][Flex_X_v2_17_NO_PIPETTES_TC_verifyThermocyclerLoadedSlots].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[d2e641ad8a][OT2_X_v2_17_P300M_P20S_HS_TC_TM_dispense_changes].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[e0b0133ffb][pl_Illumina_Stranded_total_RNA_Ribo_Zero_protocol].json
  analyses-snapshot-testing/tests/audit_snapshot_test.py
  analyses-snapshot-testing/tests/audit_snapshots.py
Labels: gen-analyses-snapshot-pr

#17639 fix(shared-data): Remove cornerOffsetFromSlot from opentrons_flex_tiprack_lid
  shared-data/labware/definitions/3/opentrons_flex_tiprack_lid/1.json
Labels: gen-analyses-snapshot-pr

#17643 fix(protocol-designer) add 8.4.3 announcement
  protocol-designer/src/assets/localization/en/modal.json
  protocol-designer/src/organisms/AnnouncementModal/announcements.tsx
  protocol-designer/src/pages/ProtocolOverview/ProtocolMetadata.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolMetadata.test.tsx
Labels: authorship

#17582 feat(api): simulate liquid probe results
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[13e5a9c68b][Flex_S_v2_20_P8X1000_P50_LLD].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[2b866b03f3][Flex_S_v2_21_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[d2c818bf00][Flex_S_v2_20_P50_LPD].json
  api/src/opentrons/protocol_api/core/engine/instrument.py
  api/src/opentrons/protocol_api/core/engine/transfer_components_executor.py
  api/src/opentrons/protocol_api/core/engine/well.py
  api/src/opentrons/protocol_api/core/instrument.py
  api/src/opentrons/protocol_api/core/legacy/legacy_instrument_core.py
  api/src/opentrons/protocol_api/core/legacy/legacy_well_core.py
  api/src/opentrons/protocol_api/core/legacy_simulator/legacy_instrument_core.py
  api/src/opentrons/protocol_api/core/well.py
  api/src/opentrons/protocol_api/instrument_context.py
  api/src/opentrons/protocol_api/labware.py
  api/src/opentrons/protocol_engine/commands/liquid_probe.py
  api/src/opentrons/protocol_engine/execution/pipetting.py
  api/src/opentrons/protocol_engine/state/frustum_helpers.py
  api/src/opentrons/protocol_engine/state/geometry.py
  api/src/opentrons/protocol_engine/state/update_types.py
  api/src/opentrons/protocol_engine/state/wells.py
  api/src/opentrons/protocol_engine/types/liquid_level_detection.py
  api/tests/opentrons/protocol_engine/commands/test_liquid_probe.py
  api/tests/opentrons/protocol_engine/state/test_geometry_view.py
Labels: gen-analyses-snapshot-pr

#17664 fix(protocol-designer): disallow touchtip if destination is trash
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/index.tsx
Labels: authorship

#17652 feat(shared-data): introduce linear interpolation helper
  shared-data/js/helpers/__tests__/linearInterpolate.test.ts
  shared-data/js/helpers/index.ts
  shared-data/js/helpers/linearInterpolate.ts
Labels: authorship

#17576 fix(protocol-designer) modify the drag preview position
  protocol-designer/src/assets/images/preview.svg
  protocol-designer/src/assets/localization/en/deck.json
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/DragPreview.tsx
Labels: authorship

#17663 fix(protocol-designer): overhaul highlight logic for modules + labware
  protocol-designer/src/pages/Designer/DeckSetup/HighlightItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/ui/steps/actions/actions.ts
  protocol-designer/src/ui/steps/actions/thunks/index.ts
Labels: authorship

#17640 fix(protocol-designer): fix slot details width and OT-2 deck view size
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/HoverSlotDetailsContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/HoverSlotDetailsContainer.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
Labels: authorship

#17679 fix(protocol-designer) fix deck rendering issue
  protocol-designer/src/pages/ProtocolOverview/DeckThumbnail.tsx
  protocol-designer/src/pages/ProtocolOverview/StartingDeck.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/DeckThumbnail.test.tsx
Labels: authorship

#17685 fix(protocol-designer): fix whitescreen if magnetic module deleted
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MagnetTools/index.tsx
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/index.ts
Labels: authorship

#17553 feat(protocol-designer, component): add a new page for liquid classes in Transfer
  components/src/atoms/buttons/RadioButton.tsx
  protocol-designer/cypress/support/SetupSteps.ts
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/assets/localization/en/liquids.json
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/organisms/DefineLiquidsModal/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/LiquidClassesStepTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/LiquidClassesStepTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/MoveLiquidTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/index.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
  shared-data/js/helpers/__tests__/index.test.ts
  shared-data/js/helpers/index.ts
Labels: authorship

#17686 fix(protocol-designer): drag/drop refinement
  protocol-designer/cypress/support/SetupSteps.ts
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/AdapterControls.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/LabwareControls.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/SlotControls.tsx
  protocol-designer/src/step-forms/utils/index.ts
Labels: authorship

#17665 test(ab): add PD protocols
  analyses-snapshot-testing/automation/data/protocols.py
  analyses-snapshot-testing/files/protocols/Flex_S_PD8_4_2_Illumina_DNA_Prep_48x.json
  analyses-snapshot-testing/files/protocols/Flex_S_PD_8_4_2_Zymo_Magbead_DNA_Cells-Flex_96_channel.json
  analyses-snapshot-testing/files/protocols/OT2_S_PD_8_4_2_smoketest.json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[0ae87f73a2][Flex_S_PD8_4_2_Illumina_DNA_Prep_48x].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[a2f48a280e][OT2_S_PD_8_4_2_smoketest].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[df64ff8efd][Flex_S_PD_8_4_2_Zymo_Magbead_DNA_Cells-Flex_96_channel].json
Labels: gen-analyses-snapshot-pr

#17678 fix(step-generation, protocol-designer): prepareToAspirate before airGapInPlace
  protocol-designer/src/steplist/substepTimeline.ts
  protocol-designer/src/steplist/test/getPreviousMoveToAddressableAreaCommand.test.ts
  protocol-designer/src/steplist/utils/getPreviousMoveToAddressableAreaCommand.ts
  step-generation/src/__tests__/consolidate.test.ts
  step-generation/src/__tests__/distribute.test.ts
  step-generation/src/__tests__/transfer.test.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/fixtures/commandFixtures.ts
  step-generation/src/utils/misc.ts
Labels: authorship

#17683 fix(api, shared-data): Pick up tc lid directly off deck slot fix
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[2b866b03f3][Flex_S_v2_21_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[7d16d5dbf0][Flex_X_v2_21_tc_lids_wrong_target].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[99c15c6c62][Flex_S_v2_21_tc_lids_happy_path].json
  api/src/opentrons/protocol_engine/commands/move_labware.py
  api/tests/opentrons/protocol_api/test_protocol_context.py
  shared-data/labware/definitions/2/opentrons_tough_pcr_auto_sealing_lid/1.json
Labels: gen-analyses-snapshot-pr

#17717 fix(protocol-designer): add a missing item for release notes
  protocol-designer/src/organisms/AnnouncementModal/announcements.tsx
Labels: authorship

#17720 chore(components): hide props of style props in Storybook
  components/src/atoms/Chip/Chip.stories.tsx
  components/src/atoms/ListButton/ListButton.stories.tsx
  components/src/atoms/MenuList/MenuItem.stories.tsx
  components/src/atoms/Toast/Toast.stories.tsx
  components/src/atoms/buttons/LargeButton.stories.tsx
  components/src/modals/Modal.stories.tsx
  components/src/molecules/Banner/Banner.stories.tsx
  components/src/primitives/style-props.ts
Labels: components, Helix

#17721 docs(api): hide API 2.23 documentation until release
  api/src/opentrons/protocol_api/instrument_context.py
  api/src/opentrons/protocol_api/labware.py
  api/src/opentrons/protocol_api/protocol_context.py
Labels: docs, papi-v2

#17723 fix(shared-data): Zero out cornerOffsetFromSlot in opentrons_tough_pcr_auto_sealing_lid
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[2b866b03f3][Flex_S_v2_21_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[7d16d5dbf0][Flex_X_v2_21_tc_lids_wrong_target].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[99c15c6c62][Flex_S_v2_21_tc_lids_happy_path].json
  shared-data/labware/definitions/2/opentrons_tough_pcr_auto_sealing_lid/1.json
  shared-data/labware/definitions/3/opentrons_tough_pcr_auto_sealing_lid/2.json
Labels: gen-analyses-snapshot-pr

#17729 fix(protocol-designer): fix warning in AssignLiquidsModal
  protocol-designer/src/organisms/AssignLiquidsModal/index.tsx
  protocol-designer/src/organisms/Labware/SelectableLabware.tsx
  protocol-designer/src/organisms/Labware/SelectionRect.tsx
Labels: authorship

#17742 fix(protocol-designer): text display issue in mix step toolbox
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/PickUpTipField.tsx
Labels: authorship

#17755 fix(protocol-designer): fix settings page layout hen devf ff is on
  protocol-designer/cypress/e2e/settings.cy.ts
  protocol-designer/cypress/support/commands.ts
  protocol-designer/src/components/organisms/Settings/AppInfo.tsx
  protocol-designer/src/components/organisms/Settings/FeatureFlag.tsx
  protocol-designer/src/components/organisms/Settings/Privacy.tsx
  protocol-designer/src/components/organisms/Settings/UserSettings.tsx
  protocol-designer/src/components/organisms/Settings/__tests__/AppInfo.test.tsx
  protocol-designer/src/components/organisms/Settings/__tests__/FeatureFlag.test.tsx
  protocol-designer/src/components/organisms/Settings/__tests__/Privacy.test.tsx
  protocol-designer/src/components/organisms/Settings/__tests__/UserSettings.test.tsx
  protocol-designer/src/components/organisms/Settings/index.ts
  protocol-designer/src/pages/Settings/__tests__/Settings.test.tsx
  protocol-designer/src/pages/Settings/index.tsx
Labels: authorship

#17714 feat(api): dynamic liquid tracking papi changes
  api/src/opentrons/protocol_api/core/engine/instrument.py
  api/src/opentrons/protocol_api/core/engine/transfer_components_executor.py
  api/src/opentrons/protocol_api/core/instrument.py
  api/src/opentrons/protocol_api/core/legacy/legacy_instrument_core.py
  api/src/opentrons/protocol_api/core/legacy_simulator/legacy_instrument_core.py
  api/src/opentrons/protocol_api/instrument_context.py
  api/src/opentrons/protocol_api/labware.py
  api/src/opentrons/protocol_engine/commands/aspirate_while_tracking.py
  api/src/opentrons/protocol_engine/commands/dispense_while_tracking.py
  api/src/opentrons/protocol_engine/execution/pipetting.py
  api/src/opentrons/protocol_engine/state/geometry.py
  api/src/opentrons/types.py
  api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
  api/tests/opentrons/protocol_api/core/engine/test_transfer_components_executor.py
  api/tests/opentrons/protocol_api/test_instrument_context.py
  api/tests/opentrons/protocol_api/test_well.py
  api/tests/opentrons/protocol_engine/commands/test_aspirate_while_tracking.py
  api/tests/opentrons/protocol_engine/commands/test_dispense_while_tracking.py
  api/tests/opentrons/protocol_engine/execution/test_pipetting_handler.py
  api/tests/opentrons/protocol_engine/state/test_geometry_view.py
  api/tests/opentrons/test_types.py
Labels: gen-analyses-snapshot-pr

#17222 feat(protocol-designer, step-generation): single channel partial tip support for 'default' primaryNozzle only
  components/src/molecules/DropdownMenu/index.tsx
  protocol-designer/src/assets/localization/en/feature_flags.json
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/components/organisms/Labware/SelectableLabware.tsx
  protocol-designer/src/feature-flags/reducers.ts
  protocol-designer/src/feature-flags/selectors.ts
  protocol-designer/src/feature-flags/types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/PartialTipField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/FirstStepMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/utils.ts
  protocol-designer/src/step-forms/utils/createPresavedStepForm.ts
  protocol-designer/src/steplist/substepTimeline.ts
  protocol-designer/src/top-selectors/substep-highlight.ts
  step-generation/src/__tests__/configureNozzleLayout.test.ts
  step-generation/src/__tests__/getIsSafePipetteMovement.test.ts
  step-generation/src/commandCreators/atomic/aspirate.ts
  step-generation/src/commandCreators/atomic/dispense.ts
  step-generation/src/commandCreators/atomic/pickUpTip.ts
  step-generation/src/commandCreators/compound/consolidate.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/commandCreators/compound/mix.ts
  step-generation/src/commandCreators/compound/replaceTip.ts
  step-generation/src/getNextRobotStateAndWarnings/dispenseUpdateLiquidState.ts
  step-generation/src/getNextRobotStateAndWarnings/forAspirate.ts
  step-generation/src/getNextRobotStateAndWarnings/forPickUpTip.ts
  step-generation/src/robotStateSelectors.ts
  step-generation/src/utils/safePipetteMovements.ts
Labels: authorship

#17781 refactor(protocol-designer): clean up navigation redux selectors and …
  protocol-designer/cypress/e2e/urlNavigation.cy.ts
  protocol-designer/cypress/support/commands.ts
  protocol-designer/src/navigation/index.ts
  protocol-designer/src/navigation/reducers/index.ts
  protocol-designer/src/navigation/selectors.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
Labels: authorship

#17799 fix(protocol-designer): change BlockedSlot overlay for waste chute
  components/src/hardware-sim/BaseDeck/WasteChuteFixture.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/BlockedSlot.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/BlockedSlot.test.tsx
Labels: authorship

#17796 docs(api): note on `set_offset()` for multiple of same labware in 2.12-13
  api/src/opentrons/protocol_api/labware.py
Labels: docs, papi-v2

#17803 feat(protocol-designer): introduce `mmFromEdge` field to touchtip
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/fieldLevel/index.ts
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/index.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
  shared-data/command/types/pipetting.ts
  shared-data/js/helpers/index.ts
  step-generation/src/__tests__/touchTip.test.ts
  step-generation/src/commandCreators/atomic/touchTip.ts
Labels: authorship

#17823 fix(protocol-designer): fix whitescreen when destination is trash
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
Labels: authorship

#17763 test(ab): 8channel and single channel liquid class combinations
  analyses-snapshot-testing/automation/data/protocols.py
  analyses-snapshot-testing/automation/data/protocols_with_overrides.py
  analyses-snapshot-testing/files/protocols/Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_consolidate_liquid.py
  analyses-snapshot-testing/files/protocols/Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_distribute_liquid.py
  analyses-snapshot-testing/files/protocols/Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_transfer_liquid.py
  analyses-snapshot-testing/files/protocols/Flex_S_v2_23_P50_8ch_None_HappyPath_transfer_all3.py
  analyses-snapshot-testing/files/protocols/Flex_S_v2_23_P50_P1000_HappyPath_transfer_all3.py
  analyses-snapshot-testing/files/templates/basic_flex_rtp_v1.1.py
  analyses-snapshot-testing/files/templates/lc_v0.0.1.py
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[0893fff293][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_consolidate_liquid_Override_50_filter].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[0c20b5d38e][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_transfer_liquid_Override_50].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[148f6754a0][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_transfer_liquid_Override_1000].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[226af6cb95][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_transfer_liquid_Override_200_filter].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[30321455f1][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_distribute_liquid_Override_1000].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[50a7a2893e][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_transfer_liquid_Override_1000_filter].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[6673423fb6][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_distribute_liquid_Override_50].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[77f88c2054][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_distribute_liquid_Override_200].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[7eba33b8f5][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_transfer_liquid_Override_50_filter].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[7f54573e85][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_distribute_liquid_Override_200_filter].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[97e364b235][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_consolidate_liquid_Override_50].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[a36421e730][Flex_S_v2_23_P50_8ch_None_HappyPath_transfer_all3].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[a43093d4c5][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_transfer_liquid_Override_200].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[ccee96192d][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_consolidate_liquid_Override_1000_filter].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[ceccd7310d][Flex_S_v2_23_P50_P1000_HappyPath_transfer_all3].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[d43f23868d][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_distribute_liquid_Override_50_filter].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[df14956df7][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_consolidate_liquid_Override_200_filter].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[eb24dd6f60][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_consolidate_liquid_Override_200].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[edd4b39cc3][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_distribute_liquid_Override_1000_filter].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[f7caa70b8f][Flex_S_v2_23_P1000_8ch_None_HappyPath_Overrides_consolidate_liquid_Override_1000].json
Labels: gen-analyses-snapshot-pr

#17835 feat(protocol-designer,-shared-data): introduce push out field in PD
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/assets/localization/en/tooltip.json
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/fieldLevel/index.ts
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/index.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
  protocol-designer/src/utils/__tests__/utils.test.ts
  protocol-designer/src/utils/index.ts
  shared-data/js/types.ts
Labels: authorship

#17747 docs hotfix- push_out after dispense
  api/docs/v2/basic_commands/liquids.rst
  api/docs/v2/pipettes/volume_modes.rst
  api/src/opentrons/protocol_api/instrument_context.py
Labels: docs, papi-v2

#17888 refactor(protocol-designer): use windows vs mac symbols for hot keys
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/utils.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/ProtocolSteps.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
Labels: authorship

#17878 feat(protocol-designer): add release notes link to announcement modal
  protocol-designer/src/assets/localization/en/modal.json
  protocol-designer/src/components/organisms/AnnouncementModal/index.tsx
Labels: authorship

#17812 fix(api): clamp erroneous negative absorbance values to 0.
  api/src/opentrons/protocol_engine/state/modules.py
  api/tests/opentrons/protocol_engine/commands/absorbance_reader/test_read.py
Labels: gen-analyses-snapshot-pr

#17843 refactor(protocol-designer): consolidate CheckboxExapandStepFormFieldProps
  protocol-designer/cypress/e2e/mixSettings.cy.ts
  protocol-designer/cypress/support/MixSteps.ts
  protocol-designer/src/components/molecules/CheckboxExpandStepFormField/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/BatchEditToolbox/BatchEditMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/BatchEditToolbox/BatchEditMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/DisposalField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
Labels: authorship

#17928 feat(protocol-designer): update required app version to 8.4.0
  protocol-designer/src/pages/ProtocolOverview/ProtocolMetadata.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolMetadata.test.tsx
Labels: authorship

#17862 feat(protocol-designer): add liquid classes button as step 2
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/src/assets/localization/en/liquids.json
  protocol-designer/src/components/organisms/AnnouncementModal/announcements.tsx
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/FirstStepMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/SecondStepMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/__tests__/MixTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/LiquidClassesStepTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/LiquidClassesStepTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/index.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
Labels: authorship
