Repository Opentrons/opentrons, pull requests merged in 2025-05, with the labels that each got.

#18227 fix(protocol-designer): Fix Designer's page height issue
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLabwareTools/LabwareLocationField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLabwareTools/MoveLabwareField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Designer/index.tsx
  protocol-designer/src/pages/ProtocolOverview/OffdeckThumbnail.tsx
Labels: authorship

#18224 feat(protocol-designer): update required app version to 8.3.2
  protocol-designer/src/pages/ProtocolOverview/ProtocolMetadata.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolMetadata.test.tsx
Labels: authorship

#18223 fix(protocol-designer): get all labware defs instead of latest when z…
  protocol-designer/src/pages/Designer/DeckSetup/SelectedHoveredItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedHoveredItems.test.tsx
Labels: authorship

#18209 feat(app): Add Submerge screen to QT Aspirate and Dispense
  app/src/assets/localization/en/quick_transfer.json
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/AspirateSettingDetail.tsx
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/hooks/useAspirateSettingsConfig.ts
  app/src/organisms/ODD/QuickTransferFlow/Dispense/DispenseSettingDetail.tsx
  app/src/organisms/ODD/QuickTransferFlow/Dispense/hooks/useDispenseSettingsConfig.ts
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/BlowOut.tsx
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/Delay.tsx
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/Submerge.tsx
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/__tests__/Submerge.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/README.md
  app/src/organisms/ODD/QuickTransferFlow/__tests__/SelectPipettePath.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/constants.ts
  app/src/organisms/ODD/QuickTransferFlow/reducers.ts
  app/src/organisms/ODD/QuickTransferFlow/types.ts
Labels: authorship

#18239 fix(protocol-designer): lowVolumeDefault typo
  protocol-designer/src/utils/index.ts
Labels: authorship

#18217 feat(monorepo): transfer command creator overhaul: pt1
  app/src/organisms/ODD/QuickTransferFlow/__tests__/utils/quickTransferStepCommands.test.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/generateQuickTransferArgs.ts
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/components/organisms/TipPositionModal/index.tsx
  protocol-designer/src/components/organisms/TipPositionModal/utils.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/hooks.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.ts
  protocol-designer/src/steplist/substepTimeline.ts
  protocol-designer/src/timelineMiddleware/__tests__/generateRobotStateTimeline.test.ts
  shared-data/command/types/gantry.ts
  shared-data/js/helpers/__tests__/getMmFromBottom.test.ts
  shared-data/js/helpers/getMmFromBottom.ts
  shared-data/js/helpers/index.ts
  step-generation/src/__tests__/transfer.test.ts
  step-generation/src/commandCreators/atomic/moveToWell.ts
  step-generation/src/commandCreators/compound/mix.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/errorCreators.ts
  step-generation/src/fixtures/commandFixtures.ts
  step-generation/src/getNextRobotStateAndWarnings/index.ts
  step-generation/src/types.ts
Labels: authorship

#18242 feat(monorepo): transfer command creator updates pt.2
  app/src/organisms/ODD/QuickTransferFlow/__tests__/utils/quickTransferStepCommands.test.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/generateQuickTransferArgs.ts
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.ts
  protocol-designer/src/timelineMiddleware/__tests__/generateRobotStateTimeline.test.ts
  step-generation/src/__tests__/transfer.test.ts
  step-generation/src/commandCreators/atomic/touchTip.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/errorCreators.ts
  step-generation/src/fixtures/commandFixtures.ts
  step-generation/src/types.ts
Labels: authorship

#18238 refactor(protocol-designer): move labware selection to modal and create LabwareCard
  components/src/atoms/buttons/EmptySelectorButton.tsx
  protocol-designer/cypress/e2e/modules.cy.ts
  protocol-designer/cypress/e2e/plateReaderTest.cy.ts
  protocol-designer/cypress/e2e/transferSettings.cy.ts
  protocol-designer/cypress/support/SetupSteps.ts
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/components/organisms/ConfirmDeleteEntityInUseModal/__tests__/ConfirmDeleteEntityInUseModal.test.tsx
  protocol-designer/src/components/organisms/ConfirmDeleteEntityInUseModal/index.tsx
  protocol-designer/src/components/organisms/FlexHardware/index.tsx
  protocol-designer/src/components/organisms/LabwareCard/LabwareCard.stories.tsx
  protocol-designer/src/components/organisms/LabwareCard/__tests__/LabwareCard.test.tsx
  protocol-designer/src/components/organisms/LabwareCard/index.tsx
  protocol-designer/src/components/organisms/Ot2Modules/index.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/__tests__/SelectLabawareModal.test.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/index.tsx
  protocol-designer/src/components/organisms/index.ts
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupToolbox.tsx
  protocol-designer/src/pages/Designer/DeckSetup/HoveredItem.tsx
  protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedLabwareRender.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedModuleLabwareRender.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Selectedtems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupToolbox.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/HoveredItem.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedItems.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/OffDeck/index.tsx
Labels: authorship

#18221 fix(shared-data): Raise limit on rear deck extent padding offset
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[f7085d7134][Flex_X_v2_16_P1000_96_TC_pipetteCollisionWithThermocyclerLidClips].json
  shared-data/robot/definitions/1/ot3.json
Labels: gen-analyses-snapshot-pr

#18233 feat(protocol-designer): update Liquids page layout
  protocol-designer/src/assets/localization/en/liquids.json
  protocol-designer/src/components/organisms/AssignLiquidsModal/LiquidCard.tsx
  protocol-designer/src/components/organisms/AssignLiquidsModal/LiquidEditor.tsx
  protocol-designer/src/components/organisms/AssignLiquidsModal/LiquidToolbox.tsx
  protocol-designer/src/components/organisms/AssignLiquidsModal/NoLiquid.tsx
  protocol-designer/src/components/organisms/AssignLiquidsModal/__tests__/NoLiquid.test.tsx
  protocol-designer/src/components/organisms/AssignLiquidsModal/index.tsx
  protocol-designer/src/components/organisms/LiquidsOverflowMenu/index.tsx
Labels: authorship

#18287 fix(step-generation): allow multiple labware to be in the waste chute
  protocol-designer/release-notes.md
  step-generation/src/commandCreators/atomic/moveLabware.ts
Labels: authorship

#18288 fix(protocol-designer): disallow touch_tip from reseviors again
  protocol-designer/release-notes.md
  protocol-designer/src/load-file/migration/8_5_0.ts
Labels: authorship

#18281 refactor(protocol-designer): fix off-deck labware editing and clean up deck setup
  protocol-designer/src/components/organisms/SelectLabwareModal/__tests__/SelectLabawareModal.test.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/index.tsx
  protocol-designer/src/labware-ingred/actions/actions.ts
  protocol-designer/src/labware-ingred/actions/thunks.ts
  protocol-designer/src/labware-ingred/reducers/index.ts
  protocol-designer/src/labware-ingred/types.ts
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupToolbox.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedModuleLabwareRender.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupContainer.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupToolbox.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedItems.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/OffDeck/__tests__/OffDeck.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/ProtocolSteps.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Designer/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/index.tsx
  protocol-designer/src/pages/Designer/utils.ts
  protocol-designer/src/step-forms/actions/thunks.ts
Labels: authorship

#18283 fix(protocol-designer): fix decklabelset position issue
  components/src/organisms/DeckLabelSet/index.tsx
Labels: authorship

#18306 fix(step-generation): update aspirateInPlace robotState and add moveToWell to robotstate
  step-generation/src/getNextRobotStateAndWarnings/forMoveToWell.ts
  step-generation/src/getNextRobotStateAndWarnings/inPlaceCommandUpdates.ts
  step-generation/src/getNextRobotStateAndWarnings/index.ts
  step-generation/src/types.ts
Labels: authorship

#18258 feat(protocol-designer): update migration for speed-related fields
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/src/constants.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/utils.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/__tests__/utils.test.ts
Labels: authorship

#18286 feat(protocol-designer): create LabwareCardOverflowMenu
  components/src/atoms/MenuList/MenuItem.tsx
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/components/organisms/LabwareCard/__tests__/LabwareCard.test.tsx
  protocol-designer/src/components/organisms/LabwareCard/index.tsx
  protocol-designer/src/components/organisms/LabwareCardOverflowMenu/__tests__/LabwareCardOverflowMenu.test.tsx
  protocol-designer/src/components/organisms/LabwareCardOverflowMenu/index.tsx
  protocol-designer/src/components/organisms/LabwareNotCompatibleModal/__tests__/LabwareNotCompatibleModal.test.tsx
  protocol-designer/src/components/organisms/LabwareNotCompatibleModal/index.tsx
  protocol-designer/src/components/organisms/index.ts
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupToolbox.test.tsx
  protocol-designer/src/step-forms/reducers/index.ts
Labels: authorship

#18317 feat(protocol-designer): add a new custom hook for exporting protocol
  protocol-designer/src/pages/Onboarding/PDListItemCustomize.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
  protocol-designer/src/resources/hooks/__tests__/useProtocolExportHandler.test.tsx
  protocol-designer/src/resources/hooks/index.ts
  protocol-designer/src/resources/hooks/useProtocolExportHandler.tsx
Labels: authorship

#18274 feat(protocol-designer): add infoscreen to SelectLabwareModal
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/components/organisms/SelectLabwareModal/__tests__/SelectLabawareModal.test.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupToolbox.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupToolbox.test.tsx
Labels: authorship

#18310 feat(monorepo): finish step generation transfer updates for dispense
  app/src/organisms/ODD/QuickTransferFlow/__tests__/utils/quickTransferStepCommands.test.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/generateQuickTransferArgs.ts
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.ts
  protocol-designer/src/steplist/substepTimeline.ts
  protocol-designer/src/timelineMiddleware/__tests__/generateRobotStateTimeline.test.ts
  step-generation/src/__tests__/aspirateInPlace.test.ts
  step-generation/src/__tests__/blowOutInTrash.test.ts
  step-generation/src/__tests__/blowOutinWasteChute.test.ts
  step-generation/src/__tests__/dispenseInPlace.test.ts
  step-generation/src/__tests__/dispenseInTrash.test.ts
  step-generation/src/__tests__/dispenseInWasteChute.test.ts
  step-generation/src/__tests__/transfer.test.ts
  step-generation/src/commandCreators/atomic/aspirateInPlace.ts
  step-generation/src/commandCreators/atomic/blowOutInPlace.ts
  step-generation/src/commandCreators/atomic/dispenseInPlace.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/errorCreators.ts
  step-generation/src/fixtures/commandFixtures.ts
  step-generation/src/getNextRobotStateAndWarnings/forAspirate.ts
  step-generation/src/getNextRobotStateAndWarnings/forDispense.ts
  step-generation/src/getNextRobotStateAndWarnings/inPlaceCommandUpdates.ts
  step-generation/src/getNextRobotStateAndWarnings/index.ts
  step-generation/src/types.ts
Labels: authorship

#18333 refactor(step-generation): add trashBin/wasteChute to pipette robotState
  step-generation/src/__tests__/dispenseUpdateLiquidState.test.ts
  step-generation/src/__tests__/dropTipInWasteChute.test.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/getNextRobotStateAndWarnings/dispenseUpdateLiquidState.ts
  step-generation/src/getNextRobotStateAndWarnings/forAspirate.ts
  step-generation/src/getNextRobotStateAndWarnings/forBlowout.ts
  step-generation/src/getNextRobotStateAndWarnings/forDispense.ts
  step-generation/src/getNextRobotStateAndWarnings/forDropTip.ts
  step-generation/src/getNextRobotStateAndWarnings/forMoveToAddressableArea.ts
  step-generation/src/getNextRobotStateAndWarnings/forMoveToWell.ts
  step-generation/src/getNextRobotStateAndWarnings/inPlaceCommandUpdates.ts
  step-generation/src/getNextRobotStateAndWarnings/index.ts
  step-generation/src/types.ts
  step-generation/src/utils/misc.ts
Labels: authorship

#18341 feat(components): introduce tiprack background colors
  components/src/hardware-sim/Labware/labwareInternals/LabwareOutline.tsx
  components/src/hardware-sim/Labware/labwareInternals/getTiprackBackgroundColor.ts
  components/src/helix-design-system/colors.ts
Labels: authorship

#18321 refactor(protocol-designer): include liquid info in stepSummary
  components/src/atoms/Tag/index.tsx
  components/src/molecules/LiquidIcon/index.tsx
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/components/organisms/StepSummary/MixSummary.tsx
  protocol-designer/src/components/organisms/StepSummary/MoveLiquidSummary.tsx
  protocol-designer/src/components/organisms/StepSummary/StyledTrans.tsx
  protocol-designer/src/components/organisms/StepSummary/__tests__/StepSummary.test.tsx
  protocol-designer/src/components/organisms/StepSummary/__tests__/getLiquidDisplay.test.tsx
  protocol-designer/src/components/organisms/StepSummary/getLiquidDisplay.tsx
  protocol-designer/src/components/organisms/StepSummary/index.tsx
  protocol-designer/src/components/organisms/StepSummary/utils.ts
  protocol-designer/src/components/organisms/index.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/ProtocolSteps.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
Labels: authorship

#18346 refactor(protocol-designer): update module tools ui
  protocol-designer/cypress/e2e/thermocycler.cy.ts
  protocol-designer/cypress/support/ModuleSteps.ts
  protocol-designer/cypress/support/Thermocycler.ts
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/components/atoms/ToggleButton/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/TemperatureTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/__tests__/MagnetTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/__tests__/TemperatureTools.test.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/createBlankForm.ts
Labels: authorship

#18355 refactor(components, protocol-designer): use inlineNotification for er…
  app/src/molecules/InterventionModal/DescriptionContent.tsx
  app/src/molecules/InterventionModal/InterventionContent/index.tsx
  app/src/molecules/InterventionModal/TwoColumn.stories.tsx
  app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/FillWellAndRetrySameTips.tsx
  app/src/organisms/ErrorRecoveryFlows/RecoveryOptions/__tests__/FillWellAndRetrySameTips.test.tsx
  app/src/organisms/ErrorRecoveryFlows/shared/ErrorDetailsModal.tsx
  app/src/organisms/ErrorRecoveryFlows/shared/ReleaseLabware.tsx
  app/src/organisms/ErrorRecoveryFlows/shared/__tests__/ErrorDetailsModal.test.tsx
  app/src/organisms/InterventionModal/index.tsx
  app/src/organisms/LabwarePositionCheck/steps/HandleLabware/EditOffset/PrepareLabware/PlaceItemInstruction.tsx
  app/src/organisms/LabwarePositionCheck/steps/HandleLabware/LPCLabwareDetails/OffsetBannerContainer.tsx
  app/src/organisms/LabwarePositionCheck/steps/HandleLabware/LPCLabwareDetails/__tests__/LPCLabwareDetails.test.tsx
  app/src/organisms/LabwarePositionCheck/steps/HandleLabware/LPCLabwareDetails/__tests__/OffsetBannerContainer.test.tsx
  app/src/organisms/ODD/ChildNavigation/index.tsx
  app/src/organisms/ODD/ProtocolSetup/ProtocolSetupModulesAndDeck/ProtocolSetupModulesAndDeck.tsx
  app/src/organisms/ODD/RobotSettingsDashboard/RobotSystemVersionModal.tsx
  app/src/organisms/ODD/RobotSetupHeader/index.tsx
  app/src/pages/ODD/RobotSettingsDashboard/RobotSettingsList.tsx
  components/src/atoms/InlineNotification/InlineNotification.stories.tsx
  components/src/atoms/InlineNotification/__tests__/InlineNotification.test.tsx
  components/src/atoms/InlineNotification/index.tsx
  components/src/atoms/index.ts
  components/src/molecules/DropdownMenu/index.tsx
  protocol-designer/cypress/support/SetupSteps.ts
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/components/organisms/SelectLabwareModal/index.tsx
Labels: authorship

#18334 feat(shared-data, step-generation): add correction volumes to step generation
  shared-data/command/types/pipetting.ts
  shared-data/js/helpers/__tests__/liquidClasses.test.ts
  shared-data/js/helpers/index.ts
  shared-data/js/helpers/liquidClasses.ts
  step-generation/src/commandCreators/atomic/airGapInPlace.ts
  step-generation/src/commandCreators/atomic/aspirateInPlace.ts
  step-generation/src/commandCreators/atomic/dispenseInPlace.ts
  step-generation/src/commandCreators/compound/mix.ts
  step-generation/src/commandCreators/compound/transfer.ts
Labels: authorship

#18353 refactor(protocol-designer): various form UI updates
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/components/molecules/ToggleExpandStepFormField/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/TemperatureTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/ThermocyclerTools/ThermocyclerCycle.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/ThermocyclerTools/ThermocyclerStep.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/utils.ts
  protocol-designer/src/steplist/fieldLevel/errors.ts
  protocol-designer/src/steplist/fieldLevel/index.ts
  protocol-designer/src/steplist/fieldLevel/test/errors.test.ts
Labels: authorship

#18372 fix(protocol-designer): don't double render hover overlay
  protocol-designer/src/pages/ProtocolOverview/DeckThumbnailDetails.tsx
Labels: authorship

#18378 feat(components, protocol-designer): add size prop to enlarge DeckInfoLabel for web
  components/src/molecules/DeckInfoLabel/DeckInfoLabel.stories.tsx
  components/src/molecules/DeckInfoLabel/__tests__/DeckInfoLabel.test.tsx
  components/src/molecules/DeckInfoLabel/index.tsx
  protocol-designer/src/components/organisms/AssignLiquidsModal/index.tsx
Labels: authorship, Helix

#18382 fix(protocol-designer): properly null heaterShakerTimer field and dep
  protocol-designer/release-notes.md
  protocol-designer/src/assets/localization/en/modal.json
  protocol-designer/src/components/organisms/AnnouncementModal/announcements.tsx
  protocol-designer/src/steplist/fieldLevel/index.ts
  protocol-designer/src/steplist/fieldLevel/processing.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateHeaterShaker.ts
Labels: authorship

#18387 fix(protocol-designer): add trash required snackbar too all components
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/__tests__/AddStepButton.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/__tests__/StepContainer.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/ProtocolSteps.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/utils/index.ts
Labels: authorship

#18373 feat(protocol-designer, step-generation): ensure moveLiquid path is valid before step generation
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/FlowRateField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/LiquidClassesStepTools.test.tsx
  protocol-designer/src/step-forms/selectors/index.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/utils.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/index.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/test/moveLiquidFormToArgs.test.ts
  shared-data/js/liquidClasses.ts
  step-generation/src/types.ts
  step-generation/src/utils/__tests__/misc.test.ts
  step-generation/src/utils/misc.ts
Labels: authorship

#18392 fix(protocol-designer): correct numbering and scrolling down in onboa…
  protocol-designer/src/components/organisms/SelectPipetteModal/__test__/SelectPipetteModal.test.tsx
  protocol-designer/src/components/organisms/SelectPipetteModal/index.tsx
  protocol-designer/src/pages/Onboarding/AddMetadata.tsx
  protocol-designer/src/pages/Onboarding/SelectBasics.tsx
  protocol-designer/src/pages/Onboarding/SelectFlexHardware.tsx
  protocol-designer/src/pages/Onboarding/__tests__/AddMetadata.test.tsx
Labels: authorship

#18400 refactor(protocol-designer): form field error and caption audit
  protocol-designer/cypress/support/MixSteps.ts
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/assets/localization/en/modal.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/components/organisms/TipPositionModal/ZTipPositionModal.tsx
  protocol-designer/src/components/organisms/TipPositionModal/__tests__/TipPositionModal.test.tsx
  protocol-designer/src/components/organisms/TipPositionModal/__tests__/ZTipPositionModal.test.tsx
  protocol-designer/src/components/organisms/TipPositionModal/utils.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/FlowRateField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/FirstStepMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/FirstStepMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/utils.ts
  protocol-designer/src/step-forms/selectors/index.ts
  protocol-designer/src/steplist/fieldLevel/errors.ts
  protocol-designer/src/steplist/fieldLevel/index.ts
  protocol-designer/src/steplist/formLevel/errors.ts
Labels: authorship

#18390 fix(protocol-desinger): error handling for adding modules when slot h…
  protocol-designer/src/components/organisms/FlexHardware/util.ts
  protocol-designer/src/components/organisms/HardwareConfigurator/AddFixtureModal.tsx
  protocol-designer/src/components/organisms/__tests__/utils.test.tsx
  protocol-designer/src/components/organisms/utils.ts
Labels: authorship

#18404 feat(app,protocol-designer,shared-data,step-generation): update distribute
  app/src/organisms/ODD/QuickTransferFlow/__tests__/utils/quickTransferStepCommands.test.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/generateQuickTransferArgs.ts
  protocol-designer/cypress/support/Import.ts
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/FlowRateField.tsx
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/utils.ts
  protocol-designer/src/steplist/formLevel/index.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.ts
  protocol-designer/src/utils/index.ts
  shared-data/js/constants.ts
  shared-data/js/liquidClasses.ts
  step-generation/src/__tests__/distribute.test.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/errorCreators.ts
  step-generation/src/fixtures/commandFixtures.ts
  step-generation/src/types.ts
  step-generation/src/utils/misc.ts
Labels: authorship

#18323 fix(api): use same well offset between liquid measuring functions
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[d2c818bf00][Flex_S_v2_20_P50_LPD].json
  api/src/opentrons/protocol_api/core/engine/instrument.py
  api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
Labels: gen-analyses-snapshot-pr

#18421 refactor(protocol-designer): app version required now 8.5.0
  protocol-designer/src/pages/ProtocolOverview/ProtocolMetadata.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/ProtocolMetadata.test.tsx
Labels: authorship

#18408 feat(protocol-designer): introduce stacking to deckSetup labware selection
  components/src/atoms/ListButton/ListButtonChildren/ListButtonRadioButton.tsx
  components/src/atoms/ListButton/ListButtonChildren/index.ts
  components/src/atoms/ListButton/__tests__/ListButtonRadioButton.test.tsx
  components/src/molecules/CustomizeExpandButton/__tests__/CustomizeExpandButton.test.tsx
  components/src/molecules/CustomizeExpandButton/index.tsx
  components/src/molecules/index.ts
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/components/organisms/EditInstrumentsModal/editPipettes.ts
  protocol-designer/src/components/organisms/LabwareCard/__tests__/LabwareCard.test.tsx
  protocol-designer/src/components/organisms/LabwareCard/index.tsx
  protocol-designer/src/components/organisms/LabwareCardOverflowMenu/__tests__/LabwareCardOverflowMenu.test.tsx
  protocol-designer/src/components/organisms/LabwareCardOverflowMenu/index.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/__tests__/SelectLabawareModal.test.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/index.tsx
  protocol-designer/src/components/organisms/SlotInformation/index.tsx
  protocol-designer/src/labware-ingred/__tests__/actions.test.ts
  protocol-designer/src/labware-ingred/actions/actions.ts
  protocol-designer/src/labware-ingred/actions/thunks.ts
  protocol-designer/src/labware-ingred/reducers/index.ts
  protocol-designer/src/labware-ingred/types.ts
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupToolbox.tsx
  protocol-designer/src/pages/Designer/DeckSetup/HighlightItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedLabwareRender.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupToolbox.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedItems.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/constants.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/pages/Designer/HighlightLabware.tsx
  protocol-designer/src/pages/Designer/LabwareLabel.tsx
  protocol-designer/src/pages/Designer/OffDeck/__tests__/OffDeck.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/index.tsx
  protocol-designer/src/pages/Designer/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/utils.ts
  protocol-designer/src/pages/Onboarding/index.tsx
  protocol-designer/src/pages/ProtocolOverview/DeckThumbnailDetails.tsx
  protocol-designer/src/pages/ProtocolOverview/utils.ts
  protocol-designer/src/step-forms/actions/thunks.ts
  protocol-designer/src/top-selectors/labware-locations/index.ts
  shared-data/js/getLabware.ts
Labels: authorship

#18426 fix(protocol-designer): allow deletion of a liquid even if its not in…
  protocol-designer/release-notes.md
  protocol-designer/src/assets/localization/en/modal.json
  protocol-designer/src/components/organisms/AnnouncementModal/announcements.tsx
  protocol-designer/src/labware-ingred/actions/actions.ts
Labels: authorship

#18434 fix(components): fix alignment of `ListItemDescriptor`
  components/src/atoms/ListButton/ListButton.stories.tsx
  components/src/atoms/ListItem/ListItemChildren/ListItemDescriptor.tsx
Labels: authorship

#18443 feat(app): update Air gap screen in aspirate/dispense
  app/src/assets/localization/en/quick_transfer.json
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/hooks/useAspirateSettingsConfig.ts
  app/src/organisms/ODD/QuickTransferFlow/Dispense/hooks/useDispenseSettingsConfig.ts
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/AirGap.tsx
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/__tests__/AirGap.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/QuickTransferAdvancedSettings/AirGap.test.tsx
Labels: authorship

#18424 fix(protocol-designer): fix empty slots for ot-2
  protocol-designer/src/step-forms/utils/index.ts
Labels: authorship

#18439 fix(protocol-designer): fix liquids page's Done button cutoff issue
  .gitignore
  protocol-designer/src/components/organisms/AssignLiquidsModal/LiquidToolbox.tsx
  protocol-designer/src/components/organisms/AssignLiquidsModal/index.tsx
Labels: authorship

#18435 feat(app): update pre-wet tip screen
  app/src/assets/localization/en/quick_transfer.json
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/AspirateSettingDetail.tsx
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/hooks/useAspirateSettingsConfig.ts
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/PreWetTip.tsx
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/__tests__/PreWetTip.test.tsx
Labels: authorship

#18440 feat(protocol-designer): create labware quantity modal
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/components/organisms/EditLabwareQuantityModal/__tests__/EditLabwareQuantityModal.test.tsx
  protocol-designer/src/components/organisms/EditLabwareQuantityModal/index.tsx
  protocol-designer/src/components/organisms/LabwareCard/__tests__/LabwareCard.test.tsx
  protocol-designer/src/components/organisms/LabwareCard/index.tsx
  protocol-designer/src/components/organisms/index.ts
  protocol-designer/src/steplist/fieldLevel/processing.ts
Labels: authorship

#18463 fix(protocol-designer): allow for waste chute addition when labware i…
  protocol-designer/src/components/organisms/HardwareConfigurator/AddFixtureModal.tsx
Labels: authorship

#18465 fix(protocol-designer): fix hover behavior for timeline step
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
Labels: authorship
