Repository Opentrons/opentrons, pull requests merged in 2025-01, with the labels that each got.

#17185 fix(protocol-designer): allow minutesSeconds timer fields to add more…
  protocol-designer/src/steplist/fieldLevel/errors.ts
Labels: authorship

#17134 test(analyses): add 8.2 features to analyses battery
  analyses-snapshot-testing/README.md
  analyses-snapshot-testing/automation/data/protocols.py
  analyses-snapshot-testing/files/README.md
  analyses-snapshot-testing/files/protocols/Flex_S_v2_21_tc_lids_happy_path.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_21_plate_reader_bad_slot.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_21_plate_reader_no_close_lid.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_21_plate_reader_no_trash.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_21_plate_reader_wrong_plate.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_21_plate_reader_wrong_plate2.py
  analyses-snapshot-testing/files/protocols/Flex_X_v2_21_tc_lids_wrong_target.py
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[34f32336bc][Flex_X_v2_21_plate_reader_wrong_plate2].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[718c468b7d][Flex_X_v2_21_plate_reader_no_close_lid].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[7d16d5dbf0][Flex_X_v2_21_tc_lids_wrong_target].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[99c15c6c62][Flex_S_v2_21_tc_lids_happy_path].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[a5ba8297e3][Flex_X_v2_21_plate_reader_no_trash].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[ba14bd77a8][Flex_X_v2_21_plate_reader_bad_slot].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[fd26a20b4c][Flex_X_v2_21_plate_reader_wrong_plate].json
Labels: gen-analyses-snapshot-pr

#17189 fix(step-generation): configureForVolume volume correctly set to am…
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  step-generation/src/commandCreators/compound/transfer.ts
Labels: authorship

#17165 fix(protocol-designer): add align-items to title part
  protocol-designer/src/pages/ProtocolOverview/InstrumentsInfo.tsx
  protocol-designer/src/pages/ProtocolOverview/ProtocolMetadata.tsx
Labels: authorship

#17175 fix(protocol-designer): fix paddings in release note modal
  protocol-designer/src/organisms/AnnouncementModal/__tests__/AnnouncementModal.test.tsx
  protocol-designer/src/organisms/AnnouncementModal/index.tsx
Labels: authorship

#17162 fix(protocol-designer): allow custom labware on adapters
  protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
Labels: authorship

#17194 fix(protocol-designer): moving labware into waste chute step summary …
  protocol-designer/src/pages/Designer/ProtocolSteps/StepSummary.tsx
Labels: authorship

#17166 fix(protocol-designer): remove unused packages from pd
  protocol-designer/package.json
  yarn.lock
Labels: authorship

#17199 fix(protocol-designer): release notes banner dismisses upon clicking x
  protocol-designer/src/organisms/AnnouncementModal/index.tsx
  protocol-designer/src/pages/Landing/index.tsx
Labels: authorship

#17209 fix(protocol-designer): tooltip under path animation copy update
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/utils.ts
Labels: authorship

#17211 refactor(protocol-designer): liquid class ff reducer typo fix
  protocol-designer/src/feature-flags/reducers.ts
Labels: authorship

#17202 fix(step-generation): only aspirate disposal volume in first chunk
  step-generation/src/commandCreators/compound/distribute.ts
Labels: authorship

#17217 fix(protocol-designer): allow custom labware on adapters
  protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
Labels: authorship

#17221 fix(protocol-designer): unify time format to display the time
  protocol-designer/src/pages/Designer/ProtocolSteps/StepSummary.tsx
  protocol-designer/src/pages/Designer/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/utils.ts
Labels: authorship

#17228 fix(protocol-designer): fix small DQA bugs
  protocol-designer/cypress/support/commands.ts
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/pages/Designer/LiquidsOverflowMenu.tsx
  protocol-designer/src/pages/Designer/Offdeck/Offdeck.tsx
  protocol-designer/src/pages/Landing/__tests__/Landing.test.tsx
  protocol-designer/src/pages/Landing/index.tsx
Labels: authorship

#17226 refactor(protocol-designer): refactor EditInstrumentsModal
  protocol-designer/src/organisms/EditInstrumentsModal/PipetteConfiguration.tsx
  protocol-designer/src/organisms/EditInstrumentsModal/PipetteOverview.tsx
  protocol-designer/src/organisms/EditInstrumentsModal/__tests__/EditInstrumentsModal.test.tsx
  protocol-designer/src/organisms/EditInstrumentsModal/__tests__/usePipetteConfig.test.ts
  protocol-designer/src/organisms/EditInstrumentsModal/index.tsx
  protocol-designer/src/organisms/EditInstrumentsModal/usePipetteConfig.ts
Labels: authorship

#17177 chore(opentrons-ai-client): clean up react imports in opentrons-ai-client
  opentrons-ai-client/src/__testing-utils__/renderWithProviders.tsx
  opentrons-ai-client/src/atoms/ResizeBar/index.tsx
  opentrons-ai-client/src/atoms/SendButton/__tests__/SendButton.test.tsx
  opentrons-ai-client/src/atoms/TextAreaField/index.tsx
  opentrons-ai-client/src/molecules/Accordion/__tests__/Accordion.test.tsx
  opentrons-ai-client/src/molecules/Accordion/index.tsx
  opentrons-ai-client/src/molecules/ChatDisplay/__tests__/ChatDisplay.test.tsx
  opentrons-ai-client/src/molecules/InputPrompt/__tests__/InputPrompt.test.tsx
  opentrons-ai-client/src/molecules/PrimaryFloatingButton/__tests__/PrimaryFloatingButton.test.tsx
  opentrons-ai-client/src/molecules/PromptPreview/__tests__/PromptPreview.test.tsx
  opentrons-ai-client/src/molecules/PromptPreviewSection/__tests__/PromptPreviewSection.test.tsx
  opentrons-ai-client/src/molecules/UploadInput/index.tsx
  opentrons-ai-client/src/organisms/LabwareModal/index.tsx
  opentrons-ai-client/src/organisms/PromptButton/__tests__/PromptButton.test.tsx
  opentrons-ai-client/src/pages/CreateProtocol/index.tsx
  opentrons-ai-client/src/resources/hooks/__tests__/useTrackEvent.test.tsx
  opentrons-ai-client/src/resources/types.ts
Labels: authorship

#17246 fix(protocol-designer): fix back button in select pipette screen
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
Labels: authorship

#17254 fix(protocol-designer): z tip position copy updates
  protocol-designer/src/assets/localization/en/protocol_steps.json
Labels: authorship

#17255 fix(protocol-designer): ot-2 TC labware highlight in protocol steps
  protocol-designer/src/pages/Designer/DeckSetup/HighlightItems.tsx
Labels: authorship

#17262 fix(protocol-designer): fix save behavior for bad liquid form
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/organisms/AssignLiquidsModal/LiquidCard.tsx
  protocol-designer/src/organisms/AssignLiquidsModal/LiquidToolbox.tsx
Labels: authorship

#17230 fix(components,-protocol-designer): fix order and border radius logic for DeckLabelSet
  components/src/organisms/DeckLabelSet/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/ModuleLabel.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedHoveredItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedLabwareRender.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedHoveredItems.test.tsx
  protocol-designer/src/pages/Designer/LabwareLabel.tsx
Labels: authorship

#17214 test(analyses): add refactored 8.2 smoke test
  analyses-snapshot-testing/automation/data/protocols.py
  analyses-snapshot-testing/files/protocols/Flex_S_v2_21_P1000_96_GRIP_HS_MB_TC_TM_Smoke.py
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[2b866b03f3][Flex_S_v2_21_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
Labels: gen-analyses-snapshot-pr

#17263 feat(protocol-designer,-step-generation): update plate reader types and introduce step form
  protocol-designer/src/constants.ts
  protocol-designer/src/form-types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/index.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
  protocol-designer/src/step-forms/selectors/index.ts
  protocol-designer/src/step-forms/types.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  step-generation/src/commandCreators/atomic/moveLabware.ts
  step-generation/src/constants.ts
  step-generation/src/errorCreators.ts
  step-generation/src/types.ts
Labels: authorship

#17242 feat(protocol-designer): magnetic block can be added to staging area slot
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/modules/moduleData.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/utils.test.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/utils.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupTools.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
Labels: authorship

#17274 fix(protocol-designer): clean-up usage of css/styled-components with …
  protocol-designer/src/organisms/Labware/WellTooltip.tsx
Labels: authorship

#17280 feat(protocol-designer): initial absorbance reader stepform UI
  protocol-designer/src/assets/localization/en/application.json
  protocol-designer/src/constants.ts
  protocol-designer/src/form-types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/InitializationEditor.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/InitializationSettings.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/LidControls.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/ReadSettings.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/index.tsx
  protocol-designer/src/step-forms/utils/createPresavedStepForm.ts
  protocol-designer/src/steplist/formLevel/createBlankForm.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateAbsorbanceReader.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/index.ts
  protocol-designer/src/ui/modules/selectors.ts
  protocol-designer/src/ui/modules/utils.ts
Labels: authorship

#17287 feat(protocol-designer,-step-generation): wire up absorbance reader in step-generation
  protocol-designer/src/file-data/helpers/index.ts
  protocol-designer/src/form-types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/ReadSettings.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/index.tsx
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateAbsorbanceReader.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/absorbanceReaderFormToArgs.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/index.ts
  protocol-designer/src/steplist/generateSubstepItem.ts
  step-generation/src/__tests__/absorbanceReaderCloseInitialize.test.ts
  step-generation/src/__tests__/absorbanceReaderCloseLid.test.ts
  step-generation/src/__tests__/absorbanceReaderCloseRead.test.ts
  step-generation/src/__tests__/absorbanceReaderOpenLid.test.ts
  step-generation/src/commandCreators/atomic/absorbanceReaderCloseLid.ts
  step-generation/src/commandCreators/atomic/absorbanceReaderInitialize.ts
  step-generation/src/commandCreators/atomic/absorbanceReaderOpenLid.ts
  step-generation/src/commandCreators/atomic/absorbanceReaderRead.ts
  step-generation/src/commandCreators/atomic/index.ts
  step-generation/src/commandCreators/compound/absorbanceReaderCloseInitialize.ts
  step-generation/src/commandCreators/compound/absorbanceReaderCloseRead.ts
  step-generation/src/commandCreators/compound/index.ts
  step-generation/src/commandCreators/index.ts
  step-generation/src/errorCreators.ts
  step-generation/src/getNextRobotStateAndWarnings/absorbanceReaderUpdates.ts
  step-generation/src/getNextRobotStateAndWarnings/index.ts
  step-generation/src/index.ts
  step-generation/src/robotStateSelectors.ts
  step-generation/src/types.ts
Labels: authorship

#17290 feat(components): update RadioButton supported state
  components/src/atoms/buttons/RadioButton.tsx
Labels: authorship

#17259 feat(api, shared-data): Move lid command implementation
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[7d16d5dbf0][Flex_X_v2_21_tc_lids_wrong_target].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[99c15c6c62][Flex_S_v2_21_tc_lids_happy_path].json
  api/src/opentrons/legacy_commands/helpers.py
  api/src/opentrons/protocol_api/core/engine/deck_conflict.py
  api/src/opentrons/protocol_api/core/engine/protocol.py
  api/src/opentrons/protocol_api/core/engine/stringify.py
  api/src/opentrons/protocol_api/core/legacy/legacy_protocol_core.py
  api/src/opentrons/protocol_api/core/protocol.py
  api/src/opentrons/protocol_api/protocol_context.py
  api/src/opentrons/protocol_engine/__init__.py
  api/src/opentrons/protocol_engine/commands/absorbance_reader/__init__.py
  api/src/opentrons/protocol_engine/commands/load_lid.py
  api/src/opentrons/protocol_engine/commands/load_lid_stack.py
  api/src/opentrons/protocol_engine/commands/move_labware.py
  api/src/opentrons/protocol_engine/execution/equipment.py
  api/src/opentrons/protocol_engine/resources/labware_validation.py
  api/src/opentrons/protocol_engine/slot_standardization.py
  api/src/opentrons/protocol_engine/state/geometry.py
  api/src/opentrons/protocol_engine/state/labware.py
  api/src/opentrons/protocol_engine/state/update_types.py
  api/src/opentrons/protocol_engine/types.py
  api/tests/opentrons/protocol_api/test_protocol_context.py
  api/tests/opentrons/protocol_engine/state/test_labware_view_old.py
  app/src/molecules/PythonLabwareOffsetSnippet/createSnippet.ts
  app/src/organisms/Desktop/Devices/ProtocolRun/SetupLabware/LabwareListItem.tsx
  app/src/organisms/Desktop/Devices/ProtocolRun/SetupLabware/SetupLabwareList.tsx
  app/src/organisms/Desktop/Devices/RunPreview/index.tsx
  app/src/organisms/ErrorRecoveryFlows/hooks/useDeckMapUtils.ts
  app/src/organisms/InterventionModal/MoveLabwareInterventionContent.tsx
  app/src/organisms/InterventionModal/utils/getRunLabwareRenderInfo.ts
  app/src/organisms/LegacyApplyHistoricOffsets/hooks/getLabwareLocationCombos.ts
  app/src/organisms/LegacyLabwarePositionCheck/utils/labware.ts
  app/src/organisms/ODD/ProtocolSetup/ProtocolSetupLabware/SingleLabwareModal.tsx
  app/src/organisms/ODD/ProtocolSetup/ProtocolSetupLabware/index.tsx
  app/src/transformations/analysis/getLabwareOffsetLocation.ts
  app/src/transformations/analysis/getLabwareRenderInfo.ts
  app/src/transformations/commands/transformations/getLabwareSetupItemGroups.ts
  app/src/transformations/commands/transformations/getLocationInfoNames.ts
  app/src/transformations/commands/transformations/getNestedLabwareInfo.ts
  components/src/hardware-sim/BaseDeck/BaseDeck.tsx
  components/src/hardware-sim/Deck/MoveLabwareOnDeck.tsx
  components/src/hardware-sim/ProtocolDeck/utils/getLabwareInSlots.ts
  components/src/organisms/CommandText/useCommandTextString/utils/commandText/getLoadCommandText.ts
  components/src/organisms/CommandText/useCommandTextString/utils/getLabwareLocation.tsx
  labware-library/src/localization/en.ts
  protocol-designer/src/analytics/middleware.ts
  protocol-designer/src/labware-ingred/reducers/index.ts
  protocol-designer/src/pages/ProtocolOverview/utils.ts
  protocol-designer/src/step-forms/utils/index.ts
  protocol-designer/src/steplist/formLevel/moveLabwareFormErrors.ts
  shared-data/command/schemas/11.json
  shared-data/command/types/setup.ts
  shared-data/js/helpers/getAddressableAreasInProtocol.ts
  shared-data/js/helpers/parseProtocolCommands.ts
  shared-data/js/types.ts
  shared-data/labware/definitions/3/opentrons_tough_pcr_auto_sealing_lid/1.json
  shared-data/labware/definitions/3/protocol_engine_lid_stack_object/1.json
  step-generation/src/commandCreators/atomic/moveLabware.ts
  step-generation/src/getNextRobotStateAndWarnings/forMoveLabware.ts
  step-generation/src/utils/createTimelineFromRunCommands.ts
Labels: gen-analyses-snapshot-pr

#17297 fix(protocol-designer): get labware location from current step index
  protocol-designer/src/ui/labware/selectors.ts
  protocol-designer/src/ui/labware/utils.ts
Labels: authorship

#17302 fix(protocol-designer): oT-2 TC labware highlight refine logic
  protocol-designer/src/pages/Designer/DeckSetup/HighlightItems.tsx
Labels: authorship

#17306 feat(components, protocol-designer, step-generation): full absorbance reader step form UI
  components/src/atoms/InputField/index.tsx
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/constants.ts
  protocol-designer/src/form-types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/Initialization.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/InitializationEditor.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/InitializationSettings.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/LidControls.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/ReadSettings.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/utils.ts
  protocol-designer/src/step-forms/types.ts
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateAbsorbanceReader.ts
  protocol-designer/src/steplist/formLevel/index.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/absorbanceReaderFormToArgs.ts
  step-generation/src/commandCreators/atomic/absorbanceReaderInitialize.ts
  step-generation/src/commandCreators/compound/absorbanceReaderCloseInitialize.ts
Labels: authorship

#17309 fix(protocol-designer): update line clamp style for title
  protocol-designer/src/atoms/constants.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/utils.ts
Labels: authorship

#17315 feat(protocol-designer): add timeline alert translations for absorbance reader
  protocol-designer/src/assets/localization/en/alert.json
  protocol-designer/src/organisms/Alerts/TimelineAlerts.tsx
Labels: authorship

#17318 feat(protocol-designer): design cleanups and copy updates
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/Initialization.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/ReadSettings.tsx
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateAbsorbanceReader.ts
Labels: authorship

#17323 fix(protocol-designer): remove tooltips for move labware dropdown fields
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLabwareTools/LabwareLocationField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLabwareTools/MoveLabwareField.tsx
Labels: authorship

#17317 feat(protocol-designer): create hook for valid absorbance reader function
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/hooks/__tests__/useEnableReadOrInitialize.test.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/hooks/index.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/hooks/useAbsorbanceReaderCommandType.ts
Labels: authorship

#17321 feat(protocol-designer, step-generation): add gripper error creator for absorbance reader lid commands
  protocol-designer/src/assets/localization/en/alert.json
  step-generation/src/__tests__/absorbanceReaderCloseInitialize.test.ts
  step-generation/src/__tests__/absorbanceReaderCloseLid.test.ts
  step-generation/src/__tests__/absorbanceReaderCloseRead.test.ts
  step-generation/src/__tests__/absorbanceReaderOpenLid.test.ts
  step-generation/src/commandCreators/atomic/absorbanceReaderCloseLid.ts
  step-generation/src/commandCreators/atomic/absorbanceReaderOpenLid.ts
  step-generation/src/errorCreators.ts
  step-generation/src/types.ts
Labels: authorship

#17329 fix(protocol-designer): small style cleanup
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/Initialization.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/ThermocyclerTools/ThermocyclerState.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/ThermocyclerTools/index.tsx
Labels: authorship

#17334 fix(protocol-designer): check gripper use with absorbance reader
  protocol-designer/src/pages/ProtocolOverview/index.tsx
  protocol-designer/src/step-forms/reducers/index.ts
Labels: authorship

#17333 fix(components, protocol-designer): Update translations according to initial pre-DQA copy/style pass
  components/src/organisms/DeckLabelSet/index.tsx
  protocol-designer/src/assets/localization/en/alert.json
  protocol-designer/src/assets/localization/en/application.json
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/molecules/DropdownStepFormField/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckItemHighlight.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/InitializationSettings.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLabwareTools/LabwareLocationField.tsx
Labels: authorship

#17336 feat(protocol-designer): handle (no) gripper with absorbance reader
  protocol-designer/src/assets/localization/en/create_new_protocol.json
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/SelectModules.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupTools.test.tsx
Labels: DO NOT MERGE, authorship

#17340 fix(components, protocol-designer): implement ListButton in step forms
  components/src/molecules/DropdownMenu/index.tsx
  protocol-designer/src/molecules/InputStepFormField/index.tsx
  protocol-designer/src/molecules/ToggleExpandStepFormField/index.tsx
  protocol-designer/src/molecules/ToggleStepFormField/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/Initialization.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
Labels: authorship

#17335 feat(protocol-designer): fix whitescreen and add preselect form type
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/index.tsx
  protocol-designer/src/step-forms/utils/createPresavedStepForm.ts
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/index.ts
Labels: authorship

#17327 feat(step-generation): error creators for absorbance reader closed lid pipetting
  step-generation/src/__tests__/aspirate.test.ts
  step-generation/src/__tests__/blowout.test.ts
  step-generation/src/__tests__/dispense.test.ts
  step-generation/src/__tests__/moveToWell.test.ts
  step-generation/src/commandCreators/atomic/aspirate.ts
  step-generation/src/commandCreators/atomic/blowout.ts
  step-generation/src/commandCreators/atomic/dispense.ts
  step-generation/src/commandCreators/atomic/moveToWell.ts
  step-generation/src/utils/absorbanceReaderCollision.ts
  step-generation/src/utils/index.ts
Labels: authorship

#17343 fix(protocol-designer): update copy, add tooltips
  protocol-designer/src/assets/localization/en/alert.json
  protocol-designer/src/assets/localization/en/create_new_protocol.json
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectGripper.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/SelectGripper.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
Labels: authorship

#17352 fix(components,-protocol-designer): preselect useGripper in moveLabware form if attached
  components/src/atoms/Checkbox/index.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/step-forms/utils/createPresavedStepForm.ts
Labels: authorship

#17354 fix(protocol-designer): fix overflow button position
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
Labels: authorship

#17358 fix(protocol-designer): fix overflow button positoin for adding step
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
Labels: authorship

#17362 fix(protocol-designer): fix offdeck container border
  protocol-designer/src/pages/Designer/Offdeck/OffDeckDetails.tsx
Labels: authorship

#17365 feat(protocol-designer): add announcement for 8.4.0
  protocol-designer/cypress/support/SupportModules.ts
  protocol-designer/src/assets/images/opentrons_absorbance_plate_reader.png
  protocol-designer/src/assets/localization/en/modal.json
  protocol-designer/src/organisms/AnnouncementModal/announcements.tsx
Labels: authorship

#17344 fix(protocol-designer): update logic to add modules and fixtures with plate reader
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectFixtures.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/utils.test.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/constants.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/utils.tsx
Labels: authorship

#17372 fix(components,-protocol-designer): fix ToggleStepFormField style, realign step title
  components/src/atoms/ListButton/index.tsx
  protocol-designer/src/molecules/ToggleStepFormField/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
Labels: authorship

#17373 fix(protocol-designer): fix no tiprack-related whitescreen
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/TiprackField.tsx
Labels: authorship

#17366 refactor(protocol-designer): remove absorbance reader feature flag
  protocol-designer/src/assets/localization/en/feature_flags.json
  protocol-designer/src/feature-flags/reducers.ts
  protocol-designer/src/feature-flags/selectors.ts
  protocol-designer/src/feature-flags/types.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/SelectModules.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupTools.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
  protocol-designer/src/step-forms/selectors/index.ts
Labels: DO NOT MERGE

#17377 fix(protocol-designer): modify tiprack status check for deselecting
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectPipettes.tsx
Labels: authorship

#17367 docs(api): Update listed pipette flow rates
  api/docs/v2/pipettes/characteristics.rst
Labels: docs, papi-v2

#17380 fix(protocol-designer): filter trashbins from move labware new location
  protocol-designer/src/top-selectors/labware-locations/index.ts
Labels: authorship

#17351 feat(api): Addition of Evotip specific commands
  api/src/opentrons/hardware_control/api.py
  api/src/opentrons/hardware_control/ot3api.py
  api/src/opentrons/hardware_control/protocols/liquid_handler.py
  api/src/opentrons/hardware_control/protocols/motion_controller.py
  api/src/opentrons/legacy_commands/commands.py
  api/src/opentrons/legacy_commands/types.py
  api/src/opentrons/protocol_api/core/engine/instrument.py
  api/src/opentrons/protocol_api/core/instrument.py
  api/src/opentrons/protocol_api/core/legacy/legacy_instrument_core.py
  api/src/opentrons/protocol_api/core/legacy_simulator/legacy_instrument_core.py
  api/src/opentrons/protocol_api/instrument_context.py
  api/src/opentrons/protocol_engine/commands/__init__.py
  api/src/opentrons/protocol_engine/commands/command_unions.py
  api/src/opentrons/protocol_engine/commands/evotip_dispense.py
  api/src/opentrons/protocol_engine/commands/evotip_seal_pipette.py
  api/src/opentrons/protocol_engine/commands/evotip_unseal_pipette.py
  api/src/opentrons/protocol_engine/errors/__init__.py
  api/src/opentrons/protocol_engine/errors/exceptions.py
  api/src/opentrons/protocol_engine/execution/gantry_mover.py
  api/src/opentrons/protocol_engine/execution/tip_handler.py
  api/src/opentrons/protocol_engine/resources/labware_validation.py
  api/src/opentrons/protocol_engine/state/pipettes.py
  api/tests/opentrons/hardware_control/test_ot3_api.py
  api/tests/opentrons/protocol_engine/commands/test_evotip_dispense.py
  api/tests/opentrons/protocol_engine/commands/test_evotip_seal_pipette.py
  api/tests/opentrons/protocol_engine/commands/test_evotip_unseal_pipette.py
  api/tests/opentrons/protocol_engine/execution/test_gantry_mover.py
  api/tests/opentrons/protocol_engine/execution/test_tip_handler.py
  hardware-testing/hardware_testing/production_qc/gripper_assembly_qc_ot3/test_mount.py
  hardware-testing/hardware_testing/production_qc/robot_assembly_qc_ot3/test_instruments.py
  hardware-testing/hardware_testing/production_qc/z_stage_qc_ot3.py
  shared-data/command/schemas/11.json
  shared-data/labware/definitions/3/evotips_opentrons_96_labware/1.json
Labels: gen-analyses-snapshot-pr

#17392 fix(step-generation): properly update robotState when dispense is after airGap
  protocol-designer/src/steplist/substepTimeline.ts
  protocol-designer/src/steplist/test/generateSubsteps.test.ts
  step-generation/src/__tests__/transfer.test.ts
  step-generation/src/commandCreators/atomic/aspirate.ts
  step-generation/src/commandCreators/atomic/dispense.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/fixtures/commandFixtures.ts
  step-generation/src/fixtures/data.ts
  step-generation/src/getNextRobotStateAndWarnings/index.ts
Labels: authorship

#17389 fix(protocol-designer): modify the list button width
  protocol-designer/src/molecules/ToggleExpandStepFormField/index.tsx
Labels: authorship
