Repository Opentrons/opentrons, pull requests merged in 2025-04, with the labels that each got.

#17941 feat(app): add feature flag for liquid classes of qt
  app/src/assets/localization/en/app_settings.json
  app/src/pages/ODD/QuickTransferDashboard/index.tsx
  app/src/redux/config/constants.ts
  app/src/redux/config/schema-types.ts
Labels: authorship

#17958 fix(protocol-designer): more robust custom labware upload validation
  protocol-designer/src/labware-defs/actions.ts
  shared-data/js/helpers/index.ts
  shared-data/js/helpers/validateCustomLabwareHelper.ts
Labels: authorship

#17980 docs(api): use correct `delay()` method in `prepare_to_aspirate()` docstring
  api/src/opentrons/protocol_api/instrument_context.py
Labels: docs, papi-v2

#17962 feat(protocol-designer): preselect liquid class
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/assets/localization/en/liquids.json
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/__tests__/MixTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/LiquidClassesStepTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/LiquidClassesStepTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/MoveLiquidTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/hooks.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/utils.ts
  protocol-designer/src/step-forms/selectors/index.ts
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/getDisabledFields/getDisabledFieldsMoveLiquidForm.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
Labels: authorship

#17999 chore: fix storybook window size of pd
  .storybook/preview.tsx
Labels: authorship

#18002 feat(protocol-designer,-shared-data): autopopulate liquid class advanced settings
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/components/molecules/CheckboxExpandStepFormField/index.tsx
  protocol-designer/src/components/organisms/AdvancedSettingsUpdateConfirmationModal/index.tsx
  protocol-designer/src/components/organisms/AdvancedSettingsUpdateConfirmationModal/useConfirmationContent.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/steplist/fieldLevel/index.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/utils.ts
  shared-data/js/types.ts
Labels: authorship

#17984 feat(app): add aspirate tab and update overview for liquid classes
  app/src/assets/localization/en/quick_transfer.json
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/AspirateSettingDetail.tsx
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/AspirateSettingsList.tsx
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/constants.ts
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/hooks/useAspirateSettingsConfig.ts
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/index.tsx
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/types.ts
  app/src/organisms/ODD/QuickTransferFlow/Overview.tsx
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/index.tsx
  app/src/organisms/ODD/QuickTransferFlow/SummaryAndSettings.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/Aspirate/Aspirate.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/Aspirate/AspirateSettingDetail.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/Aspirate/AspirateSettingsList.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/Overview.test.tsx
Labels: authorship

#17887 docs(api): API reference entries for liquid class methods
  api/docs/v2/conf.py
  api/docs/v2/new_protocol_api.rst
  api/src/opentrons/protocol_api/instrument_context.py
Labels: docs, papi-v2

#17968 fix(protocol-designer): fix height issue in designer page
  protocol-designer/src/components/molecules/HotKeyDisplay/__tests__/HotKeyDisplay.test.tsx
  protocol-designer/src/components/molecules/HotKeyDisplay/index.tsx
  protocol-designer/src/components/molecules/index.ts
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLabwareTools/LabwareLocationField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLabwareTools/MoveLabwareField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Designer/index.tsx
  protocol-designer/src/pages/ProtocolOverview/OffdeckThumbnail.tsx
Labels: authorship

#18019 feat(app, protocol-designer, step-generation): wire up pushOut
  app/src/organisms/ODD/QuickTransferFlow/__tests__/utils/quickTransferStepCommands.test.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/generateQuickTransferArgs.ts
  protocol-designer/cypress/e2e/mixSettings.cy.ts
  protocol-designer/cypress/support/MixSteps.ts
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/SecondStepMixTools.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/index.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/mixFormToArgs.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/test/stepFormToArgs.test.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/timelineMiddleware/__tests__/generateRobotStateTimeline.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
  step-generation/src/__tests__/consolidate.test.ts
  step-generation/src/__tests__/distribute.test.ts
  step-generation/src/__tests__/mix.test.ts
  step-generation/src/__tests__/transfer.test.ts
  step-generation/src/commandCreators/atomic/dispense.ts
  step-generation/src/commandCreators/atomic/dispenseInPlace.ts
  step-generation/src/commandCreators/compound/consolidate.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/commandCreators/compound/mix.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/fixtures/commandFixtures.ts
  step-generation/src/types.ts
Labels: authorship

#18020 feat(app): add new setup flow screens to Quick Transfer
  app/src/assets/localization/en/quick_transfer.json
  app/src/organisms/ODD/QuickTransferFlow/SelectLiquidClass.tsx
  app/src/organisms/ODD/QuickTransferFlow/SelectPipettePath.tsx
  app/src/organisms/ODD/QuickTransferFlow/SelectTipDropLocation.tsx
  app/src/organisms/ODD/QuickTransferFlow/SelectTipFrequency.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/SelectLiquidClass.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/SelectPipettePath.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/SelectTipDropLocation.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/SelectTipFrequency.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/index.tsx
Labels: authorship

#17973 chore(api): measure_liquid_height isn't private
  api/src/opentrons/protocol_api/instrument_context.py
Labels: docs, papi-v2

#17897 docs(api): labware offset updates in 8.4
  api/docs/v2/new_advanced_running.rst
  api/src/opentrons/protocol_api/labware.py
Labels: docs, papi-v2

#18047 feat(app): update Select pipette path component
  app/src/organisms/ODD/QuickTransferFlow/README.md
  app/src/organisms/ODD/QuickTransferFlow/SelectPipettePath.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/SelectPipettePath.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/utils/getInitialSummaryState.test.ts
  app/src/organisms/ODD/QuickTransferFlow/reducers.ts
  app/src/organisms/ODD/QuickTransferFlow/types.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/getInitialSummaryState.ts
Labels: authorship

#18056 fix(protocol-designer): get all labware defs instead of latest when z…
  protocol-designer/src/pages/Designer/DeckSetup/SelectedHoveredItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedHoveredItems.test.tsx
Labels: authorship

#18062 refactor(protocol-designer): unify starting deck and protocol step tabs
  protocol-designer/cypress/e2e/mixSettings.cy.ts
  protocol-designer/cypress/e2e/modules.cy.ts
  protocol-designer/cypress/e2e/plateReaderTest.cy.ts
  protocol-designer/cypress/e2e/thermocycler.cy.ts
  protocol-designer/cypress/e2e/transferSettings.cy.ts
  protocol-designer/src/components/organisms/Alerts/ErrorContents.tsx
  protocol-designer/src/components/organisms/Alerts/__tests__/TimelineAlerts.test.tsx
  protocol-designer/src/components/organisms/DesignerNavigation/__tests__/DesignerNavigation.test.tsx
  protocol-designer/src/components/organisms/DesignerNavigation/index.tsx
  protocol-designer/src/components/organisms/SlotInformation/index.tsx
  protocol-designer/src/file-data/actions.ts
  protocol-designer/src/file-data/reducers/index.ts
  protocol-designer/src/file-data/selectors/fileFields.ts
  protocol-designer/src/file-data/types.ts
  protocol-designer/src/pages/Designer/DeckSetup/DeckItemHighlight.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/HighlightItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/HoverSlotDetailsContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/AdapterControls.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/LabwareControls.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/SlotControls.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupContainer.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/HoverSlotDetailsContainer.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/HoveredItems.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedHoveredItems.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/DeckSetup/types.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/pages/Designer/HighlightLabware.tsx
  protocol-designer/src/pages/Designer/LabwareLabel.tsx
  protocol-designer/src/pages/Designer/OffDeck/OffDeckControls.tsx
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/OffDeck/__tests__/OffDeck.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/__tests__/OffDeckDetails.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/TerminalItemStep.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/ProtocolSteps.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Designer/__tests__/Designer.test.tsx
  protocol-designer/src/pages/Designer/index.tsx
  protocol-designer/src/pages/Designer/types.ts
Labels: authorship

#17972 docs(api): lids updates in app 8.4 / PAPI 2.23
  api/docs/v2/modules/thermocycler.rst
  api/docs/v2/moving_labware.rst
  api/docs/v2/new_labware.rst
  api/src/opentrons/protocol_api/labware.py
  api/src/opentrons/protocol_api/protocol_context.py
Labels: docs, papi-v2

#18030 Rqa 4042 refactor get relative well location
  api/src/opentrons/protocol_api/core/engine/instrument.py
  api/src/opentrons/protocol_api/core/engine/pipette_movement_conflict.py
  api/src/opentrons/protocol_api/core/instrument.py
  api/src/opentrons/protocol_api/core/legacy/legacy_instrument_core.py
  api/src/opentrons/protocol_api/core/legacy_simulator/legacy_instrument_core.py
  api/src/opentrons/protocol_api/core/well.py
  api/src/opentrons/protocol_api/instrument_context.py
  api/src/opentrons/protocol_api/labware.py
  api/src/opentrons/protocol_engine/commands/liquid_probe.py
  api/src/opentrons/protocol_engine/commands/move_to_well.py
  api/src/opentrons/protocol_engine/state/geometry.py
  api/src/opentrons/protocol_engine/state/update_types.py
  api/src/opentrons/protocol_engine/types/__init__.py
  api/src/opentrons/protocol_engine/types/well_position.py
  api/tests/opentrons/protocol_api/core/engine/test_instrument_core.py
  api/tests/opentrons/protocol_engine/commands/test_move_to_well.py
  api/tests/opentrons/protocol_engine/state/test_geometry_view.py
  shared-data/command/schemas/12.json
Labels: gen-analyses-snapshot-pr

#18073 refactor(shared-data): change liquid classes order
  shared-data/js/liquidClasses.ts
Labels: authorship

#18066 feat(protocol-designer): introduce mix reference position
  protocol-designer/cypress/support/MixSteps.ts
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/assets/localization/en/application.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/assets/localization/en/tooltip.json
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/PositionField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/SecondStepMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/utils.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
Labels: authorship

#18044 refactor(protocol-designer): use deckConfigurator for hardware onboarding page
  app/src/organisms/DeviceDetailsDeckConfiguration/AddFixtureModal.tsx
  app/src/organisms/LocationConflictModal/ChooseModuleToConfigureModal.tsx
  components/src/hardware-sim/DeckConfigurator/EmptyConfigFixture.tsx
  components/src/hardware-sim/DeckConfigurator/index.tsx
  components/src/organisms/FixtureOption/__tests__/FixtureOption.test.tsx
  components/src/organisms/FixtureOption/index.tsx
  components/src/organisms/index.ts
  protocol-designer/cypress/e2e/modules.cy.ts
  protocol-designer/cypress/e2e/plateReaderTest.cy.ts
  protocol-designer/cypress/e2e/transferSettings.cy.ts
  protocol-designer/cypress/support/SetupSteps.ts
  protocol-designer/src/assets/localization/en/index.ts
  protocol-designer/src/assets/localization/en/onboarding.json
  protocol-designer/src/assets/localization/en/shared.json
  protocol-designer/src/assets/localization/index.ts
  protocol-designer/src/components/organisms/ConfirmDeleteEntityInUseModal/index.tsx
  protocol-designer/src/components/organisms/ConfirmDeleteStagingAreaModal/index.tsx
  protocol-designer/src/components/organisms/EditInstrumentsModal/PipetteConfiguration.tsx
  protocol-designer/src/components/organisms/EditInstrumentsModal/PipetteOverview.tsx
  protocol-designer/src/components/organisms/EditNickNameModal/index.tsx
  protocol-designer/src/components/organisms/EditProtocolMetadataModal/index.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/AddFixtureModal.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/__tests__/AddFixtureModal.test.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/__tests__/HardwareConfigurator.test.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/index.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/useDeckConfigurationEditing.tsx
  protocol-designer/src/components/organisms/IncompatibleTipsModal/index.tsx
  protocol-designer/src/components/organisms/PipetteInfoItem/index.tsx
  protocol-designer/src/components/organisms/SelectModules/AddModuleEmptySelectorButton.tsx
  protocol-designer/src/components/organisms/SelectModules/__tests__/AddModuleEmptySelectorButton.test.tsx
  protocol-designer/src/components/organisms/SelectModules/__tests__/SelectModules.test.tsx
  protocol-designer/src/components/organisms/SelectPipetteModal/SelectPipetteGen.tsx
  protocol-designer/src/components/organisms/SelectPipetteModal/SelectPipetteTips.tsx
  protocol-designer/src/components/organisms/SelectPipetteModal/SelectPipetteType.tsx
  protocol-designer/src/components/organisms/SelectPipetteModal/SelectPipetteVolume.tsx
  protocol-designer/src/components/organisms/SelectPipetteModal/__test__/SelectPipetteModal.test.tsx
  protocol-designer/src/components/organisms/SelectPipetteModal/index.tsx
  protocol-designer/src/components/organisms/index.ts
  protocol-designer/src/components/organisms/types.ts
  protocol-designer/src/modules/thunks.ts
  protocol-designer/src/pages/Onboarding/AddMetadata.tsx
  protocol-designer/src/pages/Onboarding/ModuleDiagram.tsx
  protocol-designer/src/pages/Onboarding/SelectBasics.tsx
  protocol-designer/src/pages/Onboarding/SelectFixtures.tsx
  protocol-designer/src/pages/Onboarding/SelectFlexHardware.tsx
  protocol-designer/src/pages/Onboarding/SelectOt2Modules.tsx
  protocol-designer/src/pages/Onboarding/WizardBody.tsx
  protocol-designer/src/pages/Onboarding/__tests__/AddMetadata.test.tsx
  protocol-designer/src/pages/Onboarding/__tests__/SelectBasics.test.tsx
  protocol-designer/src/pages/Onboarding/__tests__/SelectFixtures.test.tsx
  protocol-designer/src/pages/Onboarding/__tests__/SelectOt2Modules.test.tsx
  protocol-designer/src/pages/Onboarding/__tests__/utils.test.ts
  protocol-designer/src/pages/Onboarding/index.tsx
  protocol-designer/src/pages/Onboarding/types.ts
  protocol-designer/src/pages/Onboarding/utils.tsx
  protocol-designer/src/step-forms/types.ts
Labels: authorship

#18054 feat(app): remove event tracking from aspirate tab and dispense tab
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/index.tsx
  app/src/organisms/ODD/QuickTransferFlow/Dispense/index.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/Aspirate/Aspirate.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/Dispense/Dispense.test.tsx
  app/src/redux/analytics/constants.ts
Labels: authorship

#18065 feat(app): update select tip drop location component
  app/src/organisms/ODD/QuickTransferFlow/README.md
  app/src/organisms/ODD/QuickTransferFlow/SelectTipDropLocation.tsx
  app/src/organisms/ODD/QuickTransferFlow/SelectTipFrequency.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/SelectPipettePath.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/SelectTipDropLocation.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/SelectTipFrequency.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/reducers.ts
  app/src/organisms/ODD/QuickTransferFlow/types.ts
Labels: authorship

#18074 refactor(protocol-designer): unify nav bar and modify back and liquids button
  protocol-designer/cypress/support/MixSteps.ts
  protocol-designer/cypress/support/Thermocycler.ts
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/components/organisms/AssignLiquidsModal/index.tsx
  protocol-designer/src/components/organisms/DesignerNavigation/__tests__/DesignerNavigation.test.tsx
  protocol-designer/src/components/organisms/DesignerNavigation/index.tsx
  protocol-designer/src/components/organisms/LiquidsOverflowMenu/__tests__/LiquidsOverflowMenu.test.tsx
  protocol-designer/src/components/organisms/LiquidsOverflowMenu/index.tsx
  protocol-designer/src/components/organisms/Navigation/__tests__/Navigation.test.tsx
  protocol-designer/src/components/organisms/Navigation/index.tsx
  protocol-designer/src/components/organisms/SettingsIcon/index.tsx
  protocol-designer/src/components/organisms/index.ts
  protocol-designer/src/load-file/__tests__/reducers.test.ts
  protocol-designer/src/load-file/reducers.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/TimelineToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/__tests__/TimelineToolbox.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/DraggableSidebar.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/ProtocolSteps.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Designer/__tests__/Designer.test.tsx
  protocol-designer/src/pages/Designer/index.tsx
  protocol-designer/src/pages/Liquids/__tests__/Liquids.test.tsx
  protocol-designer/src/pages/Liquids/index.tsx
  protocol-designer/src/pages/Onboarding/index.tsx
Labels: authorship

#18089 fix(protocol-designer): check path in conditioning volume form errors
  protocol-designer/src/steplist/formLevel/errors.ts
Labels: authorship

#18090 refactor(protocol-designer): change default state for SelectBasics buttons
  components/src/atoms/buttons/RadioButton.tsx
  protocol-designer/cypress/e2e/modules.cy.ts
  protocol-designer/cypress/e2e/plateReaderTest.cy.ts
  protocol-designer/cypress/e2e/transferSettings.cy.ts
  protocol-designer/cypress/support/SetupSteps.ts
  protocol-designer/src/components/molecules/BasicButtons/index.tsx
  protocol-designer/src/components/molecules/index.ts
  protocol-designer/src/components/organisms/HardwareConfigurator/__tests__/HardwareConfigurator.test.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/index.tsx
  protocol-designer/src/components/organisms/SelectPipetteModal/__test__/SelectPipetteModal.test.tsx
  protocol-designer/src/components/organisms/types.ts
  protocol-designer/src/load-file/types.ts
  protocol-designer/src/pages/Onboarding/SelectBasics.tsx
  protocol-designer/src/pages/Onboarding/__tests__/AddMetadata.test.tsx
  protocol-designer/src/pages/Onboarding/__tests__/SelectBasics.test.tsx
  protocol-designer/src/pages/Onboarding/__tests__/SelectOt2Modules.test.tsx
  protocol-designer/src/pages/Onboarding/index.tsx
Labels: authorship

#18099 fix(protocol-designer): properly find defs for adapter/labware combo split defs
  protocol-designer/src/load-file/migration/7_0_0.ts
Labels: authorship

#18025 docs(api): load liquids in API 2.23
  api/docs/v2/new_labware.rst
  api/docs/v2/new_protocol_api.rst
  api/src/opentrons/protocol_api/instrument_context.py
  api/src/opentrons/protocol_api/labware.py
Labels: docs, papi-v2

#18088 docs(api): API 2.23 Versioning page
  api/docs/v2/conf.py
  api/docs/v2/versioning.rst
Labels: docs, papi-v2

#18104 fix(protocol-designer): show correct waste chute fixture options and …
  protocol-designer/src/components/organisms/HardwareConfigurator/AddFixtureModal.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/useDeckConfigurationEditing.tsx
Labels: authorship

#18105 fix(protocol-designer): fix touchtip mmFromEdge migration
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/src/components/molecules/InputStepFormField/index.tsx
  protocol-designer/src/constants.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/index.ts
Labels: authorship

#18084 feat(protocol-designer): add edit hardware section to overview
  protocol-designer/src/ProtocolRoutes.tsx
  protocol-designer/src/assets/localization/en/protocol_overview.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/components/organisms/HardwareConfigurator/AddFixtureModal.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/__tests__/HardwareConfigurator.test.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/index.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/useDeckConfigurationEditing.tsx
  protocol-designer/src/components/organisms/ModuleEmptySelectorButtons.tsx
  protocol-designer/src/components/organisms/index.ts
  protocol-designer/src/components/organisms/types.ts
  protocol-designer/src/components/organisms/utils.ts
  protocol-designer/src/modules/__tests__/moduleData.test.tsx
  protocol-designer/src/modules/moduleData.ts
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Hardware/FlexHardware.tsx
  protocol-designer/src/pages/Hardware/Ot2Modules.tsx
  protocol-designer/src/pages/Hardware/__tests__/FlexHardware.test.tsx
  protocol-designer/src/pages/Hardware/__tests__/Hardware.test.tsx
  protocol-designer/src/pages/Hardware/__tests__/Ot2Modules.test.tsx
  protocol-designer/src/pages/Hardware/__tests__/updateInitialDeckState.test.tsx
  protocol-designer/src/pages/Hardware/index.tsx
  protocol-designer/src/pages/Hardware/util.ts
  protocol-designer/src/pages/Onboarding/SelectBasics.tsx
  protocol-designer/src/pages/Onboarding/SelectFlexHardware.tsx
  protocol-designer/src/pages/Onboarding/SelectOt2Modules.tsx
  protocol-designer/src/pages/Onboarding/constants.ts
  protocol-designer/src/pages/Onboarding/index.tsx
  protocol-designer/src/pages/ProtocolOverview/HardwareInfo.tsx
  protocol-designer/src/pages/ProtocolOverview/__tests__/HardwareInfo.test.tsx
  protocol-designer/src/pages/ProtocolOverview/index.tsx
  protocol-designer/src/pages/index.ts
Labels: authorship

#18093 feat(protocol-designer): decouple hardware and labware in deckSetup
  protocol-designer/cypress/e2e/modules.cy.ts
  protocol-designer/cypress/e2e/plateReaderTest.cy.ts
  protocol-designer/cypress/e2e/transferSettings.cy.ts
  protocol-designer/cypress/support/SetupSteps.ts
  protocol-designer/src/constants.ts
  protocol-designer/src/labware-ingred/actions/thunks.ts
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupToolbox.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/HoveredItem.tsx
  protocol-designer/src/pages/Designer/DeckSetup/HoveredItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/LabwareTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SelectedHoveredItems.tsx
  protocol-designer/src/pages/Designer/DeckSetup/SlotOverflowMenu.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupContainer.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupToolbox.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/HoveredItem.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedHoveredItems.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SlotOverflowMenu.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/pages/Designer/OffDeck/index.tsx
  protocol-designer/src/step-forms/utils/index.ts
Labels: authorship

#18121 fix(protocol-designer): show blockedSlot when trying to drop over a trash
  protocol-designer/src/labware-ingred/utils.ts
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/step-forms/utils/index.ts
Labels: authorship

#18122 feat(protocol-designer): wire up non-blocking hint modal
  protocol-designer/src/ProtocolRoutes.tsx
  protocol-designer/src/assets/localization/en/alert.json
  protocol-designer/src/components/organisms/HintsModal/__tests__/HintsModal.test.tsx
  protocol-designer/src/components/organisms/HintsModal/index.tsx
  protocol-designer/src/components/organisms/index.ts
Labels: authorship

#18115 feat(protocol-designer): add hardware button to timeline
  protocol-designer/src/assets/localization/en/index.ts
  protocol-designer/src/assets/localization/en/nav.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/components/organisms/Alerts/ErrorContents.tsx
  protocol-designer/src/components/organisms/Alerts/TerminalItemLink.tsx
  protocol-designer/src/components/organisms/FlexHardware/__tests__/FlexHardware.test.tsx
  protocol-designer/src/components/organisms/FlexHardware/index.tsx
  protocol-designer/src/components/organisms/Ot2Modules/__tests__/Ot2Modules.test.tsx
  protocol-designer/src/components/organisms/Ot2Modules/index.tsx
  protocol-designer/src/components/organisms/index.ts
  protocol-designer/src/pages/Designer/DeckSetup/DeckItemHighlight.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupDetails.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/AdapterControls.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/LabwareControls.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/SlotControls.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupContainer.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/HoveredItem.test.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/SelectedHoveredItems.test.tsx
  protocol-designer/src/pages/Designer/LabwareLabel.tsx
  protocol-designer/src/pages/Designer/OffDeck/OffDeckControls.tsx
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/OffDeck/__tests__/OffDeck.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/__tests__/OffDeckDetails.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/DraggableSidebar.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/HardwareStep.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/TerminalItemStep.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/TimelineToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/__tests__/HardwareStep.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/__tests__/TimelineToolbox.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/TimelineEditHardware.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/TimelineEditHardware.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Hardware/__tests__/Hardware.test.tsx
  protocol-designer/src/pages/Hardware/index.tsx
  protocol-designer/src/steplist/types.ts
  protocol-designer/src/top-selectors/labware-locations/index.ts
  protocol-designer/src/top-selectors/timelineFrames.ts
  protocol-designer/src/top-selectors/tip-contents/index.ts
Labels: authorship

#18120 feat(protocol-designer): error handling for editing ot-2 modules and allow for MoaM
  protocol-designer/src/assets/localization/en/protocol_overview.json
  protocol-designer/src/components/molecules/MagnetModuleChangeContent/__tests__/MagnetModuleChangeContent.test.tsx
  protocol-designer/src/components/molecules/MagnetModuleChangeContent/index.tsx
  protocol-designer/src/components/molecules/index.ts
  protocol-designer/src/components/organisms/BlockingHintModal/__tests__/BlockingHintModal.test.tsx
  protocol-designer/src/components/organisms/BlockingHintModal/index.tsx
  protocol-designer/src/components/organisms/KnowledgeLink.tsx
  protocol-designer/src/components/organisms/ModuleEmptySelectorButtons.tsx
  protocol-designer/src/components/organisms/Ot2Modules/__tests__/Ot2Modules.test.tsx
  protocol-designer/src/components/organisms/Ot2Modules/__tests__/util.test.tsx
  protocol-designer/src/components/organisms/Ot2Modules/index.tsx
  protocol-designer/src/components/organisms/Ot2Modules/util.ts
  protocol-designer/src/components/organisms/utils.ts
  protocol-designer/src/load-file/__tests__/reducers.test.ts
  protocol-designer/src/load-file/reducers.ts
  protocol-designer/src/modules/moduleData.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/index.tsx
  protocol-designer/src/pages/Hardware/__tests__/Hardware.test.tsx
  protocol-designer/src/pages/Onboarding/ModuleDiagram.tsx
  protocol-designer/src/pages/Onboarding/SelectOt2Modules.tsx
  protocol-designer/src/pages/Onboarding/constants.ts
  protocol-designer/src/pages/Onboarding/index.tsx
  protocol-designer/src/step-forms/actions/modules.ts
  protocol-designer/src/step-forms/reducers/index.ts
  protocol-designer/src/step-forms/test/reducers.test.ts
  protocol-designer/src/tutorial/selectors.ts
  protocol-designer/src/types.ts
Labels: authorship

#18137 refactor(protocol-designer): order advanced settings chronologically
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/DisposalField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
Labels: authorship

#17815 docs(api): update resin tip docstrings
  api/src/opentrons/protocol_api/instrument_context.py
Labels: docs, papi-v2

#18143 fix(protocol-designer): fix logic for blowoutLocationRequired form-level error
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/dependentFieldsUpdateMoveLiquid.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/test/moveLiquid.test.ts
Labels: authorship

#18155 refactor(protocol-designer): ot-2 modules responsiveness
  components/src/atoms/ListItem/ListItemChildren/ListItemCustomize.tsx
  protocol-designer/src/components/organisms/Ot2Modules/index.tsx
  protocol-designer/src/pages/Hardware/index.tsx
Labels: authorship

#18163 docs(api): flow rates are measured in µL/s
  api/docs/v2/pipettes/characteristics.rst
Labels: docs, papi-v2

#18148 refactor(protocol-designer): fix glitching and off-deck view
  protocol-designer/src/components/organisms/LiquidsOverflowMenu/__tests__/LiquidsOverflowMenu.test.tsx
  protocol-designer/src/components/organisms/LiquidsOverflowMenu/index.tsx
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/OffDeck/__tests__/OffDeck.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
Labels: authorship

#18131 feat(protocol-designer): Error handling for editing Flex hardware
  protocol-designer/src/assets/localization/en/protocol_overview.json
  protocol-designer/src/components/organisms/FlexHardware/__tests__/FlexHardware.test.tsx
  protocol-designer/src/components/organisms/FlexHardware/__tests__/getHardwareInSlotInuse.test.tsx
  protocol-designer/src/components/organisms/FlexHardware/__tests__/updateInitialDeckState.test.tsx
  protocol-designer/src/components/organisms/FlexHardware/getHardwareInSlotInUse.ts
  protocol-designer/src/components/organisms/FlexHardware/index.tsx
  protocol-designer/src/components/organisms/FlexHardware/util.ts
  protocol-designer/src/components/organisms/HardwareConfigurator/AddFixtureModal.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/HardwareConfiguratorContainer.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/__tests__/AddFixtureModal.test.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/__tests__/HardwareConfigurator.test.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/__tests__/HardwareConfiguratorContainer.test.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/index.tsx
  protocol-designer/src/components/organisms/HardwareConfigurator/useDeckConfigurationEditing.tsx
  protocol-designer/src/components/organisms/Kitchen/KitchenContext.tsx
  protocol-designer/src/components/organisms/utils.ts
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/pages/Hardware/__tests__/updateInitialDeckState.test.tsx
  protocol-designer/src/pages/Hardware/util.ts
  protocol-designer/src/step-forms/actions/index.ts
  protocol-designer/src/step-forms/reducers/index.ts
  protocol-designer/src/step-forms/selectors/index.ts
Labels: authorship

#18166 feat(protocol-designer): rework tip management mix/transfer settings
  protocol-designer/cypress/support/MixSteps.ts
  protocol-designer/cypress/support/SetupSteps.ts
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/ChangeTipField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/FirstStepMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/FirstStepMoveLiquidTools.tsx
Labels: authorship

#18165 fix(protocol-designer): fix `FlowRateField` max flow rate
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/DisposalField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/FlowRateField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/utils.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/SecondStepMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/__tests__/utils.test.ts
  protocol-designer/src/steplist/formLevel/handleFormChange/utils.ts
Labels: authorship

#18179 feat(labware-library): remove custom labware link from Labware Creator
  labware-library/cypress/e2e/labware-creator/create.cy.js
  labware-library/cypress/e2e/labware-creator/reservoir.cy.js
  labware-library/cypress/e2e/labware-creator/tipRack.cy.js
  labware-library/cypress/e2e/labware-creator/wellPlate.cy.js
  labware-library/src/labware-creator/components/IntroCopy.tsx
  labware-library/src/labware-creator/components/__tests__/FormAlerts.test.tsx
  labware-library/src/labware-creator/components/__tests__/sections/Footprint.test.tsx
  labware-library/src/labware-creator/components/alerts/FormAlerts.tsx
  labware-library/src/labware-creator/components/alerts/XYDimensionAlerts.tsx
  labware-library/src/labware-creator/fields.ts
Labels: authorship

#18180 refactor(labware-library, app, shared-data): add adapter/labware comb…
  app/src/organisms/Desktop/Labware/LabwareCard/index.tsx
  app/src/organisms/Desktop/Labware/LabwareDetails/index.tsx
  labware-library/src/components/LabwareDetails/LabwareTitle.tsx
  labware-library/src/components/LabwareList/LabwareCard.tsx
  shared-data/js/helpers/index.ts
Labels: authorship

#18181 docs(api): deprecate combination adapters
  api/docs/v2/new_labware.rst
Labels: docs, papi-v2

#18183 fix(protocol-designer): update trash snackbar and increase TC error h…
  protocol-designer/src/assets/localization/en/onboarding.json
  protocol-designer/src/assets/localization/en/protocol_overview.json
  protocol-designer/src/components/organisms/Ot2Modules/__tests__/Ot2Modules.test.tsx
  protocol-designer/src/components/organisms/Ot2Modules/index.tsx
Labels: authorship

#18153 feat(protocol-designer): introduce sentry
  .github/workflows/pd-test-build-deploy.yaml
  protocol-designer/package.json
  protocol-designer/src/index.tsx
  protocol-designer/src/resources/ProtocolDesignerAppFallback.tsx
  protocol-designer/src/resources/sentry.ts
  protocol-designer/vite.config.mts
  yarn.lock
Labels: authorship

#18200 feat(step-generation): add python to `aspirateInPlace`
  step-generation/src/__tests__/aspirateInPlace.test.ts
  step-generation/src/commandCreators/atomic/aspirateInPlace.ts
Labels: authorship
