Repository Opentrons/opentrons, pull requests merged in 2025-08, with the labels that each got.

#19101 fix(protocol-designer): ensure module does not disappear when clearing labware
  protocol-designer/src/components/organisms/LabwareCardOverflowMenu/index.tsx
Labels: authorship

#19106 fix(opentrons-ai-client): fix chat form border-radius issue
  opentrons-ai-client/src/molecules/InputPrompt/index.tsx
  opentrons-ai-client/src/molecules/InputPrompt/inputprompt.module.css
Labels: authorship

#19111 fix(app): fix air gap volume range calc
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/AirGap.tsx
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/__tests__/AirGap.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/__tests__/QuickTransferAdvancedSettings/AirGap.test.tsx
  app/src/organisms/ODD/QuickTransferFlow/utils/getAspirateAirGapVolumeRange.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/getDispenseAirGapVolumeRange.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/index.ts
Labels: authorship

#19132 fix(protocol-designer): restore tip position behavior on BatchEdit
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/PositionField.tsx
Labels: authorship

#19131 fix(app): fix liquid name issue in getLiquidClassName
  app/src/organisms/ODD/QuickTransferFlow/utils/createQuickTransferFile.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/generateQuickTransferArgs.ts
Labels: authorship

#19145 fix(protocol-designer): deck view size issue
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/utils.test.ts
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
Labels: authorship

#19140 fix(protocol-designer): fix height and padding in ProtocolSteps
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Designer/index.tsx
Labels: authorship

#19165 fix(protocol-designer): scroll to bottom of SelectBasics in onboarding
  protocol-designer/src/pages/Onboarding/SelectBasics.tsx
Labels: authorship

#19187 feat(protocol-designer,-step-generation): refacator return tip feature flag
  protocol-designer/src/assets/localization/en/feature_flags.json
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/components/organisms/Settings/__tests__/FeatureFlag.test.tsx
  protocol-designer/src/feature-flags/reducers.ts
  protocol-designer/src/feature-flags/selectors.ts
  protocol-designer/src/feature-flags/types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/DropTipField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/FirstStepMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/__tests__/MixTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/FirstStepMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/FirstStepMoveLiquidTools.test.tsx
Labels: authorship

#19212 fix(protocol-designer): fix word-break property
  protocol-designer/src/components/organisms/AssignLiquidsModal/index.tsx
Labels: authorship

#19215 feat(opentrons-ai-client): add ErrorBoundary to opentrons-ai-client
  opentrons-ai-client/src/OpentronsAI.tsx
  opentrons-ai-client/src/OpentronsAIRoutes.tsx
  opentrons-ai-client/src/assets/localization/en/protocol_generator.json
  opentrons-ai-client/src/assets/localization/en/shared.json
  opentrons-ai-client/src/resources/AiAppFallback.tsx
  opentrons-ai-client/src/resources/__tests__/AiAppFallback.test.tsx
Labels: authorship

#19217 feat(step-generation): reassign tipracks before `_with_liquid_class` emission
  step-generation/src/commandCreators/compound/consolidate.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/utils/liquidClassUtils.ts
Labels: authorship

#19237 docs: stacker manual fast fix for style uniformity
  docs/stacker-manual/docs/index.md
  docs/stacker-manual/docs/warranty.md
Labels: docs, mkdocs

#19103 docs: heater-shaker instruction manual
  docs/heater-shaker/docs/adapters.md
  docs/heater-shaker/docs/compliance.md
  docs/heater-shaker/docs/flex-installation.md
  docs/heater-shaker/docs/images/3-dot-menu.png
  docs/heater-shaker/docs/images/WEEE.svg
  docs/heater-shaker/docs/images/adapter-alignment.png
  docs/heater-shaker/docs/images/adapter-attachment.png
  docs/heater-shaker/docs/images/devices.png
  docs/heater-shaker/docs/images/din-power-connector.png
  docs/heater-shaker/docs/images/heater-shaker-hero.png
  docs/heater-shaker/docs/images/hot-surface-warning.svg
  docs/heater-shaker/docs/images/hs-anchors.png
  docs/heater-shaker/docs/images/hs-caddy.png
  docs/heater-shaker/docs/images/hs-deck-map.png
  docs/heater-shaker/docs/images/hs-parts.png
  docs/heater-shaker/docs/images/hs-with-labels.png
  docs/heater-shaker/docs/images/hs-with-labels.svg
  docs/heater-shaker/docs/images/module-icon-dark.svg
  docs/heater-shaker/docs/images/module-status.png
  docs/heater-shaker/docs/images/pinch-point-warning.svg
  docs/heater-shaker/docs/images/thermal-adapters.png
  docs/heater-shaker/docs/index.md
  docs/heater-shaker/docs/maintenance.md
  docs/heater-shaker/docs/ot2-installation.md
  docs/heater-shaker/docs/preinstall.md
  docs/heater-shaker/docs/software-control.md
  docs/heater-shaker/docs/specifications.md
  docs/heater-shaker/docs/warranty.md
  docs/heater-shaker/mkdocs.yml
  docs/mkdocs.yml
  docs/shared/icons/opentrons/heater-shaker.svg
  docs/shared/instruction-manuals.css
  docs/shared/modules/index.md
Labels: docs, mkdocs

#19245 feat(step-generation): display timeline error when closing TC with in…
  shared-data/js/getLabware.ts
  step-generation/src/__tests__/thermocyclerAtomicCommands.test.ts
  step-generation/src/__tests__/thermocyclerCloseLid.test.ts
  step-generation/src/commandCreators/atomic/thermocyclerCloseLid.ts
  step-generation/src/errorCreators.ts
  step-generation/src/types.ts
Labels: authorship

#19250 fix(step-generation): fix multiWellHandling isSupported check
  step-generation/src/utils/misc.ts
Labels: authorship

#19213 feat(docs): enforce that mkdocs build without warnings
  docs/Makefile
  docs/flex/docs/installation/requirements.md
  docs/flex/docs/labware/index.md
  docs/flex/docs/modules/absorbance-plate-reader.md
  docs/flex/docs/modules/heater-shaker.md
  docs/flex/docs/modules/hepa-uv.md
  docs/flex/docs/modules/index.md
  docs/flex/docs/modules/magnetic-block.md
  docs/flex/docs/modules/temperature.md
  docs/flex/docs/opentrons-app.md
  docs/flex/docs/protocols/designer.md
  docs/flex/docs/protocols/index.md
  docs/flex/docs/safety-regulatory.md
  docs/flex/docs/system-description/specs.md
  docs/flex/docs/touchscreen/index.md
  docs/hepa-uv/docs/product-specifications.md
  docs/mkdocs.yml
  docs/thermocycler-manual/docs/compliance.md
  docs/thermocycler-manual/docs/preinstall.md
Labels: mkdocs

#19293 fix(app): fix default touchTip values when no liquid class is selecte…
  app/src/organisms/ODD/QuickTransferFlow/QuickTransferAdvancedSettings/TouchTip.tsx
  app/src/organisms/ODD/QuickTransferFlow/utils/retrieveLiquidClassValues.ts
Labels: authorship

#19291 fix(app): fix configuration values in aspirate/dispense
  app/src/organisms/ODD/QuickTransferFlow/Aspirate/hooks/useAspirateSettingsConfig.ts
  app/src/organisms/ODD/QuickTransferFlow/Dispense/hooks/useDispenseSettingsConfig.ts
Labels: authorship

#19284 docs: thermocycler-remove-h1-titles
  docs/thermocycler-manual/docs/compliance.md
  docs/thermocycler-manual/docs/flex-installation.md
  docs/thermocycler-manual/docs/index.md
  docs/thermocycler-manual/docs/lid-seals.md
  docs/thermocycler-manual/docs/maintenance.md
  docs/thermocycler-manual/docs/ot2-installation.md
  docs/thermocycler-manual/docs/preinstall.md
  docs/thermocycler-manual/docs/specifications.md
  docs/thermocycler-manual/mkdocs.yml
Labels: docs, mkdocs

#19310 fix(app): fix invalid array range error
  app/src/organisms/ODD/QuickTransferFlow/utils/getTransferPlanAndReferenceVolumes.ts
Labels: authorship

#19313 feat(step-generation): TipRack Lid Journey 2: Tracking Chronicles
  protocol-designer/src/assets/localization/en/alert.json
  protocol-designer/src/labware-ingred/utils.ts
  step-generation/src/__tests__/replaceTip.test.ts
  step-generation/src/commandCreators/compound/replaceTip.ts
  step-generation/src/errorCreators.ts
  step-generation/src/robotStateSelectors.ts
  step-generation/src/types.ts
Labels: authorship

#19329 feat(step-generation): tipRack Lid Journey 3: One Source to Rule Them All
  app/src/organisms/ODD/QuickTransferFlow/__tests__/utils/quickTransferStepCommands.test.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/pythonDef.ts
  protocol-designer/src/file-data/__tests__/createFile.test.ts
  step-generation/src/__tests__/configureNozzleLayout.test.ts
  step-generation/src/__tests__/consolidate.test.ts
  step-generation/src/__tests__/distribute.test.ts
  step-generation/src/__tests__/pythonFileUtils.test.ts
  step-generation/src/__tests__/transfer.test.ts
  step-generation/src/commandCreators/atomic/configureNozzleLayout.ts
  step-generation/src/commandCreators/compound/consolidate.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/commandCreators/compound/replaceTip.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/robotStateSelectors.ts
  step-generation/src/utils/liquidClassUtils.ts
  step-generation/src/utils/pythonFileUtils.ts
Labels: authorship

#19357 fix(protocol-designer) fix white screen when stepName is undefined
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/ConnectedStepInfo.tsx
Labels: authorship

#19364 feat(step-generation): wire up return tip in step generation
  step-generation/src/__tests__/consolidate.test.ts
  step-generation/src/__tests__/distribute.test.ts
  step-generation/src/__tests__/mix.test.ts
  step-generation/src/__tests__/transfer.test.ts
  step-generation/src/commandCreators/compound/consolidate.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/commandCreators/compound/mix.ts
  step-generation/src/commandCreators/compound/transfer.ts
Labels: authorship

#19375 feat(protocol-designer, step-generation): allow no trash or waste chute in PD
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepButton.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Onboarding/SelectFlexHardware.tsx
  step-generation/src/__tests__/replaceTip.test.ts
  step-generation/src/commandCreators/compound/consolidate.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/commandCreators/compound/replaceTip.ts
  step-generation/src/commandCreators/compound/transfer.ts
Labels: authorship

#19369 fix(protocol-designer): fix import modal close behavior
  protocol-designer/src/components/organisms/FileUploadMessagesModal/index.tsx
Labels: authorship

#19380 feat(step-generation): emit load_lid_stack() on an adapter
  step-generation/src/__tests__/pythonFileUtils.test.ts
  step-generation/src/utils/pythonFileUtils.ts
Labels: authorship

#19386 refactor(protocol-designer): remove return tip feature flag
  protocol-designer/src/components/organisms/Settings/__tests__/FeatureFlag.test.tsx
  protocol-designer/src/feature-flags/reducers.ts
  protocol-designer/src/feature-flags/selectors.ts
  protocol-designer/src/feature-flags/types.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/DropTipField.tsx
Labels: authorship

#19393 fix(protocol-designer): style fixes for tip management in PD
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/ChangeTipField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MixTools/FirstStepMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/FirstStepMoveLiquidTools.tsx
Labels: authorship

#19376 feat(protocol-designer): add autofocus to define liquid modal input
  protocol-designer/src/components/organisms/DefineLiquidsModal/index.tsx
Labels: authorship

#19299 feat(protocol-designer): create LabwareButton and use in SlotDetailModal
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/assets/localization/en/starting_deck_state.json
  protocol-designer/src/components/atoms/LabwareButton/index.tsx
  protocol-designer/src/components/atoms/LabwareButton/labwarebutton.module.css
  protocol-designer/src/components/atoms/index.ts
  protocol-designer/src/components/molecules/LabwareButtonBasket/LabwareButtonBasket.stories.tsx
  protocol-designer/src/components/molecules/LabwareButtonBasket/index.tsx
  protocol-designer/src/components/molecules/LabwareButtonBasket/labwarebuttonbasket.module.css
  protocol-designer/src/components/molecules/index.ts
  protocol-designer/src/components/organisms/SlotDetailModal/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupToolbox.tsx
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/ActiveLabwareControls.tsx
  protocol-designer/src/pages/Designer/DeckSetup/__tests__/DeckSetupToolbox.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/OffDeckControls.tsx
Labels: authorship

#19414 feat(protocol-designer): remove Lids from being behind ff
  components/src/molecules/CustomizeExpandButton/__tests__/CustomizeExpandButton.test.tsx
  components/src/molecules/CustomizeExpandButton/index.tsx
  protocol-designer/src/assets/localization/en/feature_flags.json
  protocol-designer/src/components/organisms/SelectLabwareModal/SelectCustomLabware.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/SelectLabware.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/SelectLabwareOnAdapter.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/SelectLidOnLabware.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/__tests__/SelectLabwareModal.test.tsx
  protocol-designer/src/components/organisms/SelectLabwareModal/index.tsx
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLabwareTools/LabwareLocationField.tsx
Labels: authorship

#19413 chore(protocol-designer): add bundle analyzer for performance tuning
  protocol-designer/Makefile
  protocol-designer/package.json
  protocol-designer/vite.config.mts
  yarn.lock
Labels: authorship
