Repository Opentrons/opentrons, pull requests merged in 2025-02, with the labels that each got.

#17401 fix(protocol-designer): fix StepSummary wrapping
  protocol-designer/src/pages/Designer/ProtocolSteps/StepSummary.tsx
Labels: authorship

#17397 fix(protocol-designer): delete labware if staging area deleted
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupTools.tsx
  protocol-designer/src/pages/Designer/DeckSetup/FixtureRender.tsx
  protocol-designer/src/pages/Designer/DeckSetup/utils.ts
  protocol-designer/src/utils/index.ts
Labels: authorship

#17368 feat(protocol-designer): add submerge for aspirate and dispense
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/assets/localization/en/application.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/assets/localization/en/tooltip.json
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/index.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
Labels: authorship

#17394 fix(protocol-designer, components) fix deck view size issue
  components/src/atoms/buttons/EmptySelectorButton.tsx
  protocol-designer/src/ProtocolEditor.tsx
  protocol-designer/src/ProtocolRoutes.tsx
  protocol-designer/src/pages/Designer/DeckSetup/DeckSetupContainer.tsx
  protocol-designer/src/pages/Designer/OffDeck/HighlightOffdeckSlot.tsx
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/OffDeck/__tests__/OffDeck.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/__tests__/OffDeckDetails.test.tsx
  protocol-designer/src/pages/Designer/OffDeck/index.tsx
  protocol-designer/src/pages/Designer/Offdeck/index.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/DraggableSidebar.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepSummary.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/ProtocolSteps.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Designer/__tests__/Designer.test.tsx
  protocol-designer/src/pages/Designer/index.tsx
Labels: authorship

#17427 fix(shared-data): tc lids are schema v2 now
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[2b866b03f3][Flex_S_v2_21_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
  shared-data/js/labware.ts
  shared-data/js/types.ts
  shared-data/labware/definitions/2/opentrons_tough_pcr_auto_sealing_lid/1.json
  shared-data/labware/definitions/3/opentrons_tough_pcr_auto_sealing_lid/2.json
  shared-data/labware/schemas/2.json
Labels: gen-analyses-snapshot-pr

#17439 fix(protocol-designer): fix step overflow menu position
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepOverflowMenu.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/__tests__/StepOverflowMenu.test.tsx
Labels: authorship

#17444 fix(protocol-designer): fix presaved absorbance reader step form type
  protocol-designer/src/step-forms/utils/createPresavedStepForm.ts
Labels: authorship

#17440 fix(protocol-designer): various DQA fixes
  components/src/atoms/ListButton/__tests__/ListButton.test.tsx
  components/src/atoms/ListButton/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/Initialization.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/AddStepOverflowButton.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/ConnectedStepInfo.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/__tests__/AddStepButton.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/__tests__/ProtocolSteps.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
Labels: authorship

#17443 fix(components, protocol-designer): fix design bugs from PD 8.4.0 alpha.1
  components/src/molecules/DropdownMenu/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/AbsorbanceReaderTools/Initialization.tsx
  protocol-designer/src/ui/modules/selectors.ts
Labels: authorship

#17433 fix(protocol-designer, step-generation): update prewet behavior in PD
  protocol-designer/src/assets/localization/en/tooltip.json
  protocol-designer/src/molecules/ToggleStepFormField/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/LabwareField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepFormToolbox.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/index.tsx
  step-generation/src/__tests__/distribute.test.ts
  step-generation/src/commandCreators/compound/distribute.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/fixtures/commandFixtures.ts
Labels: authorship

#17448 fix(components, protocol-designer): fix lineclamp for dropdown menu
  components/src/molecules/DropdownMenu/index.tsx
  protocol-designer/src/molecules/DropdownStepFormField/index.tsx
Labels: authorship

#17447 fix(protocol-designer): fix temperature step form
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/src/pages/Designer/ProtocolSteps/StepSummary.tsx
  protocol-designer/src/steplist/formLevel/errors.ts
Labels: authorship

#17457 fix(protocol-designer): fix HighlightItems logic
  protocol-designer/src/pages/Designer/DeckSetup/HighlightItems.tsx
Labels: authorship

#17479 fix(protocol-designer): fix OffDeckDetails container flicker
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
Labels: authorship

#17485 fix(protocol-designer): fix adding module logic of magnetic block
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/utils.test.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/utils.tsx
Labels: authorship

#17490 fix(protocol-designer): set form field value if 1 option, add newLocation error
  protocol-designer/src/molecules/DropdownStepFormField/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/__tests__/MagnetTools.test.tsx
Labels: authorship

#17470 refactor(protocol-designer): initial refactoring of MoveLiquidTools
  protocol-designer/src/__fixtures__/formDataForSingleStep.json
  protocol-designer/src/__fixtures__/propsForFieldsForSingleStep.json
  protocol-designer/src/load-file/migration/utils/getMigrationPositionFromTop.ts
  protocol-designer/src/organisms/TipPositionModal/index.tsx
  protocol-designer/src/organisms/WellOrderModal/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/BatchEditToolbox/BatchEditMixTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/BatchEditToolbox/BatchEditMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/FlowRateField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/PositionField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/WellsOrderField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/MultipleStepsMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SingleStepMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/MoveLiquidTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/SingleStepMoveLiquidTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/index.tsx
  protocol-designer/src/resources/types.ts
  protocol-designer/src/steplist/formLevel/errors.ts
Labels: authorship

#17498 fix(shared-data): Change defaultReturnTipHeight values for 96 channel pipettes
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[0190369ce5][Flex_S_v2_16_P1000_96_GRIP_HS_MB_TC_TM_DeckConfiguration1NoFixtures].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[248a2a3107][pl_Omega_HDQ_DNA_Cells_Flex_96_channel].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[2b866b03f3][Flex_S_v2_21_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[2eaf98de6a][Flex_S_v2_16_P1000_96_GRIP_HS_MB_TC_TM_TriggerPrepareForMountMovement].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[3cf6a3778e][Flex_S_v2_18_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[42beea80be][pl_96_ch_demo_rtp].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[5c57add326][pl_Omega_HDQ_DNA_Bacteria_Flex_96_channel].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[6e34343cfc][Flex_S_v2_15_P1000_96_GRIP_HS_MB_TM_MagMaxRNAExtraction].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[88abcfdbca][pl_Zymo_Quick_RNA_Cells_Flex_96_Channel].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[95da6fbef2][Flex_S_2_15_P1000M_GRIP_HS_TM_MB_OmegaHDQDNAExtractionBacteria].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[a08c261369][Flex_S_v2_16_P1000_96_GRIP_DeckConfiguration1NoModulesNoFixtures].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[a4d3b3a2d3][pl_96_ch_demo_rtp_with_hs].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[ac886d7768][Flex_S_v2_15_P1000_96_GRIP_HS_MB_TC_TM_IDTXgen96Part1to3].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[b91d31eaa2][pl_MagMax_RNA_Cells_Flex_96_Channel].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[cecd51c8ee][pl_ExpressPlex_96_final].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[d391213095][Flex_S_v2_15_P1000_96_GRIP_HS_TM_QuickZymoMagbeadRNAExtractionCellsOrBacteria].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[d3b28ea1d7][pl_Zymo_Magbead_DNA_Cells_Flex_96_channel].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[dabb7872d8][Flex_S_v2_19_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[f24bb0b4d9][Flex_S_v2_15_P1000_96_GRIP_HS_MB_TC_TM_IlluminaDNAPrep96PART3].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[f51172f73b][Flex_S_v2_16_P1000_96_GRIP_HS_MB_TC_TM_Smoke].json
  shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/default/1_0.json
  shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/default/3_0.json
  shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/default/3_3.json
  shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/default/3_4.json
  shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/default/3_5.json
  shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/default/3_6.json
  shared-data/pipette/definitions/2/liquid/ninety_six_channel/p200/default/3_0.json
  step-generation/src/__tests__/__snapshots__/fixtureGeneration.test.ts.snap
Labels: gen-analyses-snapshot-pr

#17519 updating latest apilevel in docs to 2.22
  api/docs/v2/conf.py
  api/docs/v2/versioning.rst
Labels: docs, papi-v2

#17502 refactor(protocol-designer): fix TextArea key issue and replace styled textareas
  protocol-designer/cypress/support/MixSteps.ts
  protocol-designer/src/molecules/TextAreaField/index.tsx
  protocol-designer/src/organisms/DefineLiquidsModal/LiquidClassDropdown.tsx
  protocol-designer/src/organisms/DefineLiquidsModal/LiquidColorPicker.tsx
  protocol-designer/src/organisms/DefineLiquidsModal/__tests__/swatchColors.test.tsx
  protocol-designer/src/organisms/DefineLiquidsModal/__tests__/util.test.ts
  protocol-designer/src/organisms/DefineLiquidsModal/index.tsx
  protocol-designer/src/organisms/DefineLiquidsModal/util.ts
  protocol-designer/src/organisms/EditProtocolMetadataModal/index.tsx
  protocol-designer/src/organisms/RenameStepModal/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/CommentTools/__tests__/CommentTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/CommentTools/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/PauseTools/index.tsx
Labels: authorship

#17540 feat(api): add setStoredLabware command
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[057de2035d][OT2_S_v2_19_P300M_P20S_HS_TC_TM_SmokeTestV3].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[0cbde10c37][OT2_S_v2_18_P300M_P20S_HS_TC_TM_SmokeTestV3].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[13ec753045][Flex_S_v2_18_Illumina_Stranded_total_RNA_Ribo_Zero].json
  analyses-snapshot-testing/tests/__snapshots__/analyses_snapshot_test/test_analysis_snapshot[b777168ac1][Flex_S_v2_19_Illumina_Stranded_total_RNA_Ribo_Zero].json
  api/src/opentrons/protocol_engine/commands/command_unions.py
  api/src/opentrons/protocol_engine/commands/flex_stacker/__init__.py
  api/src/opentrons/protocol_engine/commands/flex_stacker/set_stored_labware.py
  api/src/opentrons/protocol_engine/commands/flex_stacker/store.py
  api/src/opentrons/protocol_engine/errors/exceptions.py
  api/src/opentrons/protocol_engine/execution/equipment.py
  api/src/opentrons/protocol_engine/state/geometry.py
  api/src/opentrons/protocol_engine/state/module_substates/flex_stacker_substate.py
  api/src/opentrons/protocol_engine/state/modules.py
  api/src/opentrons/protocol_engine/state/update_types.py
  api/tests/opentrons/protocol_engine/commands/flex_stacker/test_retrieve.py
  api/tests/opentrons/protocol_engine/commands/flex_stacker/test_store.py
  api/tests/opentrons/protocol_engine/commands/test_load_labware.py
  api/tests/opentrons/protocol_engine/state/test_flex_stacker_state.py
  api/tests/opentrons/protocol_engine/state/test_geometry_view.py
  shared-data/command/schemas/12.json
  shared-data/command/types/module.ts
Labels: gen-analyses-snapshot-pr

#17537 fix(protocol-designer): support more than three steps
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/FirstStepMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/FirstStepMoveLiquidTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/MoveLiquidTools.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/index.tsx
Labels: authorship

#17522 feat(protocol-designer): send error stack to mixpanel for debugging
  protocol-designer/src/resources/ProtocolDesignerAppFallback.tsx
  protocol-designer/src/resources/__tests__/ProtocolDesignerAppFallback.test.tsx
Labels: authorship

#17531 fix(protocol-designer): remove dropdown menu for module quantity
  protocol-designer/src/organisms/SelectModules/AddModuleEmptySelectorButton.tsx
  protocol-designer/src/organisms/SelectModules/__tests__/AddModuleEmptySelectorButton.test.tsx
  protocol-designer/src/organisms/SelectModules/__tests__/SelectModules.test.tsx
  protocol-designer/src/organisms/SelectModules/index.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/SelectModules.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/__tests__/utils.test.ts
  protocol-designer/src/pages/CreateNewProtocolWizard/index.tsx
  protocol-designer/src/pages/CreateNewProtocolWizard/utils.tsx
Labels: authorship

#17525 fix(protocol-designer, components): fix height diff issue between on and off
  components/src/atoms/ToggleGroup/index.tsx
  protocol-designer/src/atoms/constants.ts
  protocol-designer/src/pages/Designer/OffDeck/OffDeckDetails.tsx
  protocol-designer/src/pages/Designer/OffDeck/index.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/index.tsx
  protocol-designer/src/pages/Designer/index.tsx
Labels: authorship

#17545 feat(protocol-designer): introduce touch tip speed field to moveLiquid
  app/src/organisms/ODD/QuickTransferFlow/types.ts
  app/src/organisms/ODD/QuickTransferFlow/utils/generateQuickTransferArgs.ts
  components/src/atoms/ListButton/index.tsx
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/fixtures/protocol/8/thermocyclerOnOt2V7MigratedToV8.json
  protocol-designer/src/assets/localization/en/form.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/molecules/CheckboxExpandStepFormField/index.tsx
  protocol-designer/src/molecules/ToggleStepFormField/index.tsx
  protocol-designer/src/organisms/TipPositionModal/ZTipPositionModal.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/BlowoutOffsetField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/DisposalField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/PositionField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/errors.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/index.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/moveLiquidFormToArgs.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/timelineMiddleware/__tests__/generateRobotStateTimeline.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
  shared-data/command/types/pipetting.ts
  step-generation/src/commandCreators/compound/transfer.ts
  step-generation/src/types.ts
Labels: authorship

#17573 fix(protocol-designer) fix text style and paddings in GateModal
  protocol-designer/src/organisms/GateModal/__tests__/GateModal.test.tsx
  protocol-designer/src/organisms/GateModal/index.tsx
Labels: authorship

#17586 fix(protocol-designer): fix whitescreen after deleting labware
  protocol-designer/src/pages/Designer/ProtocolSteps/StepSummary.tsx
Labels: authorship

#17593 fix(protocol-designer, shared-data): update command schema to v10
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/mix_8_0_0.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/fixtures/protocol/8/thermocyclerOnOt2V7MigratedToV8.json
  protocol-designer/src/file-data/selectors/fileCreator.ts
  shared-data/protocol/types/schemaV8/index.ts
Labels: authorship

#17592 fix(protocol-designer): Add viewport size to mixpanel
  protocol-designer/src/analytics/mixpanel.ts
Labels: authorship

#17590 feat(protocol-designer, step-generation): add `prepareToAspirate`
  protocol-designer/src/steplist/substepTimeline.ts
  protocol-designer/src/steplist/test/getPreviousMoveToAddressableAreaCommand.test.ts
  protocol-designer/src/steplist/utils/getPreviousMoveToAddressableAreaCommand.ts
  shared-data/command/types/pipetting.ts
  step-generation/src/__tests__/movableTrashCommandsUtil.test.ts
  step-generation/src/__tests__/prepareToAspirate.test.ts
  step-generation/src/__tests__/wasteChuteCommandsUtil.test.ts
  step-generation/src/commandCreators/atomic/index.ts
  step-generation/src/commandCreators/atomic/prepareToAspirate.ts
  step-generation/src/getNextRobotStateAndWarnings/index.ts
  step-generation/src/utils/movableTrashCommandsUtil.ts
  step-generation/src/utils/wasteChuteCommandsUtil.ts
Labels: authorship

#17411 feat(protocol-designer, components): add retract for aspirate and dispense to PD
  components/src/atoms/ListButton/ListButton.stories.tsx
  components/src/atoms/ListButton/__tests__/ListButton.test.tsx
  components/src/atoms/ListButton/index.tsx
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/assets/localization/en/modal.json
  protocol-designer/src/assets/localization/en/protocol_steps.json
  protocol-designer/src/assets/localization/en/tooltip.json
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/organisms/TipPositionModal/index.tsx
  protocol-designer/src/organisms/TipPositionModal/utils.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/PositionField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/PipetteFields/utils.ts
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/MultiInputField.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/SecondStepsMoveLiquidTools.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/StepTools/MoveLiquidTools/__tests__/MultiInputField.test.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/StepForm/utils.ts
  protocol-designer/src/resources/types.ts
  protocol-designer/src/resources/utils/__tests__/index.test.ts
  protocol-designer/src/resources/utils/index.ts
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
Labels: authorship

#17598 fix(protocol-designer): add non-active error state style to StepContainer
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/StepContainer.tsx
  protocol-designer/src/pages/Designer/ProtocolSteps/Timeline/__tests__/StepContainer.test.tsx
Labels: authorship

#17599 feat(protocol-designer): add `liquidClassesSupported` field to liquid forms
  protocol-designer/fixtures/protocol/8/doItAllV3MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV4MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
  protocol-designer/fixtures/protocol/8/doItAllV8.json
  protocol-designer/fixtures/protocol/8/example_1_1_0MigratedToV8.json
  protocol-designer/fixtures/protocol/8/newAdvancedSettingsAndMultiTemp.json
  protocol-designer/fixtures/protocol/8/ninetySixChannelFullAndColumn.json
  protocol-designer/src/form-types.ts
  protocol-designer/src/load-file/migration/8_5_0.ts
  protocol-designer/src/step-forms/test/createPresavedStepForm.test.ts
  protocol-designer/src/steplist/formLevel/getDefaultsForStepType.ts
  protocol-designer/src/steplist/formLevel/stepFormToArgs/test/stepFormToArgs.test.ts
  protocol-designer/src/steplist/formLevel/test/getDefaultsForStepType.test.ts
  protocol-designer/src/ui/steps/test/selectors.test.ts
Labels: authorship

#17600 fix(protocol-designer) fix drag and drop flickering issue
  protocol-designer/src/pages/Designer/DeckSetup/Overlays/SlotOverlay.tsx
Labels: authorship
